### ISSUE TITLE
.exe samples do not work when installed

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#1000]
When a user builds Urho3D from source and installs the results, none of the samples work.  They all give an error dialog: "ERROR: Failed to add resource path 'Data', check the documentation on how to set the 'resource path prefix' "  The samples work in the build directory just fine, due to resolution of #994.  However the resource path is not valid for the final installation directory.

Several possibilities exist for solving the problem.  A claimed complication is that on Unix systems, the user may use DESTDIR to change the installation target.  The effective prefix becomes $(DESTDIR)/${CMAKE_INSTALL_PREFIX} and it will only be known at installation time, after CMake has generated a native build system.  This makes it difficult but not impossible to use an absolute path, as the method for capturing DESTDIR would be build system or OS specific.  One for instance could capture it in a Bourne shell script.  This means the target development environment would have to use Bourne shell scripts, which may not always be a valid assumption.  A recent post on the CMake mailing list, asked how to handle DESTDIR in a generator agnostic manner, and claimed to have problems using the Ninja generator.  Nobody answered his question.

Easier approach: a relative path would work fine, as the end result is just installation to 1 directory somewhere.  The Urho3D installation tree structure is static and known at configuration time.

DESTDIR is a Unix-specific complication, it doesn't affect Windows.  Windows systems cannot use DESTDIR because they have a drive letter as part of an absolute path.  Concatenating absolute paths on Windows doesn't produce a valid path.  This is documented in the CMake docs and nobody uses DESTDIR on Windows.  Or if they do, they deserve what they get.

DESTDIR can also mess up various aspects of a CMake build even on a Unix system.  At least as of 2011 Alexander Neundorf, a principal CMake developer, claimed it would mess up RPATH.  http://cmake.3232098.n2.nabble.com/DESTDIR-behaviour-with-different-variable-name-td6261440.html   
```
DESTDIR has a different purpose.
Installing to DESTDIR does not necessarily lead to a working and correct
installation, mainly when paths are involved, like e.g. RPATH settings.
Assuming that CMAKE_INSTALL_PREFIX would be /opt/foo, your executable might
get /opt/foo/lib as RPATH, also when installed to $DESTDIR/opt/foo.
So they will not have a correct RPATH.
You really should set CMAKE_INSTALL_PREFIX.
```

Ergo, having the samples obtain a relative resource path, that is different for the build and installation trees, would be a sensible way to fix this.  One way to obtain such a path is to have a file such as "resources.ini" in the same directory as the samples.  It would contain the needed relative path and be read by the samples.  The contents of resources.ini would be changed at build and installation times.

**Comment by weitjong** [comment]
I will let someone else to propose for a good solution to this, but I would like just to add the following points.

- Our RPATH setup has been working correctly since last year for Linux, Raspberry Pi, and Mac OS X. See https://github.com/urho3d/Urho3D/blame/master/Source/CMakeLists.txt#L30-L51. No issue has been reported so far, even with DESTDIR is being used during installation (we have tested the staged install in one of the tests we run in our CI servers - see https://github.com/urho3d/Urho3D/blob/master/Rakefile#L560 for Linux and https://github.com/urho3d/Urho3D/blob/master/Rakefile#L710 for Mac)

- The fact that DESDIR is not required on Windows platform is well known. We have documented how to install Urho3D library here http://urho3d.github.io/documentation/HEAD/_building.html#Building_Library with the extra note for Windows user on how to remedy the Windows deficiency in runtime path handling. 

The crux of the problem is, the absolute path of the installation location is not known at the build tree generation time (unless Urho3D only supports Windows platform), so there is no bullet proof way for CMake to supply this information that works cross-platform. However, the relative path between the Urho3D-specific sample asset directories and the sample binaries are known at the build tree generation time. That information could be used. For example it has been used this way in the NinjaSnowWar.bat/.sh and Editor.bat/.sh scripts. Note that these helper/wrapper scripts already exist long before and are not newly created just for this purpose. The rest of the sample apps do not have this helper/wrapper script. Personally I don't think creating a helper/wrapper script is a right thing to do or it would have been done already. Note also that this relative path between the asset directories and binaries is Urho3D project specific. Most of the cases this relative distance do not hold true for user applications in their own projects, so definitely we should not assume that in the Engine code itself, or at the very most just we could just use this assumption for Urho3D sample apps only. Reading the relative path from an external file (as proposed in #994) or reading it from URHO3D_PREFIX_PATH environment variable (as documented in http://urho3d.github.io/documentation/HEAD/_building.html#Building_Native) is more viable than creating wrapper script, if one really have to choose between them.

In any case I hope we do not have to move back to use the old way by installing the binaries and asset directories in a same location, although it may appear to be the easiest solution of all.

**Comment by bvanevery** [comment]
Relying on URHO3D_PREFIX_PATH or any other environmental notion, assumes a stability of development that is often not warranted.  For instance back in the day I kept a Chicken Scheme build working on Visual Studio, MinGW, and Cygwin compilers, with layers of bootstrapping compile stages, different bug testing scenarios, interim fixes, and "don't touch this" original build trees for comparison.  Relying on a single global variable to determine anything, such as the user's environment, would be a nightmare.  It is also the path of least resistance for a lot of people, and results in hard to diagnose bugs when people have stale environment variables from bad builds lying around.  Keeping separate environmental initialization batch scripts / command prompts handy for every test case is certainly possible, but work.  It is better not to rely on magic values from environments at all.

These scenarios are not inconceivable in Urho3D development as, for instance, D3D9, D3D11, and OpenGL are all valid compile targets on Windows.  But, it's a compile time decision, implying 3 different codebases to compare "what is wrong" between versions, if one wants to hunt bugs that way.

Hence why I have suggested the samples directory specific resources.ini method.  It is self-contained.  It also mirrors other Windows practices, i.e. ship this *.dll redistributable in your app directory.

A more exotic technique would be to establish an analytic criterion for "am I in the CMake build directory?" and "am I in the Urho3D installation directory?"  This could be done without any additional magic file, but it requires that the analytic criterion is exceedingly correct.  Some projects have telltale characteristics, others don't.  Another problem for maintenance is such a technique is fragile.  If you change the way you lay out the installation directory, probably it breaks.

**Comment by weitjong** [comment]
> It is better not to rely on magic values from environments at all.

Let's just say we agree to disagree on this point. I have seen many SDKs, not just Urho3D that heavily relying on setting the environment variables correctly in the host system. In fact environment variable is one of those things that work reliably across platforms.

> Hence why I have suggested the samples directory specific resources.ini method. It is self-contained. It also mirrors other Windows practices, i.e. ship this *.dll redistributable in your app directory.

Please remember Urho3D project is a cross-platform project. Solution that works for Windows does not mean it is the right solution for all. Having an *.ini or anything else along side the binary in ```/usr/bin``` directory would be frowned upon.

Any one knows how other cross-platform game engines handle the SDK installation? In ogre-samples software package packaged by Fedora package maintainer, I can see the asset directories are being installed in the ```/usr/share/OGRE/media```, the sample binary is in ```/usr/bin```, and the sample configuration file is in ```/etc/OGRE```, which looks reasonable. However, it does mean that the binary is hard-coded to look for a configuration in the ```/etc/OGRE``` at least for Linux platform.

**Comment by bvanevery** [comment]
It is a pity that the file system equivalent of the "array of structures" vs. "structure of arrays" argument occurs here.  What do Unixy people do?  I don't think OSX people have this dilemma, I think "installation" is moving a folder with all your stuff in it.  Simple like that, I don't think they slice their installation across the file system.  That would be the 2 consumer oriented desktops, yep....

I would suggest regarding the installation directory structure as inviolate, i.e. /share at a known relative path.  Then forcing the build directory to correspond to how the installation directory looks.  Only 1 correct case needs to be considered then, and the assets don't have to be in /bin

**Comment by weitjong** [comment]
Mac OS X is actually much closer to its Unix root than you might think. But at least I agree that they have done a good job at UX. Some of the tools, especially  those that are ported from Linux, are also installed in the ```/usr/bin```, ```/usr/lib```, ```/usr/share``` directories in OSX. In fact I feel right at home when I login into my Mac. I think you are just referring to the ```bundled app``` which as its name implied does bundle everything together. If you remember my last comment in #994, I have already explained that bundling the Urho3D assets into an app is only made possible **after** we have made that related changes to the Urho3D engine so that it does not always assume the assets dirs are located in the bin directory. The good news is, the application bundle system is coming to Linux as well, but until then let's not lose our focus. Alienating any of our user does us no good.

Back to the issue. Aside from difficulty in deciding where to put this external file, I am actually not in favor of this approach until we really have more information read from this file. In Ogre they do have a few information in their configuration file. But this is just my opinion.

> I would suggest regarding the installation directory structure as inviolate, i.e. /share at a known relative path. Then forcing the build directory to correspond to how the installation directory looks. Only 1 correct case needs to be considered then, and the assets don't have to be in /bin

Yes, this may work although it feels a little bit clunky. I am still waiting for other better solutions from others.

**Comment by cadaver** [comment]
Ogre does the following:

Ogre itself doesn't make any assumptions of the resource paths. These must be fully configured by the application, though there are helper functions to parse ini files, from an application-specified path.

However, the samples are a huge amount of platform-specific behavior. They have a FileSystemLayer implementation for each platform, which knows to supply the ini file search paths. These are different for e.g. Windows and Unix. A typical fallback location is the current working directory, which works OK on Windows since on Windows the ini files get installed to the same directory as the executables.

What I would lean toward would be to replicate the .bat's functionality in the sample executables (this can be conditionally compiled for Windows only, and is naturally sample-only code for convenience, not something that should be in the engine itself): if resources are not found in the executable's directory, and a prefix path has not been set already, it tries to search for "../share/Urho3D/Resources" and if found, sets that as the prefix path.

**Comment by weitjong** [comment]
I actually have an idea on how to solve this already but I want to hear from others first, just to make sure no one would say it is yet another Linux-centric solution. The idea is quite similar to yours. At the moment the ```ResourcePrefixPath``` engine parameter is expected to only contain one path. The idea is to allow it to define a list of search paths. The default is still the program/bin dir if it is not defined. In the sample-only code (in fact it should be done in all the binaries that Urho3D SDK installed that require asset resources), we could set this parameter to be "$ORIGIN;$ORIGIN/../share/Urho3D/Resources". The ```$ORIGIN``` stands for the actual bin dir path. This is similar in concept to RPATH entries for searching the shared library. Naturally we will need new C++ API to set/get/append the ```ResourcePrefixPath``` engine parameter or it should become instance variable now. In user own code, they can set the search path to anything they like. If they don't, it still backward compatible to Urho3D previous behavior.

**Comment by bvanevery** [comment]
CMake does all kinds of multiple search path things, so it's not a Linux specific idea.  Important is to canonize and document those default search paths, so that people expect the behavior.  Had some huge argument with some open source guy about that a few months ago, about his path searching and directory installation naming conventions.  He would not accept that CMake actually had well defined search conventions on Windows, even though they're all spelled out in the CMake docs.  They're the sort of thing you would have learned by osmosis if you had done enough CMake builds.  That's how I had learned them; I was relieved that they were actually documented so that I could prove it to this other guy.  But it did not matter because he was a Linuxer and would not be reasoned with that CMake actually has behavior standards for path searching on Windows.

You might start wishing your source tree was laid out with a /share directory.

**Comment by weitjong** [comment]
Our proposed solutions have nothing to do with CMake. The change will be mainly on the C++ source code.

**Comment by bvanevery** [comment]
Of course.  You had a concern that you were proposing "a Linux-centric solution" and that was my roundabout way of saying it isn't particularly.  Other development groups have a multiple search path culture.

**Comment by bvanevery** [comment]
HelloWorld now works when installed.  Good job!  

I'll note in passing that a semicolon is an allowed character in Windows filenames.  In practice it's unlikely to be used, because it has an interpretive meaning for the Windows command prompt and the environment.  Double quotes are used to overcome such issues.
