### ISSUE TITLE
String::Split doesn't emit empty strings for start/end/adjacent separators

### ISSUE THREAD

**Issue by barrettcolin** [urho3d/Urho3D#1014]
Reproducible with 1.4 (it's not convenient for me to try latest code); for example:

    Vector<String> splits = String::Split(";", ';');
    splits = String::Split(";;", ';');

In both cases 'splits' is empty. This pattern arises in an XML scene if a model has empty material slots (for instance, create a node with the ninja model in the editor (which has two material slots), pick a material for the *second* slot, save the scene and reload - the material has jumped to the first slot because of the Split behavior - the XML attribute looks like this:

`<attribute name="Material" value="Material;;Materials/NinjaSnowWar/Ninja.xml" />`

)

**Comment by weitjong** [comment]
Some of the time the extra empty strings in the result is a nuisance. Some of the time though the empty string is expected, especially when the original string is pre-formatted. Another example for the latter use case is the recently revised resource prefix paths engine parameter. I have to use
```
" ;../share/Urho3D/Resources"
```
(note that a space character have to be inserted before the first semicolon) in order to get the expected "empty" string as the first split result.

Probably we need to Split() functions or just one function but with another extra boolean parameter to switch on/off the deterministic behavior.

**Comment by barrettcolin** [comment]
From a quick test, both Javascript and Python split a string like ";" into two empty strings.

**Comment by Stinkfist0** [comment]
Typically string splitting functions tend to have `removeEmptyStrings` bool or enum parameter which can be used to control this behavior. That would be good addition for Urho's string class too.

**Comment by cadaver** [comment]
Practically the correct default behavior is that which is required for the material list serialization case. Then, like said, the possibility to omit the empty ones.

**Comment by barrettcolin** [comment]
Yes, that sounds good
