### ISSUE TITLE
Batching control or fake instancing

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#1035]
I am not sure if this is implemented already but if we have the same nodes with the same materials without any overrides except transform, would it be possible to send them in one batch saving draw calls? I am referring to a method similar to fake instancing from this article: http://carloscarrasco.com/faking-mesh-instancing-in-opengl-es-20.html 
It would be quite beneficial for older devices that does not support hardware instancing. In general are there any plans for exposing the batching control?

**Comment by cadaver** [comment]
A method that would dynamically repeat the vertex data of a mesh inside a vertex buffer is not planned to be implemented, because it's questionable (would need some kind of metric for this, which is not unambiguous) when this would be a hindrance, and when an actual benefit.

You are free to do this yourself manually if you want.

**Comment by sabotage3d** [comment]
thanks cadaver can you point me to the relevant parts of the engine that I need to change?

**Comment by cadaver** [comment]
Check View::AddBatchToQueue() which deals with conventional instancing where possible. Modifying the engine is unavoidable.

**Comment by sabotage3d** [comment]
Would it work for moving nodes?
