### ISSUE TITLE
Text3D is invisible in water

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1042]
![2](https://cloud.githubusercontent.com/assets/13021826/11168193/462f241e-8b9e-11e5-8f52-89a2315ef8f1.jpg)

**Comment by 1vanK** [comment]
same problem with materials with alpha (UrhoDecal.xml)

**Comment by cadaver** [comment]
This is an expected result of the draw order defined in the default renderpaths:

- Draw opaque geometry
- Draw water, using the opaque geometry render result as refraction texture
- Draw transparencys

The problem is that the water plane writes depth, so transparencys under the water no longer render. You have a couple of solutions, but they are not universal and may cause issues of their own:

- Disable depth test from the transparencys you want rendered over water
- Tweak renderpath to render water ("refract" pass) last
