### ISSUE TITLE
Better Networking (with SSL/TLS)

### ISSUE THREAD

**Issue by dresch86** [urho3d/Urho3D#1067]
I am considering pulling kNet and Civitweb in favor of either Boost:ASIO or Botan so we can get SSL/TLS support. I need the SSL/TLS for a REST API that only works over a secure line (most of the good ones do). Are there any allergies to getting Boost or Botan in Urho3D? Both of these libs build for mobile so cross platform should be ok.

**Comment by cadaver** [comment]
Boost is a very large dependency, and Botan seems to be C++11 only. These would be OK for something that is optional to compile.

**Comment by 1vanK** [comment]
I like that Urho 3D engine is very lightweight. Boost will double its weight for the realization of one feature.

**Comment by 1vanK** [comment]
It seems that the author of kNet participates in the development of the Urho3D as well. Maybe he could help :)

**Comment by cadaver** [comment]
In another project we are using OpenSSL and Curl for https assets with Urho. But in this case the https usage is built into the application and not into Urho.

https://github.com/realxtend/tundra-urho3d.

kNet is mainly UDP protocol oriented so I would not hold high hopes for it implementing SSL itself.

**Comment by cosmy1** [comment]
I would recommend RakNet as is game oriented and handles everything from secure connections to fast connections using UDP protocol.

**Comment by cadaver** [comment]
It indeed is a good candidate and has been discussed before. Someone would just need to take the time for integrating it, and testing for any possible cross-platform issues.

**Comment by 1vanK** [comment]
But RakNet is commercial lib http://www.jenkinssoftware.com/pricing.html

**Comment by xgundam05** [comment]
@1vanK  Actually, RakNet is now ["free and open to the community"](http://www.jenkinssoftware.com/) under the [BSD License](https://github.com/OculusVR/RakNet/blob/master/LICENSE) after it was purchased by Oculus.

**Comment by 1vanK** [comment]
By the way there are many open issues and pullrequests and the last commit 10 months ago.

**Comment by JSandusky** [comment]
When I did it a few weeks ago, replacing kNet with RakNet was pretty straight-forward (like 4 hours of work + however much research/learning) and pretty non-destructive to the public interface of Networking.

Never tested anything aside from Windows as to whether it builds cleanly/works/etc and the only significant RakNet functionality I added was host-discovery to send/receive a VariantMap of some "Beacon" information.

**Comment by primesoftware** [comment]
There is also mbedtls which is specifically designed to have a small footprint since it is targeted towards ARM based systems. The only problem is it is C programming and although I've got it to compile, I keep getting error 400 Bad Requests with their client example. I know its not the server because Boost::ASIO works fine. I could try messing around with mbedtls again. It claims it only requires 60 kB of disk space and 64 kB of RAM. The fact of the matter is we need TLS support. That should be a standard in this day and age especially if you are accessing REST API's. Parse, Facebook, and Twitter all use secure data channels. You really don't want someone messing around with high scores, data, etc.

**Comment by JSandusky** [comment]
Sigh, you keep running on about Boost::ASIO, even though there's ASIO without Boost. Though that's understandable because without Boost ASIO is basically worthless excessively strict mess.

ASIO is not even remotely good enough to replace kNet. I tried it out before RakNet, the only merit to ASIO was subnet broadcasting. Implementing subnet broadcast in kNet wasn't realistically viable.

> The fact of the matter is we need TLS support. That should be a standard in this day and age especially if you are accessing REST API's.

Fallacy much? That statement is a goldmine. I'll argue that if REST support is important than Urho3D needs a SOAP interface as well (afterall, SOAP > REST) and should be able to process WSDL and divine new types at runtime.

REST is distinctly a web-service thing, there's no good reason to drag REST into general networking as that's easily resolvable with an external library, no different than how I handle AngelScript debugging via CivetWeb for hosting a local WebSocket server ... it doesn't matter to networking ... it's something else and entirely non-critical.

**Comment by silverkorn** [comment]
I think that all we need, as the original post seemed to be meant to be, is to have a TLS implementation using a library under a permissive licence, so __mbedtls__ might be a good solution. 

So basic certificate and handshake stuffs, and generic + robust ciphers/algorithms to encrypt/decrypt would be good. I guess the rest doesn't matter whether if it's passed through kNet or CivetWeb but this might need a little help to integrate this interface, which would be why people suggests Boost::ASIO, it's all there ready to be run.

**Comment by primesoftware** [comment]
@silverkorn Yes, thank you for understanding what I was getting at. Also, I am aware ASIO can be standalone (without Boost), but I haven't been able to find a good example API. Like you said, it really doesn't matter what networking package is used, but the TLS implementation is needed. As much as I would love to code my own game server and implement my own encryption protocol I just don't have time to reinvent the wheel. Parse has a pretty good service, but they do require communication over TLS.

**Comment by silverkorn** [comment]
I started a thread last year (http://urho3d.prophpbb.com/post1209.html) but my lack of knowledge and time made it as I couldn't do much about it. :disappointed: 

@primesoftware I have the same issue, we need a safe way to pass usernames and passwords under an encrypted line, potentially for other sensitive data transfer and maybe also to avoid outer injections since only the client and the server would have the specific encryption key between them.

Apparently, the first step uses asymmetric key pair to send a symmetric key because asymmetric is slower to encrypt/decrypt than symmetric. This makes sense but I'm not totally 100% sure about this process... And yes, there's the optional but widely used certification concepts such as CA third-parties for proving a "trustable" source and other handshakes stuffs that happens before starting any of these, it might be excessive but I can understand people needing this to avoid fake installers/binaries distributions to take themselves as you and stealing you clients info...

Anyway, this might be really simple to integrate, it just depends on the security level you need... 
So certification process may be something to check later.

**Comment by JoshEngebretson** [comment]
I'm not sure this helps, though we have a WebSocket implementation which is based on https://github.com/zaphoyd/websocketpp (and standalone ASIO).  

You can checkout the Web subsystem here: https://github.com/AtomicGameEngine/AtomicGameEngine/tree/master/Source/Atomic/Web

This module was contributed, so I haven't had a lot of time to use it.  Maybe a starting point for a  SSL/TLS REST API?

**Comment by primesoftware** [comment]
I just took a loot at Civetweb's Github and noticed the following:

```
HTTP client capable of sending arbitrary HTTP/HTTPS requests.
```
I think they just added this (see 851a4cd). Going to investigate.....

**Comment by cadaver** [comment]
Civetweb has had SSL support for a long time, from back when it was first integrated into Urho. Apparently it will attempt to dynamically load the SSL library. However to my knowledge the functionality is not currently enabled in Urho builds.

**Comment by primesoftware** [comment]
@cadaver Thanks for the info! Yes, I've been looking around for an SSL example with Civetweb. I don't think going that route is going to help much for iOS folks. I think mbedTLS is a promising route. I've got it compiling and working ok. Now to make it work with Urho3D......WIP

**Comment by silverkorn** [comment]
@primesoftware That's good news. This would have a better cross-platform support and it would break the OpenSSL weird modified 3-BSD licensing limitations.

**Comment by shinyclaw** [comment]
What about ENet? http://enet.bespin.org/

**Comment by silverkorn** [comment]
ENet __omits__ certain higher level networking features such as authentication, lobbying, server discovery, __encryption__, or other similar tasks [...]

**Comment by primesoftware** [comment]
I have mbedTLS compiling and successfully communicating over a TLS channel. The TLS client example from mbed does not process any headers / data so my next task is to write a handler for that. Once I have that in place I will be back for help on integrating that as an optional plugin for Urho.

**Comment by silverkorn** [comment]
@primesoftware , That's really great news! Thanks for sharing time on this, that was one of the little missing thing that made me unsure to use Urho3D for a future game/software.

Little question, how do you proceed to generate keys and/or certificates? Do you need to generate them with OpenSSL or mbedTLS already has some functions/tools to generate them?

**Comment by primesoftware** [comment]
@silverkorn Sorry for not getting back to you sooner. Things have been busy. Does this answer your question (https://tls.mbed.org/kb/cryptography/rsa-key-pair-generator)? I don't think you need OpenSSL. mbedTLS is an encryption suite in itself as far as I know.

**Comment by silverkorn** [comment]
Nice! Lot of alternatives usually needs OpenSSL anyway to generate those.
I guess mbedTLS can be a full independant standalone.

**Comment by hdunderscore** [comment]
Here is something I whipped up a while ago when I needed something like this, it just made use of openssl directly and mimic'd Urho's HTTPRequest class: https://github.com/hdunderscore/Urho3D

I suspect supporting websockets makes the most sense for a game engine though.

**Comment by yiown** [comment]
I am a backend engineer for gaming platforms and RESTful along with HATEOAS self describing public APIs are a must in the industry.
I wanted to use Urho3D as a learning platform for web games, but the fact it does not support Websockets is a blocker.
In this respect, I believe the https://github.com/zaphoyd/websocketpp library would be a great addition to Urho3D.
In any case, whichever implementation you choose will be better to choose none and be discarded from the biggest gaming platform.

**Comment by cadaver** [comment]
The realXtend-Tundra project in which I have worked also uses websocketpp successfully. However it requires compiling boost libraries (at least system), which is something I'd rather avoid. @JoshEngebretson: Are you able to use it without pulling in boost?

If your sole / primary platform is web, pure js code may be a better solution, since Urho (or any C++ engine) compiles into a relatively heavyweight blob via emscripten.

**Comment by JoshEngebretson** [comment]
Here's  the PR for reference, pretty modest for this feature at 20k lines, mostly in ThirdParty with WebSocketPP and ASIO: https://github.com/AtomicGameEngine/AtomicGameEngine/pull/342

**Comment by cadaver** [comment]
Thanks!

**Comment by damu** [comment]
About Boost::ASIO: There's also a header only version that does not require building and linking Boost: https://github.com/chriskohlhoff/asio
Also I changed the paths to be relative which makes it easier to use: https://github.com/damu/asio (made a pull request but no reaction so far)

**Comment by weitjong** [comment]
SSL is now supported via URHO3D_SSL build option.
