### ISSUE TITLE
Emitting particles as 3d geometry

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#1085]
Hi I am currently looking into emitting 3d geometry with the particle system in Urho3d. I can see that by default there are only sprites available. I am trying to fake it but it is quite slow especially on mobile. Would it be possible to make a feature request for this?

**Comment by cadaver** [comment]
Do you mean emitting actual mesh instances?

I'm not saying strictly "no" to any feature requests regarding particle emitter improvements, but note that you also have the possibility of creating your own particle emitter component that works just the way you want - there's no specific reason it has to happen inside the engine.

**Comment by sabotage3d** [comment]
Yeah I mean actual mesh instances like cubes. If I am doing it outside the engine how should I approach it? I need some way of quickly access the particle transform so that I can instance the geometry. If I use the node system for that It would be quite slow with hundreds of particles. I am after something like lego explosion.

**Comment by neat3d** [comment]
I think this is a very important feature for game dev, not only emitting geometry, but also batch all the particle elements together for high rendering performance.
Maybe curves can be attached to some particle properties(i,e. scale, color, force), so designer can easily modify the curve to control a more accurate particle animation.

**Comment by cadaver** [comment]
If nodes are too slow, then you would have to bake a vertex buffer on each update, that contains all the geometry.

For now I'd recommend to just copy the ParticleEmitter code into your own class and modify it to do what you want.

**Comment by sabotage3d** [comment]
Thanks cadaver. For the batching I will need to modify the engine to support dynamic batching. Particle wise is the only class I need from the Particle Emitter source?

**Comment by cadaver** [comment]
Yes, ParticleEmitter is the only thing you should need.

You don't necessarily have to modify the engine for dynamic batching, just make your own particle emitter class update the geometry appropriately. Look e.g. to the DynamicGeometry sample for inspiration.

**Comment by cadaver** [comment]
Thinking of this a bit more, custom application code for any Lego / MineCraft type scenarios will always have potential to be better performing than engine code. Because engine code would need to be generic, ie. take into account any possible vertex format. 

But when doing the geometry update in your application, you can decide for example that your particle geometries have only positions and normals, and can write tight hardcoded code.

In this sense, Urho is properly structured so that you are always able to create your own custom Drawables for your own specialized scenarios, and I'm tempted to close this issue.
