### ISSUE TITLE
build LuaJIT by default

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#1091]
The Samples are now built by default, which caused Lua to be built by default.  It would be good to build LuaJIT by default as well.  The idea was raised in http://urho3d.prophpbb.com/topic1598.html and performance and reliability wise, nobody said it was a bad idea.  It reduces the number of options that most users need to worry about, which is helpful to avoid mismatches between Urho3D and downstream code compilation.  It promotes field testing of LuaJIT, which is more valuable on platforms such as Windows that don't get continuous integration testing.  The only corner cases mentioned were that iOS cannot have LuaJIT in the app store, and LuaJIT currently doesn't work with HTML5, but most Urho3D users aren't on those platforms.  It would be fairly easy to write CMake code saying if(IOS OR EMACSCRIPTEN), the latter of which seems to imply HTML5.

**Comment by weitjong** [comment]
Our CMake build scripts already growth more complex by day. I would like to keep those things that can be made simple, simple. User can always throws the switch themselves easily one way or the other, and they only have to do it once per build tree. To me, having certain options preset so that they can be tested more by users argument is not valid one. There is no canonical way of configuring Urho3D project.
