### ISSUE TITLE
ImGui as secondary UI ?

### ISSUE THREAD

**Issue by svifylabs** [urho3d/Urho3D#1105]
hey,
I am working on implementing ImGui into Urho3d and i noticed some forum posts about it, so i'm here...

https://github.com/svifylabs/Urho3D/tree/f_imgui

What do you think of it ? Should i make a pull request ? 
There are some TODO's open but it is working. 

First i thought about creating IMUI as a wrapper class but i decided against it. (wrong ?)
So you have to include <imgui/imgui.h> and use ImGui namespace for the ui elements. It does not matter where you call the ImGui functions as long as it between BeginFrame and EndFrame event.

Only tested Windows, so if someone can test it on other platforms ...

**Comment by cadaver** [comment]
Generally, we provide "fully integrated" features, meaning they are wrapped and exposed to all the scripting languages. This would be a departure from that, though I understand that wrapping a whole UI library is a huge work.

I would recommend providing this as a stand-alone module people can copy to their projects, instead of a pull request to the engine itself. We can include it in the documentation as an external link similar to the Librocket integration, and others.

http://urho3d.github.io/documentation/HEAD/_external_links.html

**Comment by MonkeyFirst** [comment]
at last your brunch have tags feature, maybe you do other PR for Tags supporting?

**Comment by green-zone** [comment]
svifylabs
Can you create separate Topic for this in Urho3D forum?

**Comment by green-zone** [comment]
imgui made a programmer for programmers.
It great for Tools and Debuging. It portable and fast.
IMUI provide extention with small changes of Urho3D source code.

It will be as secondary UI for console, debug messages, editor etc. ("system" ui)
And UI for end-user which can be heavy for performance. ("user" ui)

**Comment by svifylabs** [comment]
so created a Topic in the forum : http://urho3d.prophpbb.com/post9831.html#p9831

**Comment by vivienneanthony** [comment]
Hi,
I'm getting this compile error. http://i.imgur.com/gveww9I.png

Do anyone know what's up? I am thinking maybe it worked on 1.4 prior.

Vivienne
