### ISSUE TITLE
Emscripten builds deploy unnecessary/unused files?

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#1110]
This is a minor note, not a bug or an issue, but just thought to mention: looking at the build output directory of Emscripten builds, I see there are two files `CoreData.pak` and `Data.pak` that exist in the output folder, but if I understand correctly, those are not actually used when running the .html, but the necessary data exists in the Emscripten VFS `.data` files already?

![files](https://cloud.githubusercontent.com/assets/225351/11956023/a064e3e0-a8bf-11e5-92c2-d865a9615ef7.jpg)

**Comment by weitjong** [comment]
You are correct. They are not necessary for deployment. However, these two files are generated on the fly while building the HTML targets. They are left as build artifacts in the output directory because the our build system is smart enough to use the timestamp of the files to decide whether they need to be regenerated in the subsequent builds. No assets changes no regeneration. Having said that, it is a mistake indeed if/when these two files are also installed/included in our software package.
