### ISSUE TITLE
InstanceXML/ScriptObject nodes start at world origin

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1128]
I have a projectile node prefab with a rigid body. Using InstanceXML, they spawn at the world origin and it seems to take them a frame (physics?) before they move to the correct position.

Inside the function that spawns the projectile, after instancing the node its position is correct:
```
void fire_projectile(...)
{
	// Instance the prefab
	XMLFile@ xml = cache.GetResource("XMLFile", "Objects/" + prefab + ".xml");
	// ...
	auto@ node = scene.InstantiateXML(xml, position, rotation);
	Print("node: " + node.worldPosition.ToString());	// correct position
	// ...
}
```

Though when I inspect the node position from a "Projectile" ScriptObject, I noticed that the node is at (0,0,0), while the body is at the correct position:
```
class Projectile : ScriptObject
{
	void DelayedStart()
	{
		Print("start: " + node.worldPosition.ToString());	// 0,0,0
		Print("start body: " + body.position.ToString());	// correct position
	}
}
```

Projectiles can be seen at the world origin. In the case of rocket projectiles, if they spawn straight into collision they will explode at the world origin.
Example video: https://www.youtube.com/watch?v=9om6S8XMYBk

Note that the fire_projectile() print appears before the DelayedStart() print.

vsync seems to make this problem disappear.

**Comment by cadaver** [comment]
Can you debug inside RigidBody::OnMarkedDirty() when Scene::InstantiateXML() sets the prefab position at the end of its execution?

OnMarkedDirty should call SetPosition & SetRotation, which set the Bullet body transform.

If you are spawning the projectile inside a physics simulation tick (ie. in FixedUpdate) SetPosition & SetRotation will not set Bullet's interpolation transform, which may lead to what you observe. This was a recent change made due to parented rigidbodies behaving badly otherwise.

Can you verify this is the case?

I will think of what can be done about this. For initialization, forcing the interpolation transform should be allowed.

**Comment by cadaver** [comment]
Sorry, remembered the condition wrong. When *inside* FixedUpdate, the interpolation transform will be set. E.g. shooting snowballs in NinjaSnowWar is done in the Ninja object's FixedUpdate and therefore they should have the correct interpolation transform right from the start. If it was done in Update instead, it wouldn't be set.

**Comment by cadaver** [comment]
See if the commit fixes the issue.

**Comment by Enhex** [comment]
It fixed it.
