### ISSUE TITLE
The minidump path is hard coded

### ISSUE THREAD

**Issue by darwikey** [urho3d/Urho3D#1142]
Hello,
When a minidump is generated, the file is always saved at AppData/Roaming/Urho3D/crashdumps (for windows).
The path is hard coded in MiniDump.cpp. And it would be nice if we can define a new path (with for exampe engineParameters_ ?)

**Comment by cadaver** [comment]
Originally reason for hardcoding was to prepare for the case where the program state is so messed up that it cannot rely on reading any configuration variables. It shouldn't be a problem to provide a function for setting the minidump location. It'll probably be static since the Urho context and engine subsystem cannot be known / accessed by the static minidump function.

**Comment by OldSnake22** [comment]
+1 for this
