### ISSUE TITLE
adding a method to set Camera's projection matrix

### ISSUE THREAD

**Issue by AndyTaiDaqri** [urho3d/Urho3D#1182]
This is a patch to add a convenience function to directly set the projection matrix of a Camera--as sometimes the application code may directly compute this matrix.

[patch.txt](https://github.com/urho3d/Urho3D/files/114289/patch.txt)

**Comment by cadaver** [comment]
Thanks, I believe this is fine to include as long as we add notes that the custom matrix will be overwritten once the camera's standard projection parameters are changed.

**Comment by cadaver** [comment]
After some testing I've come to the conclusion that there are too many places which will easily break the custom projection matrix. Using autoaspect ratio on the camera, for example. There are also some places which need an API agnostic projection matrix (such as the OcclusionBuffer software renderer) while other places expect API convention projection (actual GPU parameters). As such, it would need to be worked around perhaps so that the custom matrix you specify is always the API-agnostic one, and the rendering code would convert it when necessary.
