### ISSUE TITLE
Urho3DPlayer builded when -DURHO3D_LUA=OFF -DURHO3D_ANGELSCRIPT=OFF -DURHO3D_TOOLS=OFF

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1224]
full command
```
Urho3D/cmake_vs2015.bat Build -DURHO3D_OPENGL=ON -DURHO3D_SAMPLES=OFF -DURHO3D_LUA=OFF -DURHO3D_STATIC_RUNTIME=ON -DURHO3D_ANGELSCRIPT=OFF -DURHO3D_TOOLS=OFF
```

**Comment by weitjong** [comment]
Right or wrong, this is intentional. Urho3DPlayer is rather special. Although project structurally, its source code is grouped under the ```tool``` subdir in the source tree, but the generated binary is meant for target platform as oppose to host platform, i.e. the binary is not end up in ```tool``` subdir in the build tree. Urho3DPlayer binary is resided in the ```bin``` subdir as other target binaries.

Put it in another words, you get Urho3DPlayer for free when you build Urho3D library. Probably not a good idea to add another build option just for disabling this, besides our Editor actually relies on Urho3DPlayer.

**Comment by cadaver** [comment]
When both script subsystems are off, you do get a rather feature-limited Urho3DPlayer, and you shouldn't be able to run the editor (without AngelScript), so possibly a special-case check could be inserted for that.

**Comment by weitjong** [comment]
Ah yes. Didn't notice both scripting subsystems were also off. If all these
are off then it makes no sense to include Urho3DPlayer in the build.

**Comment by 1vanK** [comment]
Thank you
