### ISSUE TITLE
Engine version 1.5-474-g385a153-dirty build failed

### ISSUE THREAD

**Issue by ffpwserver** [urho3d/Urho3D#1249]
Environment
Mac OS X EI Capitan (version10.11.3)
building the Samples is OK, but when I build my own project as before, some link error occurs
  "_CVDisplayLinkCreateWithCGDisplay", referenced from:
      _Cocoa_InitModes in libUrho3D.a(SDL_cocoamodes.m.o)
      _Cocoa_GetDisplayModes in libUrho3D.a(SDL_cocoamodes.m.o)
  "_CVDisplayLinkGetNominalOutputVideoRefreshPeriod", referenced from:
      _GetDisplayMode in libUrho3D.a(SDL_cocoamodes.m.o)
  "_CVDisplayLinkRelease", referenced from:
      _Cocoa_InitModes in libUrho3D.a(SDL_cocoamodes.m.o)
      _Cocoa_GetDisplayModes in libUrho3D.a(SDL_cocoamodes.m.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

engine works OK yesterday for me (about 12 hours before)
but when I pull the newest verion, it fails...

**Comment by weitjong** [comment]
Sorry to hear for that. Have you tried to regenerate the build tree for your project? Although I have mainly tested OSX platform with Urho3D shared lib type on my El Capitan host system but it seems there is no issue on Travis side too, the scaffolding test with static lib was passed in the last CI. Are you using generic Makefile or Xcode? Give me as much of information you can and I will try to reproduce when I have time later.

**Comment by ffpwserver** [comment]
I used the generic Makefile, my build tree was regenerated.
And I can see that the last CI build result was failed on Mac and iPhone on Urho3D's mainpage.

**Comment by weitjong** [comment]
No. If you drill in you can see it only error-ed out on iOS 64-bit due to
build time exceeding our free account limit. The rest of the build
configurations went fine. Travis differentiates between failure and
technical error status. Anyway,  if it is generic Makefile then you may
have genuinely hit a bug. I will try to reproduce it soon.

BTW, we exclude CI job for static lib type using Makefile a few months ago
to speed up our overall build time. Our free account only gives us 5 max
concurrent jobs. As our build matrix keeps growing and growing and the code
base gets more sophisticated, it will be harder to do all the CI build that
we have to do with the limited resources (time and computing power)
available to our free account.

**Comment by ffpwserver** [comment]
I recompile the engine using build-option "-DURHO3D_LIB_TYPE=SHARED",
then the problem solved.

**Comment by weitjong** [comment]
I think it's a static library dependency problem.

**Comment by weitjong** [comment]
I am afraid I am not able to reproduce your issue. The linker error that you got clearly indicates that for some reason your target is not linked against CoreVideo framework. However, I have just verified our CMake build scripts that our build system will automatically configure the target to be linked against CoreVideo framework among others. This is true for both Xcode and Makefile-based build trees. So, I suspect now that there is something wrong with your build tree or it was not generated using our CMake build scripts.

**Comment by ffpwserver** [comment]
Sorry and thanks for the last suggestion------copy the latest Urho3D CMake modules and toolchain files to my own project.
That's exactly where the problem is.
I copy and recompile them and the problem solved.
To prevent further problems, I use soft symlinks instead of copying them.
Thanks so much!!!
