### ISSUE TITLE
Mouse scaling issue on retina display

### ISSUE THREAD

**Issue by NightBlaze** [urho3d/Urho3D#1252]
There is an issue on Macbook with Retina. Actually cursor position is calculated wrong. Video http://www.youtube.com/watch?v=UiGhXOoWKfM

On commit 28fb9e7b88045df218098f3259473d660d9ce1a5 and before all is good (except retina support :) ). Video http://www.youtube.com/watch?v=_vgCS6It464

**Comment by weitjong** [comment]
Thanks for reporting this. It is good to know that now we have retina support, thanks to SDL 2.0.4. The issue should be caused lack of mouse scaling when on retina display.

**Comment by weitjong** [comment]
I don't actually have a retina display to test any of this. We have enabled the SDL_WINDOW_ALLOW_HIGHDPI on all Apple platforms now in our engine code. @NightBlaze, in your opinion, is it the mouse move too fast and need to be scaled down? Or the mouse movement feels just right and it should be the UI response to be scaled up?

**Comment by NightBlaze** [comment]
@weitjong The mouse movement feels just right and it should be the UI response to be scaled up.

**Comment by cadaver** [comment]
I don't have a retina display Mac either. So is the issue that SDL is giving us mouse coordinates that don't match the window's pixel size?

**Comment by weitjong** [comment]
I haven't got time to look into this yet, but the release notes in WhatsNew.txt may give us some clues.

```
Mac OS X:
* Added support for retina displays:
  Create your window with the SDL_WINDOW_ALLOW_HIGHDPI flag, and then use SDL_GL_GetDrawableSize() to find the actual drawable size. You are responsible for scaling mouse and drawing coordinates appropriately.
```

Actually this has been made available since 2.0.1 but our engine has never utilize this flag before and I took the chance :smile:  while I was merging the 2.0.4. After setting the flag, I remember I have to replace all the SDL_GetWindowSize() call with SDL_DrawableSize(). I suppose this is not enough. Somewhere in our UI or Input subsystems we still need to let the code how to differentiate between screen coordinates and pixels.

**Comment by weitjong** [comment]
I think we need to fix the UI subsystem to properly support the high DPI mode before enabling this by default. IMHO, just scaling the mouse movement does not really help much if the overall UI is too small to use.

**Comment by cadaver** [comment]
Should be fixed now, so closing. Can be reopened if necessary.
