### ISSUE TITLE
Odbc can not connect mysql

### ISSUE THREAD

**Issue by lvshiling** [urho3d/Urho3D#1263]
After configure MySQL driver on window7,  I try to connect MySQL,  Get Error can not connect

**Comment by lvshiling** [comment]
I test it by change connect string in 41_DatabaseDemo.lua

**Comment by weitjong** [comment]
Just to be sure.  Have you tested the connection with your db server using other clients? This will help you to rule out other possible errors before suspecting something is wrong with our code, which is actually possible as not many users walk this path. Usually we have server on Linux side.

**Comment by lvshiling** [comment]
Yes , other client is ok

**Comment by weitjong** [comment]
I have only tested it with MariaDb (MySQL re-branded) on Linux and it was ok back then. Not in front of my PC so I cannot give you how my connection string looks like now.

**Comment by weitjong** [comment]
Actually I was just being stupid. I have documented the connection string that I used during testing in our online documentation http://urho3d.github.io/documentation/HEAD/_database.html#ODBC_ConnString here, exactly because I am afraid one day I will lose it. However, if you think that you already get your connection string right and yet not able to connect then I am afraid you have to debug the source code to see where it exactly failed. Sorry for not being more helpful. Using VS as an editor is already giving me a headache, let alone as debugger tool.
