### ISSUE TITLE
Play subset frames of an animation

### ISSUE THREAD

**Issue by neat3d** [urho3d/Urho3D#1267]
Is there anyway to play a few frames of an animation but not the whole frames? 
Or I need to export a lot of animation files?

For now, I only export all animations in one .ani file with a long frame counts, I'd like to play frame 0 -> 20  as a walking animation, frame 21-50 as skill1 animation. how can I do this?

And I found that an animationState keeps a copy of animation tracks, is it necessary to keep them for every animationState? Why not just get them from the resourceCache?

**Comment by cadaver** [comment]
The engine doesn't support this, as animations are only played back using time positions. Adjacent animations will interpolate wrongly into each other since the engine has no knowledge where one animation ends and the next begins.

I strongly recommend exporting the animations as separate. If you have ideas on how e.g. AssetImporter could be improved to do the animation splitting at the .ani file export phase, it's welcome.

AnimationState doesn't hold a value copy of animation track data. Rather it holds a pointer to each track in the AnimationStateTrack structure. This is to speed up access when animating. This is somewhat unsafe though, as it's a raw pointer and it would be possible to cause crashes by removing animation tracks during playback, so the AnimationTrack should rather be refcounted.

**Comment by neat3d** [comment]
@cadaver  
I had misunderstood on AnimationStateTrack, Thank you for explaining! 
I think AssetImporter could take a conifg file as how animations can be imported.

Something like this:

c:/> assetimporter model aniTest.fbx -config "split.json"

file split.json:
{
"animations" : { "aniName1" : [0,20], "aniName2" : [30,50] }
}

Or:  without a json?

C:/> assetimporter model inFile.fbx walk.ani -split 0 20  
C:/> assetimporter model inFile.fbx attack.ani -split 30 50

**Comment by neat3d** [comment]
Hi guys, I work it out.  
Anyone want this feature just take look here: #1272

**Comment by cadaver** [comment]
Was merged. I believe the 'split' option is already very usable.
