### ISSUE TITLE
Android touch interface broken - fixed

### ISSUE THREAD

**Issue by gwald** [urho3d/Urho3D#1303]
The master build has an android touch screen bug, all touches are interpreted as top left ie: 37 UIDrag 
The 1.5 build works fine.

Also, how do you get back to the main menu, it used to be tapping on the fish (bottom left) would do this but master and 1.5 doesn't, was this removed or changed?

**Comment by weitjong** [comment]
I will just answer the second part.

> Also, how do you get back to the main menu, it used to be tapping on the fish (bottom left) would do this but master and 1.5 doesn't, was this removed or changed?

You cannot get back to the Android sample browser. This has been the case since day one. Perhaps you have confused it with other game engine. Initially, before the sample browser is created, we could only deploy the Android sample one at a time. With the browser app, it packages all the sample *.so in one apk and allows user to choose which *.so to load and launch. However, it does not know how to unload the loaded *.so from memory yet.

**Comment by hdunderscore** [comment]
Ah this is my fault, I deleted the wrong code here:
https://github.com/urho3d/Urho3D/commit/54565005e2719f1e2d94f43716b8a3f451d72761#diff-eeea0f0ea09c3078b218adad26e10f10L1625

**Comment by hdunderscore** [comment]
I believe it should work again, I also tested the emscripten version and confirmed that works with touch again.

**Comment by gwald** [comment]
weitjong, ha yes possibly, thanks for the info.
Thank Hdunderscore, yes, your fixed worked for me also cheers.

**Comment by gwald** [comment]
@hdunderscore  not sure it's related but would you mind checking the gyro works on the demos?
None of the demos work for me with the gyro option on.
