### ISSUE TITLE
Parallel Building

### ISSUE THREAD

**Issue by cosmy1** [urho3d/Urho3D#1304]
Currently Urho3D does not take advantage of parallel building which modern compilers support.
Using single core compilation have no advantages over multicore compilation therefore we should enable it by default when possible.
Microsoft introduced parallel building support (**/MP**) in Visual C++ 2010 and above. _Make sure minimal rebuild is disabled_.
On other build tools (make, ninja) there is **-j** parameter (I think ninja have it enabled by default).

For more informations:
https://blog.kitware.com/cmake-building-with-all-your-cores/

**Comment by JoshEngebretson** [comment]
Just a note on this, if you build with parallel projects (msbuild option /m) with /MP you can decrease compile times due to core starvation.  This is documented in the /m or /MP options on MSDN.  Basically, it needs to be tuned for the project.  I don't see why VS can't be smarter about how these options work together, though from some experience lots of projects in a solution, parallel project builds usually win, few projects with lots of source files, /MP usually better choice.

**Comment by weitjong** [comment]
This is not entirely true. To be more precise, our build system does not prevent parallel building as it is now. The reason is because we have setup all our build dependencies correctly. As far as I concern, once the build tree is generated, it is user own wishes to use how many worker processes for the build. That is, we do not bake that information into the build tree (in compiler flags or anywhere else). Personally I am mostly using CLI and I have shared most of my build rake tasks. See ```rake make``` task, it shows how it utilizes all the CPU cores automatically for the build.

As for the /MP compiler flag, I have no idea how it differs from msbuild /maxcpucount option.

My view. There is nothing we need to change in our build system to support parallel building, even our CI jobs use it now all the time. I would not stop anyone though to experiment with /MP flag on VS/MSVC. It just means we have yet another exception for MSVC but we have exceptions for MSVC all over the places anyway. :smile:

**Comment by cosmy1** [comment]
Checked rakefile and yes you are entirely right! Being a Visual Studio developer (!CLI :smile:) I like to generate my projects and I do it with CMake when working on Urho3D but I always have to add /MP to CMAKE_CXX_FLAGS to enable multicore compilation.

The idea came up because I have my own premake5 scripts in my private fork of Urho3D to generate project files for Win and Xbox One and thought it would be cool to have the same effect on Urho3D (did not know about rakefile).

And yes MSVC is very "special" and "unique" I would say love it or hate it :smiley: 

You can close it then :+1:
