### ISSUE TITLE
How can I fix the error: Urho3DPlayer: command not found

### ISSUE THREAD

**Issue by genehsun** [urho3d/Urho3D#1306]
According to [http://urho3d.github.io/documentation/HEAD/_editor_instructions.html], I run the command Urho3DPlayer Scripts/Editor.as under the Urho3D-1.5/bin directory, but it report an error: Urho3DPlayer: command not found.

**Comment by weitjong** [comment]
I think none of us can help you to answer that without any context. You need to tell us the steps to reproduce it or how did you end up in such situation.

**Comment by genehsun** [comment]
@weitjong thank you, i have updated the comment

**Comment by weitjong** [comment]
Still, that is not a full picture. The error message indicates the "Urho3DPlayer.exe" binary file is missing in the "bin" directory. So, did you download the binary package in the first place? Or did you download a source package and build all binaries first using the downloaded source?

In any case I don't think this is a genuine issue for Urho3D. So, I am closing this now. If you still have problem with Urho, you can raise your questions in our support forum instead of here.

**Comment by genehsun** [comment]
@weitjong ok, sorry for my trouble
