### ISSUE TITLE
(feature request) Tags and variables inheritance in custom UIDefaultStyle

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1344]
For example:

```
    <element type="Window" style="BorderImage">
        <attribute name="Tags">
            <string value="Managed" />
        </attribute>
        <attribute name="Variables">
            <variant type="Vector2" value="0 0" name="StartPosition" />
        </attribute>
    </element>

    <element type="MainMenu" style="Window">
        <attribute name="Tags">
            <string value="MainMenu" />
        </attribute>
        <attribute name="Variables">
            <variant type="Vector2" value="0 -100" name="TargetPosition" />
        </attribute>
    </element>
```

I need both tags and variables for MainMenu element

**Comment by cadaver** [comment]
For this to work in a general case where you can keep switching the style, it would need to track which variables & tags come from the style and which from the element itself. A messy implementation could just keep adding the tags & variables after deserializing the style, but it has potential for problems. @weitjong Can you comment, since you added most of the finer UI XML / style manipulation features?

**Comment by weitjong** [comment]
I agree with Lasse. Though this may be possible, it would require special handling for these two attributes. The problem is, that special handling is not localized in one method. The "messy implementation" won't work nicely because at the time of serializing the reverse logic is required to filter out attributes coming from style file, i.e. we don't save the same attribute value again in layout file when it is already defined in the style file. In this case it is not the attribute itself that we need to compare but it is its constituents (member of vector or map).

IMHO, it is doable but require some careful execution (no quick and dirty implementation). And we also need to consider how to define these attributes when a subclass really does not want inherit the values from its super class or default style.
