### ISSUE TITLE
Normal offset shadows

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#1347]
Normal offset bias for shadows http://urho3d.prophpbb.com/topic1991.html is another way of combating self-shadow artifacts which needs researching. If the implementation can be kept in the vertex shader (instead of manipulation of shadow UV coords in pixel shader) the performance could also be acceptable on mobile devices.

**Comment by yushli** [comment]
That would be a nice feature to have as currently self-shadow artifacts are quite obvious on mobile devices.

**Comment by rikorin** [comment]
I'm glad this issue got your attention. Current panning is awful even with very low constant bias and tweaking the slope on lower bias doesn't really help to remove self-shadowing completely, so it would be a nice feature to have.
![9847c5b7d6bb5adaa07f816ed7620a0e](https://cloud.githubusercontent.com/assets/17810346/15034185/7979784a-128c-11e6-8c3d-b8338208badb.png)
6 cm, it gets through my paper-thin Japanese walls causing lighting artifacts :3

Also current "variance shadow" implementation is not acceptable. Variance shadows usually look something like this: 
![6a0c64684a1978f0926dff1735d39552](https://cloud.githubusercontent.com/assets/17810346/15034117/a97525d6-128b-11e6-8f16-0a30891edfd4.png)
not like this:
![b1e76874cdbda63e7aa77af0a5169236](https://cloud.githubusercontent.com/assets/17810346/15034126/b6442442-128b-11e6-8a78-3b6e66643a92.png)
Sadly, I suck at math, so I doubt I can write (on appropriate level) such a non-trivial shader myself. Especially because I'm not familiar with Urho3D shader system yet.

**Comment by cadaver** [comment]
It can however be expected that normal offset is not a magic solution, but another option that needs tweaking and may come with its own artifacts in some cases.

VSM is a contributed feature; contributions to improve it are welcome.

**Comment by rikorin** [comment]
Well, that's a given. 
I've just installed Unity to see how shadows work there and it seems that they use normal offset too. It works really nice in practice (Unity itself is awful tho).
What I've also noticed is that PBR in Urho performs really slow compared to other implementations. Is it only for me?

**Comment by cadaver** [comment]
Experimented a bit with VSM and scaled the softness amount to shadow map resolution. Also reduced default smoothness. For the light bleeding you will need to play with the parameters in Renderer. You'll notice unnaturally thin shadows in examples like CharacterDemo. When using VSM, all large surfaces should be shadowcasting themselves to avoid this.
