### ISSUE TITLE
Material::SetRenderOrder() doesn't work

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1358]
Replication:
In sample 04_StaticScene, trying to create a material for the plane with higher render order so it will render later on top of everything doesn't change anything:

```C++
	Node* planeNode = scene_->CreateChild("Plane");
	planeNode->SetScale(Vector3(100.0f, 1.0f, 100.0f));
	StaticModel* planeObject = planeNode->CreateComponent<StaticModel>();
	planeObject->SetModel(cache->GetResource<Model>("Models/Plane.mdl"));
	auto mat = cache->GetResource<Material>("Materials/StoneTiled.xml")->Clone();
	mat->SetRenderOrder(200);   // Higher render order
	auto tec = mat->GetTechnique(0)->Clone();
	tec->GetPass(0)->SetDepthTestMode(CMP_ALWAYS);   // Always pass depth test
	mat->SetTechnique(0, tec);
	planeObject->SetMaterial(mat);
```

**Comment by cadaver** [comment]
Material's render order controls order within each pass.

However, when forward rendering with per-pixel lights is used, you need to remember that there are several passes in play: objects may get their ambient rendered with the "base" pass, the first light is rendered afterward with the "litbase" optimization pass, and further lights will be rendered with repeated "light" pass. Using render order needs cooperation from all materials, and in the example above when you're changing the depth test, you must make sure you change it from all necessary passes.

Since "litbase" is most likely going to be a problem in forward rendering you can disable it globally from the renderpath by setting the following in the forward renderpath:

    <command type="forwardlights" pass="light" uselitbase="false" />

If you use deferred rendering, then render order within the G-buffer pass should work as expected "out of the box" without renderpath changes.

Should probably add the text I just wrote to the documentation.
