### ISSUE TITLE
Adding StringName class

### ISSUE THREAD

**Issue by svifylabs** [urho3d/Urho3D#1359]
what do you think of a StringName class for Uhro3d ?

Description from [UnrealEngine](https://docs.unrealengine.com/latest/INT/Programming/UnrealArchitecture/StringHandling/ )
> FName
> ... FNames provide a very lightweight system for using strings, where a given string is stored only once in a data table, even if it is reused. FNames are case-insensitive. They are immutable, and cannot be manipulated. The storage system and static nature of FNames means that it is fast to look up and access FNames with keys. Another feature of the FName subsystem is the use of a hash table to provide fast string to FName conversions. 

Open Source Ref:
https://github.com/godotengine/godot/blob/master/core/string_db.h
https://github.com/HeliumProject/Foundation/blob/master/Name.h
https://github.com/GarageGames/Torque3D/blob/master/Engine/source/core/stringTable.h

i already have an implementation of that. How must i change the default Urho3d license text if i modified the Name class from HeliumProject or the stringTable class from Torque3D for Urho3d so that i can upload it?

**Comment by cadaver** [comment]
Urho tries to keep string usage away from the hot paths so I'm not really sure if this is needed. Other opinions are welcome. There is the StringHash mechanism used throughout but I wouldn't want that to be tied to a global table access. For example when you need a table in your EventProfiler PR it's fine that it uses its own string hashmap. It's also better for performance when a map for a specific purpose stays relatively small, instead of a big global table.

It is not a problem to add a permissive engine's license to Urho's master license file and adapt code from another engine. However in this case we're talking of a quite small isolated problem so I'd prefer a "Urho native" clean room reimplementation made from ground up.

**Comment by cadaver** [comment]
Closing since no other discussion for now, and the EventProfiler was merged without.
