### ISSUE TITLE
EventProfiler

### ISSUE THREAD

**Issue by svifylabs** [urho3d/Urho3D#1360]
hey 
What do you think of an EventProfiler ? It just inherits from the profiler class (for now) to create a new class. 
The problem was that i had to somehow save the eventnames (if StringNames are used for the event IDs, that would be easier to implement), so i used a static HashMap ...

modified:
> // Object.h
> /// Register event names.
> struct EventNamesRegistrar
> {
>     static StringHash RegisterEventName(const char* eventName);
>     static HashMap<StringHash, String> eventNames_;
> };
> 
> /// Describe an event's hash ID and begin a namespace in which to define its parameters.
> #define URHO3D_EVENT(eventID, eventName) static const Urho3D::StringHash eventID(EventNamesRegistrar::RegisterEventName(#eventName)); namespace eventName

and added 
> // Object.cpp
> void Object::SendEvent(StringHash eventType, VariantMap& eventData)
> {
> ...
> #ifdef URHO3D_PROFILING
>     Urho3D::AutoEventProfileBlock autoEventprofileblock(GetSubsystem<Urho3D::EventProfiler>(), EventNamesRegistrar::eventNames_[eventType].CString());
> #endif
> ...

thats how it looks
http://imgur.com/NbPJfrY

**Comment by cadaver** [comment]
This is a nice idea. It should be default off though, since the existing profiling blocks have been chosen with the idea that they don't repeat hundreds of times per frame, however events could easily happen by the hundreds per frame and rob performance.

It doesn't necessarily have to be a compile-time check, you could add static functions to Object class to enable/disable event profiling, in which case it'd be just a relatively fast bool check when sending an event.

Check my thoughts on the string names issue; since I'm not sure that's essential I'm fine with this using a separate lookup map.
