### ISSUE TITLE
add anchorPoint to UIElement (feature request)

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1366]
Currently Sprite has hotspot property to set the center of the sprite. But UIElement doesn't have this property. further hotspot is using actual size instead of percentage. Suggestion: add anchorPoint to UIElement, using percentage to set the center of this element. E.g., anchorPoint(0.5,0.5) will set the anchor point at the center of the element. That will make positioning UI more conveniently.

**Comment by cadaver** [comment]
If we add this, I believe we should remove the UI element alignments (left/right/center, top/bottom/center) because those calculate a fixed anchor point internally (eg. left if aligned left, center if aligned center). This could break existing UI's. Layouting code also assumes UI elements being anchored from the top-left.

If you're interested I recommend working on it on a PR, to see if you can get it compatible with the existing UI, and perhaps most importantly to not make it more confusing.

**Comment by yushli** [comment]
I'd like to do but that sounds a lot of code to look at and a lot of corner cases to watch out. I may settle down just adding that to the top level text ui elements.
