### ISSUE TITLE
iOS screen resolution error

### ISSUE THREAD

**Issue by SuperWangKai** [urho3d/Urho3D#1371]
My device is iPhone 6 with iOS 9.3.

The game resolution is error as 480x320, thus the drawing part of the screen is smaller and we lost the sharpness of the retina screen.

And the correct resolution should be 1334 x 750. test by
```objc
CGRect screenBounds = [[UIScreen mainScreen] bounds];
CGFloat screenScale = [[UIScreen mainScreen] scale];
CGSize screenSize = CGSizeMake(screenBounds.size.width * screenScale, screenBounds.size.height * screenScale);
```
**Is seems that this is a bug of SDL2 and the test programs from SDL2 are also incorrect.** 
and 
```cpp
SDL_GetDesktopDisplayMode
```
cannot get the correct resolution.

**Comment by SuperWangKai** [comment]
For searching and trying many times, I found out there are two reasons:

1. We need to modify the launch image assets or code to support new device and iOS version,
https://forums.developer.apple.com/thread/5572

2. SDL2 may know nothing about retina, I guess?

**Comment by weitjong** [comment]
SDL2 actually supports retina display. However we have disabled it by default due to our Input and UI subsystems have not designed to work with high DPI display yet. You may try to experiment with it by enabling the high DPI mode using the engine parameter, which on Apple platform should make the SDL window to take advantage of the retina display. Having said that, you are really on your own as the high DPI mode is not being well tested as much as we could. None of the core devs have the necessary hardware to do so.

**Comment by vancura** [comment]
Do you know what's the HiDPI engine parameter please?

**Comment by weitjong** [comment]
If you are using Urho3DPlayer, use the ```-hd``` option. See http://urho3d.github.io/documentation/HEAD/_running.html.

If you are building your own binary using Urho3D as external library, set the ```HighDPI``` engine parameter before initializing it. See http://urho3d.github.io/documentation/HEAD/_main_loop.html.
