### ISSUE TITLE
What about real FBX support?

### ISSUE THREAD

**Issue by amerkoleci** [urho3d/Urho3D#1372]
Would be nice to add official FBX sdk support for FBX, Collada and OBJ loading as it supports all of them.

**Comment by cosmy1** [comment]
Assimp supports a very wide range of formats. Why did you need FBX SDK? Is there any particular feature Assimp miss?

**Comment by Stinkfist0** [comment]
FWIW, at least the DAE import of Autodesk FBX SDK is not particularly great and I've been struggling importing many DAEs to Unity and viewing them in ViewFBX (I'm pretty both use the same 32-bit SDK). However at least this one AssImp-based viewer (Open 3D Model Viewer) seems to import these problematic files OK.

**Comment by dragonCASTjosh** [comment]
The only upside I could imagine for the SDK is it's less bulky then assimp although size is currently no problem

**Comment by paper-pauper** [comment]
The FBX SDK is proprietary; no, thanks.

**Comment by JSandusky** [comment]
> The FBX SDK is proprietary; for this reason, it's best to avoid using it.

That isn't entirely true. IT has its' own license agreement that will conflict with projects that aim to be as open as possible. That only makes it "proprietary" in the eyes of copyleft licenses like the GPL. 

The only serious restriction made is in the redistribution of the library. Just because Blender takes issue with something does not make it a real issue in OSS.

A proper FBX converter is viable, though having worked with the FBX SDK I can confirm that it is quite unpleasant to do. Static mesh import is roughly 3 hours of work, skeleton animations are an indefinite amount of work as are morph targets. The indefinite is because the permutations are massive. If a proper FBX importer uses the sampling route provided by the FBX SDK then it won't be that bad, doing it off of the actual data will never end.

Reading FBX is a lot easier than writing FBX ... which really sucks as I'm on a project that requires writing out FBX models and animation.

**Comment by c4augustus** [comment]
I see that AssetImporter currently ignores morphs. The latest version of assimp library code shows that its COLLADA importer does parse morphs. So all that remains, hopefully, is to add morph parsing code to AssetImporter. I'll probably do that this week, and then submit a PR.
