### ISSUE TITLE
Can't use as external lib

### ISSUE THREAD

**Issue by CheeryLee** [urho3d/Urho3D#1398]
Hello!
I try to use Urho3D as external library on my ArchLinux, but when I compile the project, i get the error:
```
Input/InputEvents.h:28
SDL/SDL_gamecontroller.h: No such file or directory
 #include <SDL/SDL_gamecontroller.h>
```
This file is really not in SDL folder -- it's placed in SDL2 folder. Surprisingly, but Urho and samples built successfully.

**Comment by weitjong** [comment]
How did you configure your build tree? I suppose you were not using our build system or otherwise you shouldn't have ended up with this issue. If you look at the our project repository, you should see that the "project" uses a fork version of ```SDL v2.0```. The "project" here does not only refer to Urho3D project but your own project (using Urho3D as external library) as well. In our SDL fork, we have configured that all its headers are found in ```SDL``` directory and never in ```SDL2```.

For this kind of questions, you may use our forum instead of GitHub issue tracker.

**Comment by CheeryLee** [comment]
Solved by adding SDL folder from Urho3D sources into include path.

**Comment by weitjong** [comment]
Glad you have figured that out. Currently some of the SDL headers are rqeuired when using Urho3D library because a few of Urho3D headers have included the SDL headers, but this is totally avoidable via forward declaration and moving the include statement to the corresponding implementation file. In fact I have done so a few days ago but the work get stashed away temporarily.
