### ISSUE TITLE
Codestyle: long lines

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1417]
I know that it is quite strange question, but..
What's the point of very-very-very long lines?

Here is the whole function with two lines of code is written in one line.
![image](https://cloud.githubusercontent.com/assets/8576192/15984480/5e0286ea-2fd5-11e6-9742-7c7208d738d5.png)

However, this is not the "put-anything-in-one-fuckin'-line" rule.
I see a lot of places with another style.

What is the right way to format code?

**Comment by cadaver** [comment]
The cutoff for a line in cpp files has been typically at 130 characters, though it may not be uniformly enforced. In inlined header file functions like that example, I've simply put everything on a long line since in most cases the operation being done is obvious, and this allows the user to see more of the API at a glance (at least in VS editor which doesn't word-wrap automatically)

**Comment by eugeneko** [comment]
I see.
What about comments in headers?
Are they limited to 130 symbols too?

**Comment by cadaver** [comment]
No, there are longer ones. See for example Renderer.h. Some particularly long explanations have been split into block comments, but those are rare.
