### ISSUE TITLE
Threaded navmesh generation

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1420]
Hello, 

Is it technically possible to put the tiled navmesh generation in another CPU tread so it can be used in large open world based games where the navmesh tiles need to be generated / regenerated / removed on the fly to save memory ? Threaded navmesh building is a must have in my opinion :)

Is there anything that could prevent this feature to be added , Im not very familiar with threading rules in the engine...

**Comment by cadaver** [comment]
In general we currently don't have anything in the scene that would be pending a result completion, so this would be a departure. When resources load asynchronously, they aren't returned by the ResourceCache until ready. Also, loading precalculated navmeshs should be fairly fast.

However since Recast/Detour operates on its own data structures the calculation should be possible to thread. I must say that I don't have especial interest to do it but anyone is free to contribute, naturally.
