### ISSUE TITLE
Urho3D as subdirectory

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1427]
I want to use Urho3D as separate library, but it should be linked to my solution as project with source code instead of binaries.
How can I do it?
Seems like add_subdirectory doesn't work because of tons of used constants.

**Comment by weitjong** [comment]
Technically although this is possible, you will have to know CMake quite a bit to make all the necessary tweaks. Our buildsystem is currently not working out of the box for this type of use case. See the discussion here http://urho3d.prophpbb.com/topic1701.html and issue #1167.

You can also see the problem this way. The first we want to use original SDL's CMakeLists.txt into Urho3D project, it also did not work because its CMake scripts see SDL itself as the main project. But with sufficient tweaks, in the end we manage to demote it as subproject/module among others. Analogously, you want to tweak Urho3D in your project the same as what we did with SDL in Urho3D project. Unfortunately though, there are a lot more things we need to sort out before you can successfully add Urho3D as another subdirectory/subproject.

**Comment by eugeneko** [comment]
I hope that at some point after build system refactoring I'll be able to do
it.
Because now I have to keep two IDE instances to navigate in both my project
and Urho3D and it is not very convinient.
And.. Sorry for duplicate.

2016-06-18 11:54 GMT+03:00 Yao Wei Tjong <notifications@github.com>:
