### ISSUE TITLE
Geometry shaders support

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1429]
Nuff said.

Are you going to add support of GS?
If no, how can I do it?

**Comment by OldSnake22** [comment]
I have tried to integrate it myself but i am lacking of some knowledge for doing it...

I would appreciate if someone could add it too

**Comment by 1vanK** [comment]
CodingMonkey has realized GS (somewhere http://www.gamedev.ru/community/urho3d/forum/ ), but it required rewritig all shaders from VS->PS to VS->GS->PS

**Comment by OldSnake22** [comment]
Yes, unfortunately DX11 support was missing

**Comment by OldSnake22** [comment]
I mean DX11 geometry shader support :) CodingMonkey has been making GS for OpenGL but not for DX11 yet.

**Comment by MonkeyFirst** [comment]
~~~
 but it required rewritig all shaders from VS->PS to VS->GS->PS
~~~
Actually no, there is no needing to rewrite all shaders for VS-GS-PS, but only for custom techique what will be use GS shader. i trying to implement optional GS using path. but for now i forgot all what i doing before :)  if i remember right, in my implementation are still exist some problems with using GS with some of render path.

~~~
for OpenGL but not for DX11 yet.
~~~
for my shame i still do not know / learn dx11( and i remember what somebody also try to implement GS for DX11

**Comment by eugeneko** [comment]
I know how to implement GS in DX11 and (more or less) in GL.
However, I feel lack of codebase knowledge to make such features.

2016-06-23 9:03 GMT+03:00 MonkeyFirst <notifications@github.com>:

**Comment by JSandusky** [comment]
I've refactored shader programs into an aggregate of "ShaderStages." Though I haven't migrated it that far it should be suitable for covering transform feedback and TS/DS shaders as well. Might upload and submit a PR.

The change does make a complete mess of those shader constant/uniforms that are defined in the source though. In all honesty though, those are becoming a bit of a liability for being constant once you reach out so far ... makes total sense for PS/VS only, not so much as more and more of the pipeline is exposed.

Thorough OGL support is lacking though in my implementation.

> Actually no, there is no needing to rewrite all shaders for VS-GS-PS, but only for custom techique what will be use GS shader. i trying to implement optional GS using path. but for now i forgot all what i doing before :) if i remember right, in my implementation are still exist some problems with using GS with some of render path.

That isn't entirely true (note the "entirely"). For anything involving cubemaps (ie. point light shadows) writing the necessary GS is essential because if you're on a GS capable target then you should exploit the GS ability to write primitives to different targets to make 1 call and render a mesh into the cube rendertargets. 

Hence I specified "isn't entirely" as the shadow shaders are relatively freestanding.

That same capability is also significant as a very basic optimization for VR rendering. In that case @dragonCASTjosh 's suggestion of a common shader lang becomes more meaningful or at the least a refactoring of shaders into an "expected format to parse" in order to automatically generate the necessary GS for outputting to the render-targets for each eye. Though "expected format" to parse could be easily be limited to "your input/output structs MUST be named THIS" as VR/cubemap shaders are basically just duplication.

**Comment by MonkeyFirst** [comment]
~~~
Might upload and submit a PR.
~~~
cool, because acutually i don't want dig into it again, at all. But probably you will need waiting till @Cadaver introduce PR with api-agnostic headers.

~~~
That isn't entirely true (note the "entirely").
~~~
Actually i mean (in my implimentation) if you need some technique with GS you will need write new own custom LitSolid/Unlit shader(s) with GS interpolators passing. And if you don't need this, you don't do any changes and continue using std shaders.

**Comment by hdunderscore** [comment]
Any progress on this?

**Comment by JSandusky** [comment]
Thanks for reminding me about this. I had finished up GL support a bit ago and need a break from cleaning up compute right now. I'll get this wrapped up for review over the next couple of days.

**Comment by JSandusky** [comment]
I've looked over my stuff on this, the only controversial bits are that I "objectified" the shader constants (VSP_AMBIENTSTARTCOLOR, etc) to eliminate redundancy, although geometry shaders could realistically reuse everything involved in vertex-shaders, that was about the tesselation related shaders (which I have no desire myself to implement, I was just thinking about them as I implemented it - GL and DX diverge on those greatly).

I just need to update it all against the latest Urho3D trunk, fill in some doxy documentation, append the shader documentation, and implement a basic sample (I'll just stick with the triangles -> hexagons I had done before). I'll submit PR for review before wrapping up a sample. It'll still take a short bit of time (finger vs door + wind = finger loses).

I expect zero agreement on the adjacency helpers, adjacency index buffers are a dilemma. I think that's a whole community issue as it invades tools, direct exporters, etc.

**Comment by najak3d** [comment]
JSandusky - what is the status of Geometry Shader support for Urho3D?   We actually want it for UrhoSharp.

We are in process of determining if UrhoSharp will become our 3D engine for a 3D global mapping application port.   (The application already has been in production for 14 years, but we're transforming it from 2D to 3D this year.)

**Comment by JSandusky** [comment]
It's functional but lacking support for fallbacks in Material technique selection when there isn't support for GS/HS/DS (so you'd have to abuse the quality-levels) and GL-ES was never checked for compilation. 

I use it all the time since I replaced the Urho3D DebugRenderer with IM3D that uses the GS for lines and points but I won't be making a PR for it.

It's massively out-of-date with master so you'll have to use a merge tool (winmerge or w/e). I clean split from master back in 2017. Source is in the Shaders.zip dump https://github.com/JSandusky/Urho3D (it's just the Graphics folder + `GSTest`/`TessTest` and GS expanded particle shaders), UI changes are that `SetShaders(...)` now takes more arguments for all shader stages so they're not included [add default params if desired]).

There's a much more up to date rewrite for RBFX, https://github.com/JSandusky/rbfx/tree/JS/Shaders with an intact commit history. Although it's for RBFX it's probably easier to see the changes that way then via a merge tool, since RBFX didn't change Graphics much.

---

Minor DX11 caveats:

-  CBuffers must be compatible between VS,GS,HS,DS stages (new ones can be added, but if **b0** is used then all of those stages need to expect the same buffer for **b0**
    - Only applies to DX11 since OGL already has that constraint
    - A consequence of how I implemented it to reduce book-keeping to just a sanity check instead of juggling assignments within `MAX_SHADER_PARAMETER_GROUPS` while not making OGL code brittle
- VertexInputLayouts aren't quite perfect (works in all tested cases though), more recent rewrite I did for RBFX is more aggressive
    - Only applies to tessellation

---

I don't know what any of it would require on the UrhoSharp side regarding binding generation, some functions change a fair bit to account for there now being more than just 2 shader stages (ie. enum parameters, etc) so I would expect that you'd have to regenerate the bindings.

**Comment by najak3d** [comment]
Thank you for the response.  It's very good to hear from you.  I'm glad to see you from Ohio; I was born/raised in Cincinnati OH, then went to college in Indiana, where I live now (just south of Indianapolis).   What part of Ohio are you in now?

I've been in chat with Rokas Kupstys about creating RbfxSharp, which would be the same as UrhoSharp, except it would wrap Rbfx instead.   He mentioned that Eugene is now the one who knows most about the Geometry shaders, which have not yet been merged into Rbfx -- maybe that is what you are referring to as well?

Even if it fails to provide fallbacks, I think Geometry shader samples would go a long way to help Rbfx eclipse Urho3D, and become Microsoft's new recommendation for Xamarin 3D plugin.

When you mention fall backs, how much in use are devices/PC's that would require these fallbacks to function?   Our product targets Windows/Android/iOS devices that are up to 6 years old, typically.

**Comment by JSandusky** [comment]
>  What part of Ohio are you in now?

New Albany area, outside of Columbus.

> He mentioned that Eugene is now the one who knows most about the Geometry shaders, which have not yet been merged into Rbfx -- maybe that is what you are referring to as well?

Possibly, now that you mention Eugene does have a copy my older Urho3D specific GS/HS/DS code with an intact commit history in a branch https://github.com/eugeneko/Urho3D/tree/GeometryShaders.

> When you mention fall backs, how much in use are devices/PC's that would require these fallbacks to function? Our product targets Windows/Android/iOS devices that are up to 6 years old, typically.

~5 years old for most GL ES 3.2 support, so it's still going to be quite a lot without it. S7s and onward. WebGL is the more serious gotcha.

How bad that is really depends on what you need to write a fallback for, if you're just using the GS to create nicely mitred / rounded lines then a fallback that's sort-of ugly (like just using the RibbonTrail with explicit points) isn't so serious. Using the tessellator to procedurally add chamfer edges to faces is serious if you require the chamfer.

**Comment by najak3d** [comment]
For lines, we're just adding rounded ends and joints, which could just we a few extra triangles, or a square with a radius-based opacity falloff.   Mostly we just want to eliminate the obvious defects that would otherwise occur at the ends of thick lines that intersect at a moderate angle, and using the falloff along edges to prevent jagged pixelation.  Nothing fancy.  We've already got this working fine without Geometry shaders.

So mostly, it becomes an efficiency thing, since we frequently will swap in/out lines, as well as modify the width of the lines as you zoom in (we will be mostly maintaining a near constant screen width (where there are caps for min/max width -- so as you zoom out they get smaller, but not too small, and as you zoom in they get wider, but not too wide).   This auto-modification of width, without redefining all geometry points, will be done much more cleanly and efficiently with geometry shaders.    We're only drawing 10K-20K line segments at a time, MAX, so performance of the geometry shader shouldn't be an issue.

**Comment by JSandusky** [comment]
Reviewed the copy Eugene has, has the same issues as the RBFX version. ShaderID is garbage (I use _mm_cmplt on __m128i myself, but the public code doesn't since I can be harsh in my own constraints) and it's unchecked for non-Windows targets. That's all.

That fork is viable for someone to pick up, I'd only pick it up personally if someone else picked up a **NO-SDL2** path for Urho.

**Comment by najak3d** [comment]
What do you have against SDL2?  Why is no-SDL2 vital to you?  Isn't this the magical component typically used to aid in cross-platform support?  What would you use to replace it?

**Comment by JSandusky** [comment]
Arcade hardware, need a generalized backend for windowing/file-IO/input to consider Urho3D for it. Adding platform support to SDL2 is pain when you're looking at something like Sega RidgeXXX boards that run on WES.
