### ISSUE TITLE
Create new resources from component code.

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1430]
I want my component to create some models/textures/etc.
And I need some property for editor that allow me to specify non-existing resource like destination resource.
How can I do it?

**Comment by cadaver** [comment]
Easiest but a little clumsy is to create a string attribute for the destination resource name. 

Urho's resource system does not really help you in creating new files. Resource folders are added as search paths into the resource system, but it doesn't by itself help you decide where a file should be saved. Look for the editor code (material and particle effect editor) for inspiration.

If it's appropriate for your use case, for example you will always be creating the resources in memory each time the program runs, it's not required to save resources to disk at all. Instead you can "new" a resource of whatever type, assign it a name, and call ResourceCache::AddManualResource() so that other code can refer to the resource.

For actually filling the resource data programmatically, use the resource's public API. For models you can refer to AssetImporter tool code for assistance.

**Comment by eugeneko** [comment]
Actually I need some way to store procedural data that could be cached between application runs.
So memory resources are not acceptable.
Thank you, I'll try to impemented it this way..
