### ISSUE TITLE
CMake ignored default build samples (off) 

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#1437]
The default building sample applications option (off) is ignored. I have to force set it to build with CMake `-DURHO3D_SAMPLES=0`, unless you already changed the default build option and have not updated the docs.

http://urho3d.github.io/documentation/1.5/_building.html

![sam](https://cloud.githubusercontent.com/assets/3676827/16360154/db854fbc-3b83-11e6-9916-02f7fabe05c0.jpg)

**Comment by weitjong** [comment]
You are correct to point out that there was documentation errata when we released 1.5. The build option for Lua and samples has been changed to on by default just before the release, however, that was not being reflected in time in the documentation. The errata are now corrected in HEAD version of the documentation. Since we do not normally do "backport", we won't go back to correct them in 1.5.
