### ISSUE TITLE
Memory leak on Windows in Window mode

### ISSUE THREAD

**Issue by KonstantinTomashevich** [urho3d/Urho3D#1438]
Hi! I download Urho3D repository (master branch) week ago and now I find small memory leak in application window mode on my Windows 7 x64.
For clear expiriment I run 3 applications: Windowed Empty Application, Fullscreen Empty Application, HelloWorld Sample. After that I open task manager:
```
Windowed Empty Application memory: 22 164 kilobytes.
Fullscreen Empty Application memory: 11 140 kilobytes.
HelloWorld Sample memory: 30 176 kilobytes.
```
After 10 minutes:
```
Windowed Empty Application memory: 31 080 kilobytes.
Fullscreen Empty Application memory: 11 408 kilobytes.
HelloWorld Sample memory: 41 260 kilobytes.
```
Result: around 18 kilobytes per second memory leak.
I know that this memory leak is not very big and maybe is not critical. But I think it will be good if somebody fix it. :)

**Comment by cadaver** [comment]
If this is an actual memory leak within Urho it's certainly critical and should be fixed. However, do you see the memory use increase linearly as a variable of time, ie. if you let the program run 20 minutes instead, has the memory use grown to about 50 MB? Do you see detected leaks if you run the program inside debugger in debug mode?

In a 3D application, it's not uncommon to see the memory use grow after startup due to the system and drivers taking their share.

**Comment by cadaver** [comment]
Have been running HelloWorld in both 32 & 64 bit builds and I'm not able to see behavior that would indicate an actual memory leak. Tempted to close if there are no further comments or confirmation from others.

**Comment by weitjong** [comment]
I cannot confirm on Windows platform. However, I am quite sure there is no memory leak issue on Linux platform. Tested using valgrind against master branch just a few weeks ago. I suppose with the exception of graphic backend difference, the engine uses mostly the same code base for both Windows and Linux platforms.

**Comment by cadaver** [comment]
The closest I got to this was in D3D11 Debug mode build, where the private working set would indeed increase noticeably per each second after startup, but this continued only for about 10-20 seconds, then it stopped. No leaks were shown by VS. My guess is that this is the graphics driver or D3D runtime allocating more memory for its internal use.

**Comment by KonstantinTomashevich** [comment]
Ok, thanks for your replies. I think, this is problem of my pc, because there is similar memory use increase in HelloWorld in 1.5 release.

**Comment by cadaver** [comment]
It could theoretically be a driver version or Windows configuration issue, hard to know. However can you answer, if you let HelloWorld run longer, do you see memory usage rising constantly, even over the 41260 KB you stated in your first post?

If there is an actual Urho problem then it would be completely credible to be in both 1.5 release and current master, since I don't remember any issues of this sort being found and fixed in the meanwhile.

**Comment by KonstantinTomashevich** [comment]
> do you see memory usage rising constantly, even over the 41260 KB you stated in your first post?

No, it stops around 42000-43000 KB.

**Comment by cadaver** [comment]
Then I'd say even your machine is behaving relatively normal and as expected. Closing this, can be reopened if there is evidence of a specific leak in the engine code.
