### ISSUE TITLE
  NDK r10e: Could not check compiler toolchain as it does not handle '-E -dM' compiler   options correctly

### ISSUE THREAD

**Issue by guijun** [urho3d/Urho3D#1450]
CMake Error at CMake/Modules/CheckCompilerToolchain.cmake:59 (message):
  Could not check compiler toolchain as it does not handle '-E -dM' compiler
  options correctly
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:87 (include)
  CMakeLists.txt:50 (include)

NDK r10e.

**Comment by weitjong** [comment]
I assume you use latest master branch based on those line number you gave. There are a few reasons I could think why it failed (for your case), like:

- CMake failed to find the C compiler in your Android NDK. Did you get any message from CMake earlier on when it validated the compiler toolchain?
- If it found the compiler correctly then probably it was caused by your "shell" did not know how to "pipe" from one subcommand to another. And it later fell back to inner check that is originally designed for emcc (the "fake" compiler front-end as it is just a python script).
- The fallback check uses temporary empty file. Rightfully, the fallback check should work for Android compiler too (GCC or Clang). But I have not tested this first hand so I don't know for sure. But since it failed too there, I guess we could say it is a bug (if it really the case, however, I doubt that).

All Android compilers must know '-E' and '-dM' compiler flags.

**Comment by guijun** [comment]
CMake Error at CMake/Modules/CheckCompilerToolchain.cmake:56 (message):
  /usr/local/bin/ccache dummy.c -E -dM RESULT_VARIABLE CC_EXIT_STATUS
  OUTPUT_VARIABLE NATIVE_PREDEFINED_MACROS ERROR_QUIET
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:87 (include)
  CMakeLists.txt:50 (include)

**Comment by guijun** [comment]
set( NDK_CCACHE /usr/local/bin/ccache CACHE INTERNAL "" )
set( LIBRARY_OUTPUT_PATH_ROOT /Users/kkk/Documents/ude4/kmc_engine/build_and CACHE INTERNAL "" )
set( ANDROID_FORBID_SYGWIN TRUE CACHE INTERNAL "" )
set( ANDROID_NDK_HOST_X64 1 CACHE INTERNAL "" )
set( ANDROID_NDK /Users/kkk/Documents/app.sdk/android-ndk CACHE INTERNAL "" )
set( ANDROID_NDK_LAYOUT RELEASE CACHE INTERNAL "" )
set( ANDROID_TOOLCHAIN_NAME arm-linux-androideabi-4.9 CACHE INTERNAL "" )
set( ANDROID_ABI armeabi-v7a CACHE INTERNAL "" )
set( ANDROID_NATIVE_API_LEVEL 12 CACHE INTERNAL "" )
set( ANDROID_STL gnustl_static CACHE INTERNAL "" )
set( ANDROID_STL_FORCE_FEATURES ON CACHE INTERNAL "" )
set( ANDROID_FORCE_ARM_BUILD OFF CACHE INTERNAL "" )
set( ANDROID_NO_UNDEFINED ON CACHE INTERNAL "" )
set( ANDROID_SO_UNDEFINED OFF CACHE INTERNAL "" )
set( ANDROID_FUNCTION_LEVEL_LINKING ON CACHE INTERNAL "" )
set( ANDROID_GOLD_LINKER ON CACHE INTERNAL "" )
set( ANDROID_NOEXECSTACK ON CACHE INTERNAL "" )
set( ANDROID_RELRO ON CACHE INTERNAL "" )
set( ANDROID_LIBM_PATH -lm CACHE INTERNAL "" )
set( ANDROID_EXPLICIT_CRT_LINK OFF CACHE INTERNAL "" )

**Comment by weitjong** [comment]
I think I see your issue now. We (Urho3D) do not support ```NDK_CACHE``` option of original android.toolchain.cmake file, although we could have. Instead, we follow Android documentation for ccache setup. See https://source.android.com/source/initializing.html#optimizing-a-build-environment. Remove ```NDK_CCACHE``` option and replace it with ```USE_CCACHE``` environment variable which you "export" it only once in your build environment. As a matter of fact this ```USE_CCACHE``` environment variable is also honor by the other custom toolchain files that we have in Urho3D codebase.

I am actually also working on a new version of android.toolchain.cmake file. I should be able to commit it in the next few days, if all goes well, in the ```refactor-buildsystem``` branch. In the new version, I have removed the unsupported ```NDK_CCACHE``` code all together.
