### ISSUE TITLE
Incorrect Text attribute (class Text)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1451]
Instead URHO3D_ATTRIBUTE("Text", String, text_, String::EMPTY, AM_FILE);
should be URHO3D_ACCESSOR_ATTRIBUTE("Text", GetText,SetText

becose when loading:
```
        <element type="Text" style="ButtonText">
            <attribute name="Auto Localizable" value="true" />
            <attribute name="Text" value="START!" />
        </element>
```
stringId_ still emty and text_ cleared when language is changed.

**Comment by cadaver** [comment]
Thanks for noticing. Will just need to check that there aren't performance issues due to updating the text multiple times when loading. Alternate solution is to implement custom logic to ApplyAttributes.

**Comment by cadaver** [comment]
I believe correctness and performance can be best kept by adding separate SetTextAttr & GetTextAttr functions that handle the stringId. When saving a localized text element (especially after live edits and language changes), it's the stringId that needs to be saved, so that already localized text isn't incorrectly saved.

**Comment by cadaver** [comment]
Actually, if this were a UI element saved by the Urho editor the order of attributes would be different (autoLocalizable last) and I believe it would already work. However it's good to fix to make it work for any order.

**Comment by 1vanK** [comment]
Thank you so much
