### ISSUE TITLE
Android and PackageFile support

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#1455]
I just found this late and so I thought we could use pak or package files on Android..

https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/IO/PackageFile.cpp#L57-L63

maybe a feature request?

**Comment by cadaver** [comment]
This has been discussed on the forums some times already. The .apk is already an archive and (unless I have outdated information and the situation has improved) the Android AssetManager provides relatively poor methods for unrestricted random access. It would be good for completeness' sake but the practical performance especially for a big package could be poor, so it's better to just use individual files packed by the native .apk mechanism.

**Comment by cadaver** [comment]
Ok, looked at SDL code and there is a "good" path (if SDL manages to get an "assetFileDescriptorRef" which allows normal seek operations and the "bad" path which reopens and rereads up to the wanted position to emulate a seek. This is all handled transparently by SDL, but I don't know when getting the descriptorRef succeeds. Maybe someone more familiar with Android packaging can clarify. Anyway, since that is the case, it could be worth it implementing package support (though with some added code complexity) which may or may not perform well, but at least the user wouldn't just get a "not supported" error message.

**Comment by rasteron** [comment]
Thanks Lasse!

**Comment by cadaver** [comment]
Have taken a shot at implementing this and it seems to work. I believe I've now seen the "good" and "bad" modes in action, "bad" mode performance is indeed noticeably poor when running NinjaSnowWar for example. I was able to get good performance by specifying compression (-c flag) for PackageTool. In that case it seems that the .apk packaging skips its own compression. Will add a note of this to documentation.

**Comment by weitjong** [comment]
Cool! With this change, we could probably make ```URHO3D_PACKAGING``` build option works properly for Android platform too.

**Comment by weitjong** [comment]
Tested with URHO3D_PACKAGING=1 too, but only on an emulator.

**Comment by rasteron** [comment]
I just tested this on an emulator as well, no errors but I got the options dialog instead. It should launch NSW by default since this is in [commandline.txt](https://github.com/urho3d/Urho3D/blob/master/bin/Data/CommandLine.txt)?

Btw, got the 2 paks generated during build inside assets folder before running ant.

**Comment by rasteron** [comment]
Ok, just created Data folder with the commandline.txt outside the pak file and it now works great! 

Thanks.

**Comment by rasteron** [comment]
In terms of loading time and performance, yes when compressing I don't see any difference so far using emulator and an average android quad phone, seems to be the logical or default option.
