### ISSUE TITLE
Re-order components and nodes in Editor

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1463]
Subj.
E.g. I have some requirements on component order or just for aesthetic reasons.
And manual remove-add is not a solution, of course.

**Comment by 1vanK** [comment]
U can use temp node for reordeing :)

https://github.com/urho3d/Urho3D/issues/1088

**Comment by MonkeyFirst** [comment]
You want to group by type of component
~~~
StaticModel
StaticModel
SoundSource
SoundSource
CustomGeometry
CustomGeometry
~~~
or what?

**Comment by eugeneko** [comment]
I want to have a way to change order of nodes and components as I wish because current restriction looks very synthetic.

If you are interested in my actual task, I need to make sure that one component (or node) is loaded before another one because of some dependencies.

**Comment by cadaver** [comment]
Since dragging already means reparenting we'd have to overload the action with a key held down, for example CTRL. I believe this is simply missing due to not being implemented yet. It certainly should be doable.

However I'd recommend to program components so that they can work regardless of the component order. For inspiration look at e.g. the interaction between RigidBody and CollisionShape. It can get complex, but in my opinion is worth it for robustness.

**Comment by eugeneko** [comment]
I don't need _interaction_ between components. My components generate resources that are cached on the drive and used by another components. E.g. procedural tree component that provides geometry for StaticModel component of the same (or not) node. So if there are no cached data on drive, I need procedural component to be loaded before any depecdend components, because otherwise I'll get an error caused by missing resource.
Maybe it could be better to create such procedural components derived from its users (StaticModel), but I don't want such kind of hard dependency.
In my 'engine' I run some script before scene loading, but this approach disables all component features like hot editing.

**Comment by cadaver** [comment]
Dependance on a generated resource essentially is interaction, though not direct. You should be able to rethink the problem so that any load order produces correct result. One approach would be to have the tree staticmodels have empty model refs, and only the generator component assigns them once it's done.

**Comment by eugeneko** [comment]
Re-ordering nodes works with Ctrl+MouseLeft drag. How to re-order components?

**Comment by eugeneko** [comment]
Thank you, I think I missed this commit.

2016-08-08 10:57 GMT+03:00 Lasse Öörni <notifications@github.com>:
