### ISSUE TITLE
Shadow Maps Optimization

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1465]
Hello,

Currently shadow maps rendering consume a lot of performances. For games that need a "lot" of light sources this is very problematic as the shadow maps are rendered every frames. With just 3 point light the frame rate is dropping quite a bit and this is sad because the rest of the engine is quite well optimized :)

A basic idea would be to have flags on each drawables, those flags would be for example: 

LIGHT_DYNAMIC
LIGHT_STATIC

Two shadow maps would be generated for each spot and point lights source. and the idea is to only draw the shadow map when needed based on those flags and when the drawables are moving. So the shadows are not drawn every frames like it is now.

This optimization is explained here: http://www.leadwerks.com/werkspace/blog/1/entry-114-double-buffered-shadow-maps/

I have tested this optimization in leadwerks engine in the past, before and after and the performance gain was very noticeable.

I can't handle this work myself as i miss some knowledge on the subject but i would be very happy if Cadaver could try it. I think it's very important to optimize shadow rendering as it have a too big impact on performances for now :) 

What is your opinion about it @cadaver ? 

Thank you

**Comment by damu** [comment]
Shadow performance and shadow artifacts are also common issues for me (like http://urho3d.prophpbb.com/post6060.html and http://urho3d.prophpbb.com/post9596.html). I'm also note knowledgeable enough in that subject to improve the situation. Some other engines perform way better though so there seem to be solutions. The Urho forum has 19 pages with results about shadows and issues with them: http://urho3d.prophpbb.com/search.php?keywords=shadow

Many games seem to render small dynamic lights each frame but big lights like the sun only every few seconds. I guess because the small ones don't use cascading (multiple shadow maps depending on distance). Maybe one could also differentiate between static (or semi-static) geometry and dynamic geometry to render the former note every frame into shadow maps but the later every frame?
Maybe it would help to reduce the shadow map resolution (with this http://urho3d.github.io/documentation/1.5/class_urho3_d_1_1_light.html#add6673792827a34b148eea6b9cba71fe ?) of a light that is far away?
Maybe one could also use a different (more expensive) shader for a shadow map that doesn't use bilinear interpolation/scaling but one that uses some kind of rounding so that lower resolution maps look better?

Some general information, though not really about buffering shadow maps:
https://msdn.microsoft.com/en-us/library/windows/desktop/ee416324(v=vs.85).aspx
http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-16-shadow-mapping/

**Comment by cadaver** [comment]
It's a good idea, but it has potential to complicate the rendering code (which is already the most complex part of Urho3D) and shadowing shaders more, and require additional tracking structures for which drawables have moved in which light frustums. The current Urho3D rendering code aims to effortlessly render a limitless amount of shadowed lights (though with performance cost) and this method rather needs a unique texture allocation per a shadow visible on the screen.

I don't think I'd start working on it now but it's good to keep in mind. Meanwhile anyone else is naturally encouraged to tackle it, but like said it can get complex.

In my own measurements I've thought shadow rendering to be lightweight compared to shadow sampling, but of course it depends on the world geometry. A lot of shadowed lights (especially point lights) will certainly never be free.

**Comment by cadaver** [comment]
Note that you can already manually cut down on unnecessary shadow caster interactions by using the shadow mask bits in drawables and lights. Occlusion is not applied to the shadow caster queries so for example a wall behind a wall could get unnecessarily rendered to a point light shadow map.

**Comment by dragonCASTjosh** [comment]
I think the best solution to shadow performance issues would be to have a system to bake shadows, although I know this would be a massive task and would need to be maintained by the creator

**Comment by cadaver** [comment]
Yeah, I'm sure e.g. Unreal or Unity have dedicated programmers just for the lighting. Unreal especially has a rather complicated matrix of static / baked / dynamic lights and shadows, which takes its toll on the architecture and runtime complexity. Urho's approach is more of the "Doom3" school, ie. do all light interactions as dynamic for code simplicity.

**Comment by dragonCASTjosh** [comment]
In that case may I suggest taking the cryengine path with only realtime GI

**Comment by dragonCASTjosh** [comment]
As part of the shadow talk i guess its fair to bring up some of the issues with VSM

**Comment by cadaver** [comment]
The typical issue with VSM is that it doesn't play nice with non-shadowed surfaces at all (shadows get too thin), unlike regular depth shadow mapping. Point light shadows looked somewhat broken with VSM but I didn't check in too much detail.

**Comment by dragonCASTjosh** [comment]
i did VSM in my experimental renderer without to much issue but after checking the code within Urho it looks practically the same but my renderer doesnt have these issues, im not sure where the root of the problem is

**Comment by aksyom** [comment]
A total newbie here, just testing Urho3D with previous experience on Panda3D and UPBGE.

In my experience static shadow maps are the way to go.

Would only need 2 things in the Light class:
- SetStaticShadowMap(bool), GetStaticShadowMap(): if true, then automatic shadow map updates are disabled for this light, the shadow map is only generated once
- UpdateShadowMap(void): if called, then shadow maps will be updated once in this frame

If I had these methods available in the Light class, I could simply just
1) create and attach a dummy directional light the frustrum of which covers the entire scene, 4K or even 8K shadow map resolution, only one cascade
2) call light_->SetLightMask(0x0) to disable illumination for this light; we only require the shadow map
3) use light_->SetShadowMask(...) to setup the shadow mask so that only static objects cast shadows from this light
4) call light_->SetStaticShadowMap(true) which makes the shadow map updated only once
5) call light_->UpdateShadowMap() when I feel like updating the shadow map for any specific reason, ie. if any of the static objects in the scene move, or if new objects are parented etc.
6) add a normal dynamic directional light, covering a smaller area, that follows the viewport camera; this light actually illuminates the scene and casts shadows for moving objects

The static shadows would be overlapped by the dynamic shadows, in a way they complement each other.

Of course static shadow maps don't help with point lights or the like, since you most probably want moving objects to cast shadows from those.
