### ISSUE TITLE
No connection:delete() in Lua API

### ISSUE THREAD

**Issue by MaxTheBackspace** [urho3d/Urho3D#1467]
Writing networking code can be hard so some people might choose to write it in Lua to make it easier to prototype. However, there is no connection:delet() binding to ~Connection() destructor, so this will occupy more memory as more clients join and disconnect. The https://github.com/urho3d/Urho3D/blob/master/bin/Data/LuaScripts/17_SceneReplication.lua example simply uses table.remove to get rid of the connection object, hoping it will be garbage collected by Lua.

**Comment by cadaver** [comment]
The authoritative memory management of client connections is performed by the Network subsystem (as actual UDP connections are made and broken off), and applications should not ever need to invoke Connection's destructor. The Lua table is merely holding a (weak) reference to the Connection object to tie them to the controlled scene nodes, and it shouldn't leak. However don't take this as 100% gospel since I didn't write the Lua bindings memory management myself.

**Comment by cadaver** [comment]
This shouldn't be an actual issue, and no further discussion, so closing for now.
