### ISSUE TITLE
Make usage of Urho3D/include folder optional

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1473]
For now Urho3D have to be used through **Urho3D_build/include/Urho3D** folder.

Pros:

- Clean include folder

Cons:

- Two copies of includes that have to be synchronized if symlinking isn't acceptable.
- _Ruined code navigation like go-to-source and go-to-definition_. This is the worst thing that could happen when I investigate smbd's code.

I even can't use **Urho3D_src/source/Urho3D** without extra work because this folder have no Urho3D.h

I suggest to _allow_ to use **Urho3D_src/source/Urho3D** as include folder.

**Comment by weitjong** [comment]
The discussion about the SDK-like include dir is already over, I am afraid. See issue #556. In the past we didn't use SDK-like include dir, we had peoples suggesting us to use it, and now we have it people requests us to go back. :smile:  We cannot keep everyone happy.

**Comment by eugeneko** [comment]
> We cannot keep everyone happy

In this case you can. SDK-like include dir should not make obstacles for ones who just don't want to use it. All that need is the option like URHO3D_EXPORT_SOURCES to just make code navigation happy _or_ some work with generated headers like Urho3D.h that break direct usage of Urho3D/Source as include dir.

**Comment by weitjong** [comment]
Not sure I am really following you here. What kind of code navigation problem are you facing with? Are you just referring to the difficulty in navigating to the generated "Urho3D.h" file? If yes, then it has nothing to do with SDK-like include dir. All the generated files (source and/or header) may not be visible in the IDE's project browser because they are generated in the build tree, while usually IDE only list project files in the source tree. You may approach the vendor of your IDE producer to fix that problem. I am using CLion and I have opened a ticket with JetBrains to have that problem fix. In the meantime there is nothing prevent me from opening any of the generated files manually in the IDE by using the "File|Open" menu.

If there is a way to keep all our limited users base happy, we will usually do it. However, in this case we would prefer to have consistency. We would prefer it is ```#include <Urho3D/Engine/Application.h>``` everywhere we look.

If browsing/navigating the generated files is indeed your main beef then perhaps you can just tell CMake to generate the build tree on top of the source tree. This way, all the files are then appears to be in a single tree. We usually do not recommend that though.

**Comment by eugeneko** [comment]
> What kind of code navigation problem are you facing with?

I can't go to Urho3D source code (from header to cpp or from declaration to definition) when I use Urho3D as external library.
E.g. I want to go to implementation of StaticModel::SetModel. I can easily open StaticModel.h and declaration. What should I do next? F12 doesn't work, VisualAssist's Alt-G that is much clever than F12 doesn't work too. Alt-O that switches from header to source and vise versa doesn't work too.

Please suggest some one-click solution for my case if you don't want to change anything.

**Comment by weitjong** [comment]
Just want to be clear here about one point. None of the core devs here are under any obligations to support anyone in relation to the usage of Urho3D. However, you can help yourself and modify it to your heart content to suit your own need. With that cleared, now, I don't think what you asked is possible at all. That is what by definition external library is. IDE should only know about its interface and not its implementation. Ask yourself, could you highlight a DX11 methods or a method from any other external libraries and jump to its definition? Unless you have the corresponding library source code also "included" as part of your own project's build system, I believe the answer is NO.

Having said that, I agree with you that this is not convenience and especially so since Urho3D is an open source project where its implementation is available. Actually I have been asked about this a few times already (publicly or personally) on how to solve this. In Java world one could attach a library source code zip file to an external JAR library file with a few clicks. I don't think there is a standard mechanism in C++ world for that, correct me if I am wrong.

IMHO, the only way to achieve that is to customize your own project so that it includes/embeds Urho3D as one of its internal targets (as opposed to external library). Unfortunately, our build system currently does not support this use case but we plan to support it in the near future.

**Comment by eugeneko** [comment]
> I don't think what you asked is possible at all. 

Now I think that I only need a way to automatically copy Urho3D sources to Urho3D/include too. I am not very familiar with CMake scripts and Urho3D build system. Could you give me a hint where is Urho3D/include dir generated?

**Comment by weitjong** [comment]
I am not sure that will work. Perhaps it will for VS, not really familiar with it. Before you try to automate it, have you tried to set that up manually?  Installing headers is a necessary thing to do for preparing the Urho3D SDK. While installing source files is not. However, I won't stop you to experiment with it. To answer your last question, the headers are installed using ```install_header_files()``` macro in the Urho3D common module.

**Comment by eugeneko** [comment]
> Before you try to automate it, have you tried to set that up manually?
I checked. Switching between source and header files works fine. This is enough for navigation although go-to-definition is more handy.

Changing install pattern to `*.h *.cpp` was enought for reaching my goals, thank you.

**Comment by eugeneko** [comment]
Just a minor whin. I've just lost ~1h of my work.

1. Edit header.h
2. During navigation came to include/*/header.h instead of Source/*/header.h
3. Try to build
4. (rage)

**Comment by weitjong** [comment]
I am sorry to hear that. That's the inherent danger of having hard-copies that the build system has warned about. In other host systems we don't have this problems. If you have better way to solve this for Windows without complicating the others then I have no objections.
