### ISSUE TITLE
Inverse Square light falloff

### ISSUE THREAD

**Issue by dragonCASTjosh** [urho3d/Urho3D#1478]
This is a physically correct model for the falloff of light dependent on the range of the light. its a simple implementation equal performance to the current fall off solution. The downside/ reason i bring it up is the current Implementation replaces the texture based solution, i dont want to sync time into the changes if they are not merged to master as i dont have a person need for it.

**Comment by cadaver** [comment]
There is nothing in the engine that says the texture-based falloff needs to be used, ie. it can just as easily be replaced with an arithmetic calculation in the user's custom shaders.

However inverse square falloff in theory expands into infinity, which is difficult because you'd usually want light radius to be bounded so that you can apply culling to light interactions.

**Comment by dragonCASTjosh** [comment]
The way i implemented it was as a modification to current falloff system so it should only be applied in the same way as the current solution

**Comment by dragonCASTjosh** [comment]
The changes are a small modification to the diffuse method in lighting.[.hlsl/.glsl], the following code is the DirectX implementation  

```
float GetDiffuse(float3 normal, float3 worldPos, out float3 lightDir)
{
    #ifdef DIRLIGHT
        lightDir = cLightDirPS;
        #ifdef TRANSLUCENT
            return abs(dot(normal, lightDir));
        #else
            return saturate(dot(normal, lightDir));
        #endif
    #else
        float3 lightVec = (cLightPosPS.xyz - worldPos) * cLightPosPS.w;
        float lightDist = length(lightVec);
        float falloff = pow(saturate(1 - pow(lightDist / 1, 4)),2) ;

        lightDir = lightVec / lightDist;
        #ifdef TRANSLUCENT
            return abs(dot(normal, lightDir)) * falloff;
        #else
            return saturate(dot(normal, lightDir)) * falloff;
        #endif
    #endif
}
```

**Comment by cadaver** [comment]
I think it's OK if you make it so that the inverse square falloff is only used in PBR mode. That way we don't lose any existing usecases, since it can be assumed that PBR user won't want a wacky texture-based falloff curve. Also note that if you change the spotlight attenuation to no longer use a texture, we'd lose usecases like a "dirty torch" projector texture.

**Comment by dragonCASTjosh** [comment]
i was looking into IES texture for use on spot lights and point lights. This is a simular solution to how Frostbite and Unreal handle the light textures.

 Results
[http://docs.unrealengine.com/latest/images/Engine/Rendering/LightingAndShadows/IESLightProfiles/IES_SpotVsPoint_02.jpg](http://docs.unrealengine.com/latest/images/Engine/Rendering/LightingAndShadows/IESLightProfiles/IES_SpotVsPoint_02.jpg)

**Comment by dragonCASTjosh** [comment]
#1477 Changes added in this PR

**Comment by cadaver** [comment]
Closing as the PBR PR was merged.
