### ISSUE TITLE
Serialize Image to DDS

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1480]
It looks strange for me that Image could be read from DDS but couldn't be written to.
I suggest to add SaveDDS method and maybe SerializeDDS(Serializer&).
I am trying to implement is on my own but I am afraid that I can do something wrong because Deserialize logic is quite complicated.

**Comment by cadaver** [comment]
We don't currently integrate a library which would do it, and as you say, doing it manually is errorprone. Especially block compressing a RGB(A) image would certainly require an external library instead of implementing ourselves.

This is not seen as a priority since Urho's primary function related to images is to consume them to upload to the GPU, and it's not intended as an image production or manipulation library. Though I suppose some asset pipeline related functions (ie. rendering cubemaps / lightmaps) would benefit from it. PNG etc. saves are already provided as convenience for screenshots and such.

**Comment by eugeneko** [comment]
> Though I suppose some asset pipeline related functions (ie. rendering cubemaps / lightmaps) would benefit from it.

Yep, asset pipeline is my case.

> Though on second thoughts, an asset pipeline could also invoke an external DDS compression tool (e.g. from PNG), in which case Urho would not need the implementation inside it.

Exactly! And the main benefit of using DDS instead of other format is that you don't need to change file name and compress images insensibly for engine.

I think I could implement some simple DDS serialization that works only with uncompressed images. And then it could be improved if needed.

There is also pretty good library **squash** that provide image compression but I think Urho3D don't need this.
