### ISSUE TITLE
Possible ScreenToWorldPoint bug

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1504]
I have function for projection cursor to plane:

```
    Vector3 CursorToPlaneXZ()
    {
        auto mousePos = INPUT->GetMousePosition();
        auto camera = cameraNode_->GetComponent<Camera>();
        float x = (float)mousePos.x_ / GRAPHICS->GetWidth();
        float y = (float)mousePos.y_ / GRAPHICS->GetHeight();
        auto cameraRay = camera->GetScreenRay(x, y);
        float dist = cameraRay.HitDistance(Plane(Vector3::UP, Vector3::ZERO));
        Vector3 result = camera->ScreenToWorldPoint(Vector3(x, y, dist));
        DEBUG_HUD->SetAppStats("Y", result.y_);
        // Fix precision error.
        result.y_ = 0.0f;
        return result;
    }
```

ScreenToWorldPoint should return Vector3 with y == 0. But this is not the case. At first I thought it was an error of precision of calculations. But the error is too large (Y = -3.6 in corners of the screen).

Test files: https://github.com/1vanK/PuddleSimulator
Press F2 for open DebugHud and click LMB.

**Comment by cadaver** [comment]
The distance (Z coordinate) that ScreenToWorldPoint expects is along the view Z axis. When you point to corners of the screen the camera ray is no longer aligned along the Z axis. 

In this case once you have the ray hit distance you could simply calculate the hit world position from the ray's origin + direction * hitDistance.

The typical usecase for ScreenToWorldPoint() would be when you want to find a screen point's world counterpart at a fixed distance.

Though I'll have to review the math in any case, because there's use of camera nearclip which strictly shouldn't be needed when working with the camera view matrix.

**Comment by 1vanK** [comment]
Yes, "Vector3 result = cameraRay.origin_ + cameraRay.direction_ * dist;" works perfect. Thank you!
