### ISSUE TITLE
Make PBR demo work on iOS

### ISSUE THREAD

**Issue by smb-z** [urho3d/Urho3D#1545]
Set of several issues:
1. PBRMaterial demo for iOS doesn't copy Autoload asset, so no PBR materials can be loaded by demo.
2. BRDF.glsl compile error at:
#116:         float lightScatter = f0 + (fd90 - f0) \* pow(1.0f - NdotL, 5.0f);
#117:         float viewScatter = f0 + (fd90 - f0) \* pow(1.0f - NdotV, 5.0f);

"f" is unexpected. If I delete "f" suffix, shader can be compiled.
3. PBR don't work as expected:

![img_0476](https://cloud.githubusercontent.com/assets/9615945/18031012/0e17288e-6cde-11e6-8d8e-7a368706b0a6.PNG)

![img_0472](https://cloud.githubusercontent.com/assets/9615945/18031015/3bb5449c-6cde-11e6-86c6-7e0d7399c0f8.PNG)

**Comment by MonkeyFirst** [comment]
It's seams iOS have more pedant glsl-compiler ) because the using of ".f" it's not provided by glsl specs

**Comment by cadaver** [comment]
The shader bugs will be good to fix. I remember having trouble with the IBL image being just black on GLES, didn't investigate closer. Will not promise that this will be completely fixed.

**Comment by dragonCASTjosh** [comment]
The texture sampling used within the IBL is what epic use as there mobile approach so it should be capable of running on mobile platforms

**Comment by sabotage3d** [comment]
I think epic are using ES 3.0 if I am not mistaken.

**Comment by dragonCASTjosh** [comment]
Yea i think they are, witch may cause problems for getting it working on prior ES versions without extensions.

**Comment by cadaver** [comment]
My Android phone refused to use the extension when I tried.

**Comment by dragonCASTjosh** [comment]
We may have to hold of on PBR for mobile until we find time and resources to bring ES3 into urho

**Comment by smb-z** [comment]
>cadaver: My Android phone refused to use the extension when I tried.
Here's Google stats on OpenGL ES suport: https://developer.android.com/about/dashboards/index.html#OpenGL
So ES 3.0+ is supported only by 54% devices. That's why it seems userful to support PBR on ES2 devices even maybe with some restrictions.

>dragonCASTjosh: We may have to hold of on PBR for mobile until we find time and resources to bring ES3 into urho.
Do you know what restriction of ES 2 doesn't allow PBR to be applied?

My point is that while Urho3D claims itself as cross-platform (which is really cool feature, I choose Urho3D mostly because of that), maybe it should support core features (PBR is one of them I think) on most supported platforms, even with some restrictions.

Later I can look into PBR demo on Android/IOS to investigate reasons why it doesn't look same as on desktop.

**Comment by cadaver** [comment]
Note that PBR is a rather new feature in the timeline of whole Urho3D. Also, it's just a set of shaders and materials, which I wouldn't necessarily call "core". However I do agree that within limitations the built-in shaders should make their best effort to work on all platforms, except where clearly impossible, for example deferred rendering is a no-go on GLES2, due to no multiple render target support (and in practice, lacking performance)

**Comment by dragonCASTjosh** [comment]
I believe Cadaver mentioned above the sampling the IBL using mip levels is not supported. It also looked like other issues are at part play with the BRDF that would cause a lot of issues to fix due to it being perfect results on pc, we would likely have to write a mobile specific path

**Comment by dragonCASTjosh** [comment]
Also I don't think PBR will be core until it becomes the default

**Comment by sabotage3d** [comment]
There are simplification on mobile that can be assumed like using a specific mip level for IBL and a simplified BRD approximation model. I have seen quite terrible performance from Unity's PBR shaders even on latest generation phones on simple games.

**Comment by dragonCASTjosh** [comment]
The problem with the BRDF is its as simplified as possible already, the Lambert defause factor is about as simple as possible. GGX is about as fast as Blinn in most cases. And everything else is stupidly simplified. The IBL itself can take further improvements but the problem comes with sampling mips, and R&D into new approches

**Comment by JSandusky** [comment]
There's no real "definite win" for PBR on iOS or Android.

A work-around for the IBL mip sampling would be to use spherical harmonics (based on the zone cubemap) and lerp/mix between the cube sample and SH values. Cubical environment mapping (6 colors, mapped like a cubemap) would work too.

Here's a gist for an SH class for Urho (from my old lightmapper [it is known to work, but might need updating to new macros]):
https://gist.github.com/JSandusky/4602cdb06ef24c7ac885a02b767c0a64

A big problem there though is that adding SH opens a "Pandora's Floodgate" of wish lists and feature requests and doesn't fall in nicely with how zones are now. Never-mind that SH is generally a PITA to work with (easy to botch addition/extraction vectors, not intuitive, etc).

Cubemaps fit reasonably nicely with zones at the time, it was a hack, but it wasn't a completely atrocious one. SH is basically an overhaul, messes with existing gradient features and in the best case introduces some ambiguities such as "I have this zone without a cubemap, but it borders a zone with a cubemap, how do I build my SH?"

Even if cubical environment mapping is subpar, I think I'd favor that since it falls in line better with Urho3D's zones as they are. It'd be a much more natural replacement of the existing zone color gradient. Giving each of a zone's faces a color is reasonable for legacy style shading and could fit well with zone cube map baking.

**Comment by boberfly** [comment]
I've still got an ES3.0 branch lying around here if anyone wants to take a peek. The Graphics subsystem has changed quite a bit by the looks of it since I did the port in December though. I was also toying with using pixel local storage http://malideveloper.arm.com/resources/sample-code/shader-pixel-local-storage/ to do deferred/prepass but I didn't have a very nice test/debug cycle experience to truly get it to work though because the Android SDK/NDK debugger was absolute balls for ES3.0 and my Galaxy S6...

**Comment by c4augustus** [comment]
I've just slammed into this because I now need to use PBR and IBL in my Android app to match what the iOS app is doing using SceneKit--for which those developers are using PBR and IBL for all the content. BTW, I've been running Urho in ES 3.0 on Android for a while now, but I have the advantage of only needing to support Android 5.0+ and phones of the S6 generation and beyond. Wish me luck.

**Comment by c4augustus** [comment]
I needed to fix the "f" suffix in the shaders and also make sure that all float literals are decimal numbers as using integer literals causes compilation failure in GLES3 on Android. It renders PBR now, but the IBL is definitely not correct. I'm going to try to fix it.

**Comment by JSandusky** [comment]
> I needed to fix the "f" suffix in the shaders and also make sure that all float literals are decimal numbers

That's an extension thing that's always on for anything that supports core GL4.0+. The suffix really shouldn't be there and it's meaningless. With GL4.0+ being a ridiculous percentage of PCs that was never caught but it should error on anything less (it's part of the *datatype* group of extensions so one does not simply turn it off).

> It renders PBR now, but the IBL is definitely not correct. I'm going to try to fix it.

Screenshot of the incorrectness? (a not totally borked photo of the phone screen will work) Watch out for that **#ifndef GL_ES** in shaders depending on how you handled passing the target defines.

**Comment by c4augustus** [comment]
The current problem for me is the IBL.glsl call to FixCubeLookup(...). With this call, the reflection sampling is wrong, at least on the MacOS desktop (I'm still working to get ES 3.0 shader code compiling on Android). Disabling that call fixes at least this much of the problem. Here are screenshots for rendering on Mac, the model is inside a test cube map with different colored sides. The current code that calls FixCubeLookup(...) looks incorrect:
<img width="547" alt="screen shot 2018-03-04 at 17 36 55" src="https://user-images.githubusercontent.com/5049680/36952284-5dc7f774-1fd3-11e8-9a55-bcc8412d4be7.png">
Removing the call to FixCubeLookup(...) looks correct: 
<img width="540" alt="screen shot 2018-03-04 at 17 35 14" src="https://user-images.githubusercontent.com/5049680/36952286-6922e110-1fd3-11e8-81fa-afd16735664d.png">

**Comment by JSandusky** [comment]
That's probably because it has a hardcoded face-scale of 1024x1024 - if your cube uses a different size it'll be all wrong.

ES3 can filter cubemaps across seams so it's unnecessary to use FixCubeLookup (it appears to be from the witness blog on cube seams), you can #ifdef around it if you've added a preprocessor def for GL_ES3 or what not.

**Comment by c4augustus** [comment]
Ah, okay, thanks. I'm still getting GLES3 compatibility established in the shaders themselves. My overall goal is to match the PBR and IBL results from the equivalent scene running in iOS using SceneKit. So far, I have to change the "metalness" and roughness settings to get comparable results. For example, one SceneKit material with metalness 0.4 roughness 0.4 is more closely matched using metallic 0.3 roughness 0.6 in Urho3D. Of course SceneKit is rendering using Metal rather than GLES and Apple's source code is not available AFAIK.

**Comment by c4augustus** [comment]
Okay, I've got PBR and IBL working on Android using GLES3 and the results match the MacOS desktop. To support GLES3 properly we'll need to get Urho3D's SDL upgraded to a newer version that provides GLES3 headers, but right now for my own purposes I've been able to get it working with just this: https://github.com/c4augustus/Urho3D/commit/14179f97126c26a421304027a23d3adbe795104a
