### ISSUE TITLE
Possibility to choose max anisotropy samples per textures

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1563]
Hello ! 

Would it be possible to be able to choose max anisotropy samples count on textures ? 

This would be very usefull for terrains ! Setting anisotropy samples to 8 or even more with 16 cause a massive framerate drops (more than 10 FPS drop) when the terrain is rendered on the screen. I guess that this is because the terrain is a big surface to process for the GPU. 

I have tried to force trilinear filtering on terrain texture and it solve the performance issue. Even if other meshes textures are anisotropic filtered there is only 2 FPS drop at worse.

The good thing would be to be able to set for example a maximum of 2 samples of anisotropic filtering on the terrain texture as trilinear filtering make the terrain quite blurry :)

Tested on DX11 desktop build with a Nvidia GTX 760.

**Comment by cadaver** [comment]
Yes, this is possible because the Graphics class is just currently making an intentional simplification. But in reality it's a per-sampler setting. Probably would make it so that in a texture, anisotropy level 0 (or other illegal value) means to use the default from Graphics.

**Comment by OldSnake22** [comment]
Nice :) Do you think you can make it or do you want me to take a try for this "feature" ?

**Comment by cadaver** [comment]
If you want it done faster you can take a shot at it yourself, otherwise I won't make other promises than that I'll eventually get around to doing it.

It just needs to take care of the situation where the default is changed in Graphics class, in that case it should loop over all textures that are using the setting. Also, D3D9 implementation is quite different from OpenGL & D3D11.

**Comment by OldSnake22** [comment]
I will wait then ! it is safer... :)
