### ISSUE TITLE
Navigation does not work when DynamicNavigationMesh created after CrowdManager (for example in Editor)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1565]
I'm not sure that it's a bug. If it is intentionally, we can add note to https://urho3d.github.io/documentation/1.6/_navigation.html

**Comment by cadaver** [comment]
It's sort of not what you'd expect. Currently we have rules like "physicsworld is automatically created" but we shouldn't create a navigation mesh automatically, since it's not obvious where it should go (not necessarily scene root). I feel the proper operation would be for CrowdManager to keep listening to component additions until it can find a navigation mesh.

**Comment by 1vanK** [comment]
Nice!
