### ISSUE TITLE
CrownManager does not works after deleting Obstacle component

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1571]
Way for reproduce:

39_CrowdNavigation.as

```
Node@ jackNode;

void SpawnJack(const Vector3& pos, Node@ jackGroup)
{
    jackNode = jackGroup.CreateChild("Jack");
    ...
    Obstacle@ obstacle = jackNode.CreateComponent("Obstacle");
}
```

```
void SetPathPoint(bool spawning)
{
    Vector3 hitPos;
    Drawable@ hitDrawable;

    // Added
    Obstacle@ obs = jackNode.GetComponent("Obstacle");
    if (obs !is null)
        obs.Remove();
```

**Comment by cadaver** [comment]
I tested by creating an obstacle to all subsequent Jacks after the first one, and indeed the agent will not navigate even after removing the obstacle. Looks like the agent fails to be added, because it's inside an obstacle. Toggling the node enabled/disabled state after removing the obstacle component allowed the agent to navigate, because of being re-added after the situation is now valid.

IMO it looks like an error to purposefully create an agent inside an obstacle.

**Comment by 1vanK** [comment]
Hm, in my code https://github.com/urho3d/Urho3D/issues/1570 I remove agent before adding obstacle and remove obstacle before adding agent

**Comment by cadaver** [comment]
It might go wrong because if you remember, obstacles are not necessarily immediately updated, but by emptying the "update queue" on each frame, so it may be that the obstacle is still in place in the Detour library even though the obstacle component is removed.

However I tested the following code to turn agents into obstacles and vice-versa, and that didn't cause problems, at least not with a small number of agents:

```
void AddOrRemoveObject()
{
    // Raycast and check if we hit a mushroom node. If yes, remove it, if no, create a new one
    Vector3 hitPos;
    Drawable@ hitDrawable;

    if (Raycast(250.0f, hitPos, hitDrawable))
    {
        Node@ hitNode = hitDrawable.node;

        // Note that navmesh rebuild happens when the Obstacle component is removed
        if (hitNode.name == "Mushroom")
            hitNode.Remove();
        else if (hitNode.name == "Jack")
        {
            if (hitNode.GetComponent("Obstacle") !is null)
            {
                hitNode.RemoveComponent("Obstacle");
                CrowdAgent@ agent = hitNode.CreateComponent("CrowdAgent");
                agent.height = 2.0f;
                agent.maxSpeed = 3.0f;
                agent.maxAccel = 3.0f;
            }
            else
            {
                hitNode.RemoveComponent("CrowdAgent");
                Obstacle@ obstacle = hitNode.CreateComponent("Obstacle");
                obstacle.radius = 0.5f;
                obstacle.height = 2.0f;
            }
        }
        else
            CreateMushroom(hitPos);
    }
}
```

**Comment by 1vanK** [comment]
AddOrRemoveObject() executed in HandleUpdate(), my code in HandlePostUpdate (after navmesh actions), may be it is reason?

**Comment by 1vanK** [comment]
I change postupdate to update in my code, no any difference. I can give my code if it needent (but it is very dirty xD )

**Comment by 1vanK** [comment]
Yes, adding
```
            node_->SetEnabled(false);
            node_->SetEnabled(true);
```
helps my

**Comment by 1vanK** [comment]
Anyway turn agents into obstacles and vice-versa cause discontinuous change of chracter's coords sometimes, so I will find another way to deprecate monster to push character

**Comment by 1vanK** [comment]
Agent still move with constant speed after 
```
        CrowdAgent* agent = node_->GetComponent<CrowdAgent>();
        agent->ResetTarget();
```

**Comment by slapin** [comment]
I have the same problem with my code. I see this problem was resolved but I don't understand how. Could you please write what you did so the problem go away? Please share a piece...
