### ISSUE TITLE
How to get all Image mip levels?

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1573]
I have manually created Image and I don't know whether it has mipmap levels or not.
How can I get actual number of levels?

**Comment by cadaver** [comment]
Images only have real mip levels if they have been loaded from a compressed container format like DDS. If you created an image yourself with SetSize() / SetData() it doesn't have mip levels, instead they're created on demand with bilinear resize.

At the moment the Image class doesn't support creating compressed content at runtime.

**Comment by eugeneko** [comment]
> it doesn't have mip levels
What if I used PrecomputeMipLevels and then _changed_ these levels' images?

**Comment by cadaver** [comment]
PrecomputeMipLevels() will bug if you change the image data, so don't call it. Use the utility function Texture::CheckMaxLevels() to calculate how many levels there are until you reach 1x1, or calculate it manually.

The Image class could be cleaned up, but since it works for the main purpose it's used in the engine (loading existing images) it's not a priority. Pull request to improve it would be accepted, as usual.

**Comment by cadaver** [comment]
You could also add the maximum amount of mip levels to write as a parameter, to make it possible to intentionally save e.g. just 1 level.

**Comment by eugeneko** [comment]
It looks like the main purpose of Image is to be helper class between file and texture.
As far as PrecalculateLevels() is exposed in public interface, I'm going to add some utility functions:

`void GetLevels(PODVector<Image*>& levels)` that returns all levels of image including `this`
`void CleanLevels()` just for symmetry.
