### ISSUE TITLE
MSVC detects a lot of memory leaks in Editor

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1582]
MSVC 2015 Update 3 detects a lot of small memory leaks if I try to run Editor in Urho3D player. Demos are leak-free both executables and scripts, even script integration demos. Most leaks are located in Str.cpp(431).

Have you tested Urho for memory leaks? Are these leaks real or just side effect of some static variables?

**Comment by weitjong** [comment]
I don't know about others but I have performed a limited tests some time ago using Valgrind on Linux. It has helped me to find an uninitialized variable which caused a mysterious intermittent crash in one of our demo app in AppVeyor CI. I was not able to find any memory leak that I should be concerned of at the time. Valgrind did detect some "potentially leaking" memory blocks in the "still reachable" category,  if my memory serves me right. In theory,  since we still have pointers to those blocks, they might be freed when the engine/app is exiting. Not sure though whether we are seeing the same thing.

**Comment by cadaver** [comment]
I have seen the memory leak in Editor and not elsewhere. My belief is that it's some complex AngelScript structures that contain strings and that don't get freed correctly even when the editor's scripts are unloaded at exit.

**Comment by eugeneko** [comment]
@cadaver I've found STR:

```
class MrLeaker
{
    int value;

    MrLeaker(int value_)
    {
        value = value_;
    }
}

void leaktest()
{
	MrLeaker@ mainLeaker;
	Dictionary leakerDict;
	
	mainLeaker = MrLeaker(0);
	leakerDict.Set("", @mainLeaker);

	MrLeaker@ leaker;
	leakerDict.Get("", @leaker);
}
```

I'll continue investigation but I'm unfamiliar with AS so I hope you will look at this.

**Comment by eugeneko** [comment]
Does CScriptDictValue need copy-ctor?
