### ISSUE TITLE
Load model from resources NOT in asset folder

### ISSUE THREAD

**Issue by Fax3D** [urho3d/Urho3D#1584]
Hi,

About Urhosharp and Xamarin.Forms, i think it should be possible to load a 3D model (or any other type of resource) from outside the Asset folder, for example from SD Card or from a file stream taken from internet... 
This could be a very useful features for creating application that dont' rely only on pre-packaged resources, but need to use a more dynamic way to visualize 3D objects.

Thanks.

**Comment by cadaver** [comment]
The ResourceCache operates on packages and paths that have been registered as resource paths.

However you are free to "new" a model resource and load it from any Deserializer stream, that can point to an absolute filename anywhere in the filesystem. Or that's at least how it works on the C++ side. 

Note that this project itself does not / cannot give support to C# specific issues, for that you should use the Urhosharp project's issue tracker.

**Comment by cadaver** [comment]
Tested that it even works through the ResourceCache, as it will fall back to absolute path if the resource isn't found otherwise. AngelScript example: (where the path in question is not registered as a resource path)
´´´
mushroomObject.model = cache.GetResource("Model", "D:\\Stuff\\UrhoScene2\\Models\\minigun.mdl");
´´´

**Comment by Fax3D** [comment]
Thanks very much @cadaver, it works even in Urhosharp!
