### ISSUE TITLE
Make Urho3DPlayer.h/cpp re-usable.

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1590]
I think that (almost) anybody who use Urho as external library needs some kind of player to run Editor.
Let's make Urho3DPlayer re-usable because it is pretty convinient to use it as base class.

PS: It could be even made a part of Urho library..

**Comment by cadaver** [comment]
It's a good idea, but note that Urho3DPlayer is complex due to including AS / Lua support, mobile / emscripten command line support, instructions, script reloading.

When you already have a working Urho executable which initializes the engine, and don't need to handle special cases, getting the editor running is just a few lines of code. Also some might want to tie it into their main executable and for example break into the editor with just a keypress, so I suppose it's hard to make Urho3DPlayer universally applicable, while the actual act of running the editor within Urho is simple.

**Comment by eugeneko** [comment]
My global idea is to make Urho3D Player and Editor as reusable as possible without changing original Urho code. I'll write more when I will start work on it but this issue is the first step.
