### ISSUE TITLE
Condition that works, but seems bogus

### ISSUE THREAD

**Issue by smb-z** [urho3d/Urho3D#1591]
File:  Urho3D/Source/Urho3D/Graphics/Renderer.cpp
Line: 680

`for (unsigned i = viewports_.Size() - 1; i < viewports_.Size(); --i)`

This loop works properly, e.g. if viewports_.Size() is 3, i will iterate through [2 1 0].
But obviously condition `i < viewports_.Size()` works only because `--0==UINT_MAX`
Was `i>=0`  condition assumed here?

**Comment by weitjong** [comment]
The datatype is an unsigned integer. I also asked the same question when I
first reviewing the project code and quickly get accustomed to this idiom :)

Sent from my Galaxy Tab 3

On Sep 16, 2016 8:09 AM, "smb-z" <notifications@github.com> wrote:

File: Urho3D/Source/Urho3D/Graphics/Renderer.cpp
Line: 680

for (unsigned i = viewports_.Size() - 1; i < viewports_.Size(); --i)

This loop works properly, e.g. if viewports_.Size() is 3, i will iterate
through [2 1 0].
But obviously condition i < viewports_.Size() works only because
--0==UINT_MAX
Was i>=0 condition assumed here?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/urho3d/Urho3D/issues/1591>, or mute the thread

**Comment by smb-z** [comment]
I see. Found similar code in other modules, so I guess it was intended. Ok, let it be :)

**Comment by cadaver** [comment]
Yes, intended, often in cases where something is going to be removed from the vector.
