### ISSUE TITLE
Web demo for PBR

### ISSUE THREAD

**Issue by dragonCASTjosh** [urho3d/Urho3D#1597]
I noticed that PBR does not have a web demo available on the website. So i was wondering if there is anything specific preventing it from running on web or if its a sample you just dont feel should have a web version.

**Comment by cadaver** [comment]
If I remember right, the CI build chokes on the amount of asset data and cannot complete in time, that's why we did the separation to the LargeData folder.

**Comment by dragonCASTjosh** [comment]
Maybe it could be worth finding a solution that allows CI to build the PBR demo and any later advanced graphics demos

**Comment by danhambleton** [comment]
So, I've been trying to get PBR working on GLES for some time. So far, I get a black screen when running a web build with the PBRDeferred render path. Any thoughts?

Would really really love to get it working on the web!

**Comment by dragonCASTjosh** [comment]
I'd recommend running forward.xml as that's where I put my lost work. Also ensure that the LargeData folder as I believe it's called is include in the build

**Comment by danhambleton** [comment]
Do you mean using the Forward.xml Renderpath and then just using the PBR materials/techniques/shaders?

It doesn't look like Forward.xml has been updated in a while (2 years as far as I can see). Am I getting that right?

**Comment by danhambleton** [comment]
Also, I just naively tested setting the renderpath to Forward.xml and applying the PBR materials. No go (i.e. model disappears).

**Comment by dragonCASTjosh** [comment]
forward.xml allows you to use both PBR and None PBR materials. and it really does sound like the large deta assets are missing

**Comment by danhambleton** [comment]
Hey, I must be missing something....Here are two screenshots: The first one is from a desktop build.

![win_forward](https://cloud.githubusercontent.com/assets/1939589/20351580/71283d86-abe1-11e6-9d21-d28607bde910.PNG)

And the second is from a Web build:

![web_forward](https://cloud.githubusercontent.com/assets/1939589/20351549/57f581b6-abe1-11e6-80a4-2c2314a251f2.PNG)

Everything else in the scene is identical...

**Comment by dragonCASTjosh** [comment]
hmm not sure whats up with the forward render path there as both desktop and web should take the same path for the most part and the parts the vary happen the same for deferred and forward

**Comment by danhambleton** [comment]
In the PBRDeferred renderpath, there are a bunch of custom render targets, PS Defines, commands, etc... But the forward render path looks very different. Do I need to alter anything in there?

**Comment by dragonCASTjosh** [comment]
nope as the materials handle the defines in forward

**Comment by JSandusky** [comment]
I know this is old, but console errors? I have a hard time believing that GLES2 will actually fit all of the information into register for the forward shaded deferred paths (as far as it is concerned ... it cares more about API level than actual hardware, which is why GLES gets so much misguided hate). 

This level of perfect black is indicating a pixel shader crash, it's absolute 0,0,0 everywhere in the problem region using the eyedropper.

I'd approach this by commenting out large blocks of things out from the shaders used on the object until you arrive at something that works, then gradually reintroduce those until you can nail down the culprit. This is the situation where resource hotloading really matters.
