### ISSUE TITLE
Urho3D cause "Out of memory" exception when try load scene with incorrect model

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1600]
Test files http://virealism.com/LostCoast.7z
It is not my scene, from http://www.gamedev.ru/community/urho3d/forum/?id=217746&page=29#m434

Scene Data\scenes\coast.xml
```
  <node id="4">
    <component type="StaticModel" id="5" />
    <component type="RigidBody" id="6" />
    <component type="CollisionShape" id="7">
      <attribute name="Shape Type" value="TriangleMesh" />
      <attribute name="Model" value="Model;Models/coast.mdl" /> // ERROR
    </component>
  </node>
```

It is strange, but original urhosharp demo (from archive) load this scene succeful.

**Comment by cadaver** [comment]
Coast.mdl is just 8 bytes, which is not enough data even for an empty model.
Going to close this as wontfix, because completely safeguarding against arbitrary corrupted model data is going to be very hard, since you have to consider "valid" but too large values which lead to out of memory error in practice. Contributions are welcome though.
