### ISSUE TITLE
How to draw lines in Urho3D's UI Window

### ISSUE THREAD

**Issue by lvshiling** [urho3d/Urho3D#1619]

**Comment by cadaver** [comment]
If you mean debug drawing like DebugRenderer, there isn't an API for that. The UI elements are based around drawing quads. You could make custom UI elements though, which can define freeform UI geometry (batches) to render.

**Comment by lvshiling** [comment]
Could the engine can provide standard interface api?

**Comment by cadaver** [comment]
Take a look at these forum threads:
http://urho3d.prophpbb.com/post12898.html
http://urho3d.prophpbb.com/topic2152.html

When we're talking about 3D debug geometry, it's quite standard to have functions for line, bounding box etc. These are often ugly, and it doesn't matter that they are ugly. However when we're talking of UI and the various aesthetics and purposes the author may want for it, it's IMO better that you write custom elements with custom geometry rather than using pre-provided functions. Also, so far nothing in the built-in elements has required anything else than textured quads.

**Comment by lvshiling** [comment]
Actually I want to make a curved line editor by UI subsystem.

**Comment by cadaver** [comment]
For the Urho project, it's also a matter of not trying to over-reach, at least with the current active developers. That said I'd have nothing against a well-done contribution that adds geometric shape drawing, or even a complete node graph editor to the UI, but it's not a personal focus or interest for me.
