### ISSUE TITLE
Soft Particles Support

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1623]
This is a feature request for soft particles. A very basic feature to have in any modern engine now.

**Comment by cadaver** [comment]
The building blocks are already there; there are renderpaths that write depth (also forward), you just need to write a suitable shader that compares the scene depth to particle depth.

Your mileage in relation to other contributors may vary, but personally I'm by this point uninterested in making Urho measure up to a "modern engine" at least when it comes to having various effects out of the box, because there's always something that it's going to miss, and time is limited. I'm more interested in making sure the engine doesn't have missing pieces at the code-level that prevents you from realizing the effects you want.

**Comment by OldSnake22** [comment]
> I'm more interested in making sure the engine doesn't have missing pieces at the code-level that prevents you from realizing the effects you want.

And this is perfect ! :) 

Will try to add this soon and share my implementation if i succeed.

**Comment by 1vanK** [comment]
My be it will help you https://github.com/1vanK/Urho3DSoftParticles :)

**Comment by eugeneko** [comment]
> I'm by this point uninterested in making Urho measure up to a "modern engine" at least when it comes to having various effects out of the box, because there's always something that it's going to miss

But you've merged ribbon trail. However, it looks like 'just another effect out of the box' from my point of view.

>I'm more interested in making sure the engine doesn't have missing pieces at the code-level that prevents you from realizing the effects you want.

It's great that you support contributors in this activity.

**Comment by cadaver** [comment]
I have nothing against merging a well-done feature that hasn't caveats. Ribbon trail is just an own Drawable subclass that has no requirement for the render path or shaders. Soft particles is trickier because it requires a readable depth buffer, which you can't reasonably have on mobiles, and is not something you want to enable by default.

When you work for your own project you can be quite specific how you construct your renderpath & shaders. You usually make a choice of either deferred or forward and stick to it. Meanwhile, offering effects in Urho by default is always harder because it should try to cater to all possibilities. 

It's for the same reason why it's easier to provide some code or effect snippet on the Showcase forum, than to make a PR of it.

**Comment by cadaver** [comment]
An actual engine-level feature which could be useful for this (and potentially other scenarios) would be to allow the "scenepass" command to set additional shader defines. In that case a soft particles renderpath could optionally enable the soft mode in particle shaders, and @1vanK's work could be merged in a simplified manner. The same way, linear & hardware (reconstructible) depth could be handled with ifdefs in the same shader.

**Comment by OldSnake22** [comment]
That would be great to add such system yes.

@1vanK Thank you i will take a look !

**Comment by 1vanK** [comment]
@OldSnake22 keep in mind, there are two different implementation: in Data (by MonkeyFirst) and in MyData (my)

**Comment by ucupumar** [comment]
@cadaver do you mean if that's implemented we can just call scene pass in the shader? If so, I can think of many effects that will be easier to merge like motion blur and ssao.

**Comment by cadaver** [comment]
You mean that if there's a specifically named sampler in the shader, a buffer texture matching its name would be bound automatically? It would be convenient, but it'd be likely worse for performance, because the auto-bindings would have to be inspected each time shaders are changed during a render pass. Now, when the pass-global textures are set from the renderpath when the pass begins, it only needs to be done once.

**Comment by cadaver** [comment]
The support for renderpath scene passes being allowed to define their additional shader defines is now in.

**Comment by OldSnake22** [comment]
Thank you this is a usefull feature

**Comment by 1vanK** [comment]
Renderpath: Forward.xml
Scene: Plane with "Smoke.xml" material + Box (without light)

![2](https://cloud.githubusercontent.com/assets/13021826/19797583/bd7e49e2-9cf4-11e6-94d2-efc022e7bed4.png)

Scene: Plane with Smoke.xml material + Box + Point Light

![2 -](https://cloud.githubusercontent.com/assets/13021826/19797594/d0797418-9cf4-11e6-9062-03bc9e19f6ab.png)

**Comment by cadaver** [comment]
Let's check. In theory the unlit smoke should behave just like before, the shader just added the soft particle option, but apparently not.

**Comment by cadaver** [comment]
Previously the Smoke material was using DiffVColUnlitAlpha technique. This is just the same as currently, except with a different shader. You shouldn't use it with models that don't have vertex colors (such as the default plane), since the result is undefined.

**Comment by 1vanK** [comment]
Hm, it is strange, but I do not see issue in old version

![2](https://cloud.githubusercontent.com/assets/13021826/19798174/286a27e6-9cf8-11e6-9d4a-f97f6211d417.png)

**Comment by 1vanK** [comment]
Anyway, may be make default primitives more unifersal? (add white colors to vertices)

**Comment by cadaver** [comment]
I guess it just happens to work. On D3D11 you would get an input layout error.

**Comment by cadaver** [comment]
Anyway, you're (or anyone else) are welcome to add vertex colors and re-export. The blend files are in the SourceAssets directory. I'm rather poor in my Blender skills so I wouldn't know how to add. Though you will note that the smoke will look rather poor with white vertices, but I agree that white would be the "most universal" default.

**Comment by 1vanK** [comment]
I modify my demo, and when SoftParticleFadeScale < 1.0

![2](https://cloud.githubusercontent.com/assets/13021826/19799287/896029a0-9cfe-11e6-809d-fa9231d83e6d.png)
```
<material>
    <technique name="Techniques/DiffUnlitParticleAlpha.xml" />
    <texture unit="diffuse" name="Textures/Smoke.dds" />
    <parameter name="SoftParticleFadeScale" value="0.1" />
</material>
```

**Comment by cadaver** [comment]
What renderpath and rendering API?

I notice at least

**Comment by 1vanK** [comment]
Opengl 3,
RenderPaths/ForwardDepthSP.xml

Modified Main.as
https://gist.github.com/1vanK/c3dad27ab871e1ae3b56369aee6f7b8f

**Comment by cadaver** [comment]
FadeScale below 1 is expected to behave as it does, as it fades even if the geometry is stupidly far away. It's a slightly counterintuitive value. In most cases you'd use values above 1. If you want to make the scale behave differently, you can submit PR to the shader.

**Comment by 1vanK** [comment]
> In most cases you'd use values above 1.

It is need for big sprites (single explosion sprite for example)

Screenshot from original demo https://github.com/1vanK/Urho3DSoftParticles

![2](https://cloud.githubusercontent.com/assets/13021826/19800913/a6b40a88-9d05-11e6-8b16-1fd88ce56a5b.png)

Currently (with FadeScale 1):

![2 -](https://cloud.githubusercontent.com/assets/13021826/19801071/4d4a3ac0-9d06-11e6-9f26-945d26c7feee.png)

**Comment by cadaver** [comment]
The way you're not doing the fade if the depth difference is into the other direction likely makes the difference. Should be possible to adapt.

**Comment by cadaver** [comment]
Actually, doing it that way can lead to harsh borders in other cases. Needs testing. You can of course always make your own soft particle shader according to the case at hand.

**Comment by 1vanK** [comment]
My implementation just increase size of particles to geometry direction, but not decrease visble part. Particles ALWAYS has volume, so I think is correct. 

http://blog.wolfire.com/2010/04/Soft-Particles

**Comment by cadaver** [comment]
I'll add a shader compile option to enable the "expanding" mode. Currently the shader kicks in before depth test (shrinking). The advantage in this mode of operation is that you get hardware depth test (faster) and same materials/techniques work either with or without the soft particle testing.

**Comment by 1vanK** [comment]
Cool! Thank you!
