### ISSUE TITLE
cmake_ios.sh fails with Xcode 8 MacOS 10.11

### ISSUE THREAD

**Issue by Kikimora** [urho3d/Urho3D#1628]
This is what I got when build master branch with provided build scripts
```
cmake_ios.sh _build_ios
-- Performing Test HAVE_GCC_SYNC_LOCK_TEST_AND_SET
CMake Error at /usr/local/Cellar/cmake/3.6.0/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.11' but CMAKE_OSX_SYSROOT:

   "iphoneos"

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.0/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  /Users/averbin/Downloads/Urho3D/_build_ios/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)


CMake Error: Internal CMake error, TryCompile configure of cmake failed
-- Configuring incomplete, errors occurred!
See also "/Users/averbin/Downloads/Urho3D/_build_ios/CMakeFiles/CMakeOutput.log".
```

**Comment by cadaver** [comment]
Can verify that I got that one too. Since I was in a hurry and didn't know / remember where to look, I reinstalled XCode 7 to get running.

**Comment by weitjong** [comment]
This issue seems to be similar to a known issue with iOS build tree generation in Travis CI build environment. The difference is that the known issue happened on Xcode7 or 6 too (can't remember now without checking the history). Since I have not encountered the issue locally back then, I thouht it is an anomaly within Travis VM and so we just script the build system to workaround it for Travis CI build environment only.

You try to test if by masquerading as Travis CI by executing the script like so: ```TRAVIS=1 ./cmake_ios.sh my_build_tree``` fixes your issue or not. If the result is positive then we could probably apply the workaround globally.

**Comment by cadaver** [comment]
The TRAVIS=1 workaround lets the CMake go through successfully for me.

**Comment by Kikimora** [comment]
TRAVIS=1 also works for me, thank you!

I found TRAVIS related "if" statement somewhere in cmake files and commented it so that conditional code became unconditional. I think this should be a permanent solution to the issue. 

--
Thanks

Sent from my iPhone

**Comment by cadaver** [comment]
I found the CMake to fail again (for the same reason) in the middle of the build when trying to make the tolua++ utility. For quick testing I just disabled Lua, but if this was made unconditional, it would probably also sort out that?

**Comment by weitjong** [comment]
Yes, it should be.
