### ISSUE TITLE
Possible size issue in VariantValue

### ISSUE THREAD

**Issue by iSLC** [urho3d/Urho3D#1631]
According to the comment above the `VariantValue` the structure should not exceed 16 bytes in size. Which holds true on 32 bit platforms. However, on 64 bit platforms, because each sub union includes a pointer, the size of the structure doubles in size. And the other pointers except the first one `ptr_` are actually never used in code. Actually, even keeping just `ptr_` inside the first union pushes the structure size to 24 bytes on 64 bits. Should be 20 bytes but probably needs to satisfy alignment.

I suppose the entire union could be summed to:
```
union VariantValue
{
    int                 int_[4];
    float               float_[4];
    void *              ptr_; // or ptr_[16 / sizeof(ptr)]?
    bool                bool_;
};
```

Or this way to keep the naming:
```
union VariantValue
{
    struct { int int_, int2_, int3_, int4_; };
    struct { float float_, float2_, float3_, float4_; };
    void * ptr_;
    bool bool_;
};
```

If this was the intended behavior then please ignore this.

EDIT: I just realized that because of this, `float2_` will have an offset of 4 bytes from `float_` and same with `int2_` and `int_`. Which could get in the way of how they're used to represent Vectors, Quaternions etc.

**Comment by cadaver** [comment]
The comment in the code is unclear and does not address a 64-bit build. It's never an issue if VariantValue itself is larger than 16 bytes. On 64-bit builds we actually want the pointers to be there and expand VariantValue to 32 bytes, so that we're able to store a VariantVector or VariantMap inside, which may consist of up to 4 pointers. I'll fix the comment.

**Comment by iSLC** [comment]
In that case, sorry to bother.
