### ISSUE TITLE
Mouse is still locked after engine terminates

### ISSUE THREAD

**Issue by TheComet** [urho3d/Urho3D#1650]
I'm having this strange issue that only occurs when using **fullscreen** mode.

When the engine exits and closes, my mouse pointer is still confined to a 1024x768 box (which is the fullscreen resolution), even though my monitor is 1366x768.

The only way to fix it is to restart X.

This issue occurs on the current HEAD of master (8d76730f5) and I'm running linux gentoo-4.4.21 x86_64

**Comment by cadaver** [comment]
I don't remember seeing this on Linux ever. Probably something related to SDL's interactions with the specific window manager, since I'd assume they should restore sane defaults when the program is terminated and the video mode reset. You could try switching the mouse to visible mode before exiting. If this helps, that could be made default. If it doesn't help, then you're in for some SDL debugging.

**Comment by cadaver** [comment]
Hm, checked the code and it already does SDL_ShowCursor(SDL_TRUE) before closing the window, so there's nothing to add in that regard. But apparently that can still bug if the fullscreen resolution is different.

**Comment by weitjong** [comment]
I observe the exact opposite. Using full screen Editor but with resolution smaller than my native monitor resolution, at exit the mouse returns back to my native monitory resolution. No problem there, however, at runtime the mouse is not confined to the full screen resolution. The screen is filled with garbage/fragment from my desktop if I continue to move my mouse "further right or below" the full screen as if I have a larger virtual screen. I think it is a regression, I don't recall seeing this in the past before we add "-w -s" to the Editor.sh shell/batch script.

For what it's worth, I am using nVidia proprietary driver with my old GTX 580.

**Comment by weitjong** [comment]
Hold on, now I really think about it, I may have been always just run full screen mode in my native monitor resolution in the past. So, please ignore my comment saying that this may be a regression. It may behave like that since day one.  :smile:

**Comment by cadaver** [comment]
@TheComet93 Actually there's one additional thing you could try. In OGLGraphics.cpp around line 2404 where it's closing the window, try forcibly ending window grab:

SDL_SetWindowGrab(window_, SDL_FALSE);

and see whether it helps with your problem.

**Comment by SirNate0** [comment]
I don't know if it's related or not, but when debugging in windowed mode in Ubuntu my mouse is confined to the window when the program hits a breakpoint or seg. fault. Which makes it difficult to interact with the debugger, as I have to click on the terminal window to be able to do anything (typically I accomplish this by moving the window to another desktop and then going back to the one with the terminal, at which point the mouse is stuck against the side of the screen in the height range of the window). I don't know if there is anything that could be done about this, and I wouldn't call it a huge issue since it shouldn't affect any end-users of games.

**Comment by OvermindDL1** [comment]
@SirNate0 This is a standard thing when debugging, the easiest way is just when a breakpoint is hit in GDB is just execute the normal in-game-code mouse ungrab command (you can make a GDB script do it automatically too if you want).
