### ISSUE TITLE
Recognize the DirectX that comes with MinGW-w64

### ISSUE THREAD

**Issue by iSLC** [urho3d/Urho3D#1654]
I've noticed that any recent version of the MinGW-w64 compiler comes with most of the necessary libraries and headers of DirectX. Actually, it comes with a whole lot of other built-in libraries. However the build system does not recognize these headers and libraries. Could it be possible to use these instead of having to install the SDK provided by Mirosoft? I'm mostly interested in DirectX 9.

I've compiled DirectX applications in the past without having to install the SDK. In fact, I didn't even had to explicitly link to the libraries. I'm guessing that MinGW noticed I was including the headers and deduced the libraries automatically.

![Screen](https://s13.postimg.org/nm02i5n07/Untitled.png)

MinGW-w64 6.2.0 x64

EDIT: So far I could get it to work by explicitly setting these variables to something like:

```
DIRECTX_INC_SEARCH_PATHS _:\MinGW\620_64\x86_64-w64-mingw32\include
DIRECTX_LIB_SEARCH_PATHS _:\MinGW\620_64\x86_64-w64-mingw32\lib
```

**Comment by weitjong** [comment]
Our buildsystem uses DirectX header and libraries packaged by the MinGW alright. In order to do so, the buildsystem needs to detect the so-called MINGW_SYSROOT  for a particular MinGW installation. It is this detection that is not bullet proof at the moment. Some of the times it does not detect it automatically and for these cases then one have to supply the MINGW_SYSROOT explicitly. Use DIRECTX_INC_SEARCH_PATHS and DIRECTX_LIB_SEARCH_PATHS only when both these directories are not installed in the default location of MinGW sysroot. Your sysroot (_:\MinGW\620_64\x86_64-w64-mingw32) does have an unusual path. I am not surprised in this case that the auto-detection failed to detect it.

**Comment by iSLC** [comment]
I think they've made some changes to the internal directory structure in the recent MinGW revisions. At least that's what it seemed when I updated them a while ago. I could be wrong.

Does `MINGW_SYSROOT` have to point to the base MinGW folder where the `bin` folder is located or inside the `bin` folder? I've added it explicitly as the former. Or maybe it needs to point somewhere else.

I don't use their installer. I usually download the archive directly and extract it. So I could be lacking some environment variables with the right information.

Off-topic: I usually keep my software on a separate partition and I keep [multiple versions](https://s15.postimg.org/g0mz9yfsb/Untitled.png) of MinGW. Reason why the path could seem a bit off.

**Comment by weitjong** [comment]
It really does not matter how each vendor decided to structure their MinGW packages because in the end the compiler itself must know where those header and library are located. We are using the knowledge of the compiler to auto-detect this system root location. However, in our current approach we still need to parse the output from compiler correctly with a REGEX. It is this part that is hard to get it right for all the cases out there, considering it handles both ANY MinGW installation on BOTH Linux and Windows host systems.

**Comment by weitjong** [comment]
> Does MINGW_SYSROOT have to point to the base MinGW folder where the bin folder is located or inside the bin folder? I've added it explicitly as the former. Or maybe it needs to point somewhere else.

In our buildsystem we expect the MINGW_SYSROOT, when explicitly specified, points to a parent directory containing /usr and /lib subdirs.

I am closing this issue for now as we are already using the DirectX files shipped by MinGW whether via MINGW_SYSROOT hint or being auto-detected.
