### ISSUE TITLE
Any plan to support vulkan?

### ISSUE THREAD

**Issue by kingofoz** [urho3d/Urho3D#1660]
Hi all,
vulkan is becoming more and more popular. I think we'd better have a plan to support it.

Thanks,
Yingjun

**Comment by iSLC** [comment]
I don't think so. This has been discussed over several times if I remember correctly. Basically, you cannot expect to gain anything from Vulkan if you still need to support older APIs. You're either Vulkan all the way or not at all. Otherwise it'll be pointless. At least that's what I think the result of that discussion was. Do some searching, you might find it.

**Comment by eugeneko** [comment]
We already have some discussion in #1201 about this.
Actually, I didn't read it, so don't ask me.

**Comment by kingofoz** [comment]
OK...Thanks.
