### ISSUE TITLE
Bug of DecalSet found at Samples:08_Decals

### ISSUE THREAD

**Issue by morrow1nd** [urho3d/Urho3D#1680]
Build on:
 - Urho3D-1.6
 - Windows10
 - vs2015 x64
 - use c++11

I found this problem when I learn from Samples:08_Decals. After put too many decals on one Node, it showed a surprised phenomenon: When I added a new decal, the initial one disappeared. That would happened after adding about 125 decals to **one Node**. See these pictures. 

![bug_decalsets](https://cloud.githubusercontent.com/assets/20684730/20142000/ed152756-a6cd-11e6-97c6-58a41fe470e0.gif)

![bug_decalsets1](https://cloud.githubusercontent.com/assets/20684730/20142224/da7e8276-a6ce-11e6-9578-4c7f05d41048.gif)

**Comment by OvermindDL1** [comment]
That is by design and something every engine does.  The information for them requires hoisting them into the rendering of the object space, and as such a cap on memory is used.  You can probably adjust it higher if you want though, but as the usual it can cause slowdowns if there are too many.

But yes, look at decals in games, take a popular one like Unreal Tournament (any of them), you can only have so many bullet hole graphics before it starts making the oldest vanish.  ;-)

**Comment by cadaver** [comment]
Not a bug, vertex / index count is intentionally limited, but there are DecalSet functions to change the maximum allocation. See SetMaxVertices(), SetMaxIndices() and SetOptimizeBufferSize().

**Comment by morrow1nd** [comment]
Thanks a lot!
