### ISSUE TITLE
Cannot open console in editor

### ISSUE THREAD

**Issue by zombiegonsdude** [urho3d/Urho3D#1681]
They key down event seems to be firing multiple times for a single key press so anything that uses a toggle is toggled off.

This is happening in the latest commit. I'm building on a linux mint environment.

f1cb469a34c13c56e9d6a9a75c38539cf2de8bd2

**Comment by eugeneko** [comment]
Latest commit don't have engine's code changes.
Have you tested previous commit?

**Comment by weitjong** [comment]
Most probably this is a regression issue from SDL 2.0.5 upgrade.

**Comment by weitjong** [comment]
Confirmed it is reproducible on Fedora too. Can someone test and confirm whether it also happens on other platforms?

**Comment by eugeneko** [comment]
_Cannot_ reproduce descripted defect on Win32+MSVC2013

**Comment by weitjong** [comment]
Thanks for testing it. I have narrowed down the culprit to the below two upstream SDL commits.

- 0e59ffc8023e845090e9244ac085e5893637594d Added support for keyboard repeat (only tested on Windows so far)
- 5d2b7ba68b880da6355648039db6aebf02105318 Fixed key repeat detection on X11, and simplified the code for everyone else

The root cause is this line. https://github.com/urho3d/Urho3D/blob/198adcedece3e3521a2cae541703677550266f3f/Source/ThirdParty/SDL/src/events/SDL_keyboard.c#L693

It seems that at least on Linux platform, the ```repeat ``` is almost always true the second time it is evaluated, no matter how fast you press/unpress the key. i.e. the E_KEYDOWN event after the SDL 2.0.5 upgrade always come in pair in Urho3D. The first one with ```repeat=0``` and the second one with ```repeat=1```, no mater how fast you unpress.

I am a bit hesitate to locally revert back the above two commits in our SDL fork because if we deviate from the upstream then we have to forever maintain the difference on our side. Since Urho3D propagate the ```repeat``` flag from SDL to the E_KEYDOWN event, we could easily change the event handler for E_KEYDOWN to ignore the repeated event if it is undesirable. But all the Urho3D applications need to make this same change if they use E_KEYDOWN event. Both fixes have its own drawback. 

I opt for fixing it in our engine code.

**Comment by cadaver** [comment]
Agreed, fixing in engine input code sounds cleanest.

**Comment by weitjong** [comment]
Reopen as the problem still exists for E_KEYUP event.

**Comment by weitjong** [comment]
I have reverted my above changes because it does not fix the regression issue correctly. There is something else that causing this. I could not reproduce this behavior when testing against unmodified SDL2 directly without using Urho3D. The two commits that I pointed out above was made prior to SDL 2.0.4, so they are not the actual culprit. Back to square one.

**Comment by eugeneko** [comment]
Good luck in digging, @weitjong

**Comment by weitjong** [comment]
Believe it or not, it has something to do with ibus, I have put a TODO item in our modified SDL's CMakeLists.txt for ibus and fcitx support because I don't want to use the original SDL implementation which uses pkg-config tool.  So, the original SDL CMakeLists.txt and ours will auto-configure itself slightly differently at the moment. Temporarily enable ibus support manually in my build fixes the reported issue. However, I still don't fully understand why SDL can behave differently in this case.

**Comment by zombiegonsdude** [comment]
Thanks for tracking down this difficult bug. I installed the **libibus-1.0-dev** package and rebuilt which seems to resolve the issue. That's something pretty deep in the stack causing this issue to happen. I wouldn't think using ibus could impact things in this way. 

Hopefully there will be another way around this. Requiring the dev package for ibus is not very intuitive for making builds. One of the reasons I like urho is the build system is not as complicated as similar projects. I imagine a lot of users wouldn't even have ibus installed for multiple language input as it's not part of the default distributions installation ( linux mint anyway ).

Again thanks, that sounds like a tough bug.

**Comment by weitjong** [comment]
I believe I have nailed it for good this time.

**Comment by zombiegonsdude** [comment]
Removed ibus dev package and did a clean rebuild, appears to be working fine. Thanks again. Much appreciated :)

**Comment by cadaver** [comment]
Excellent!
