### ISSUE TITLE
build failure on Linux - Nov 13, 2016

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#1685]
In file included from /home/o/UDev/Urho3D-1.6-orig/Source/ThirdParty/SDL/src/video/mir/SDL_mirvideo.c:38:0:
/home/o/UDev/Urho3D-1.6-orig/Source/ThirdParty/SDL/src/video/mir/SDL_mirsym.h:55:82: error: unknown type name ‘MirPointerConfinementState’
 SDL_MIR_SYM(void,mir_surface_spec_set_pointer_confinement,(MirSurfaceSpec *spec, MirPointerConfinementState state))
                                                                                  ^
/home/o/UDev/Urho3D-1.6-orig/Source/ThirdParty/SDL/src/video/mir/SDL_mirdyn.h:40:37: note: in definition of macro ‘SDL_MIR_SYM’
     typedef rc (*SDL_DYNMIRFN_##fn) params; \

**Comment by Lumak** [comment]
Based on what I built from downloading the zip file just now.

**Comment by Lumak** [comment]
Oh wait, there was an update on building on Linux page wasn't there? Let me take a look and see if I need to install any new libs.

**Comment by Lumak** [comment]
installed mir-client-platform-mesa-dev and still get errors.

**Comment by weitjong** [comment]
See this commit 474fc17a7e362a393f0db965cef3f6136d5b413f from SDL upstream. For some reason, they added new feature that is only available in Mir 0.24 (which is relatively new, only released in August if I am not wrong). If you are using stable distro like Ubuntu LTS  then your Mir version is probably too old. I am not familiar enough with Mir because Fedora does not have it, so I don't know how to do proper version checking to automatically switch off Mir support in our build system when your system does not have the required version. The devs in the upstream SDL also seems do not perform the proper version check.

**Comment by weitjong** [comment]
At the moment you can switch Mir support off manually by a) do not have any Mir related development packages installed at all in your system; or b) if you want to keep the lower version installed then pass the ```VIDEO_MIR=0``` as one of the build option. See example here.
https://github.com/urho3d/Urho3D/blob/master/.travis.yml#L295

**Comment by Lumak** [comment]
I thought exporting the VIDEO_MIR=0 as an environment variable would do the trick, but nope.

Passing -DVIDEO_MIR=0 did the trick.

Thanks.

**Comment by weitjong** [comment]
Yeah, that what I mean :smile:  If you call cmake directly or use the shell script then prefix the build option by "-D" as always. If you use rake then no need. Our CI (the example I gave you) is using rake.
