### ISSUE TITLE
Bug DynamicNavigationMesh build the scene with objects containing CrowdAgent.

### ISSUE THREAD

**Issue by Commondor** [urho3d/Urho3D#1689]
Hi all,

I found a mistake during construction of DinamicNavigationMesh in a scene loaded objects containing CrowdAgent component. DinamicNavigationMesh builds incorrect navigational grid for objects containing CrowdAgent component.
Who knows the solution to this problem?

Best regards,

**Comment by cadaver** [comment]
How does the scenario differ from 39_CrowdNavigation demo? What other components are in the object containing CrowdAgent?

**Comment by Commondor** [comment]
Steps:
1. Load scene.xml with object containing CrowdAgent component.
2. Build DinamichNavigationMesh.
3. Init CrowdManager
4. Under and over objects that contain CrowdAgent appears navigation mesh for which the object is to jump to the neighboring grid point, and only then begins to move.

![screenshot_thu_nov_17_15_32_19_2016](https://cloud.githubusercontent.com/assets/9081571/20391234/1f4afed6-acdb-11e6-8d23-47a8d631f9c5.png)

**Comment by cadaver** [comment]
This is expected from how the navigation generation works, if you mark the whole scene recursively navigable using a Navigable component at the root. The demo works because the CrowdAgent has AnimatedModel and no Rigidbody. A fix would be to deliberately exclude anything with CrowdAgent from the nav geometry generation.

Btw. you may have trouble when combininng CrowdAgent and physics (Rigidbody) movement, they will both try to control the scene node.

**Comment by Commondor** [comment]
> Btw. you may have trouble when combininng CrowdAgent and physics (Rigidbody) movement, they will both try to control the scene node.

But without physics objects can not communicate with other objects in the scene.

**Comment by Commondor** [comment]
I checked: even if the object of the delete CollisionShape and RigidBody, it is still a navigation mesh is not built correctly.

**Comment by cadaver** [comment]
It's still the StaticModel component which makes the navmesh think of adding it to the navigation mesh. I should be able to test and commit a fix in the near future, by simply testing a StaticModel instead of AnimatedModel in the example 39, and making sure it works properly.

You *can* use a kinematic rigidbody that is able to push other object when moved by the CrowdAgent, but it's assumed to be infinitely heavy, so other objects can never stop or slow down the motion.

**Comment by Commondor** [comment]
I temporary fixed:

`void NavigationMesh::CollectGeometries(Vector<NavigationGeometryInfo>& geometryList, Node* node, HashSet<Node*>& processedNodes,
    bool recursive)
{
    // Make sure nodes are not included twice
    if (processedNodes.Contains(node))
        return;
    // Exclude obstacles from consideration
    if (node->HasComponent<Obstacle>())
        return;
   // Exclude crowdAgents from consideration
   if (node->HasComponent<CrowdAgent>())
		return;
    processedNodes.Insert(node);`
...

Now the grid is generated correctly and objects correctly start moving.

**Comment by Commondor** [comment]
> Btw. you may have trouble when combininng CrowdAgent and physics (Rigidbody) movement, they will both try to control the scene node.

Need move the "Collision Layer" from RigidBody in CollisionShape, remove RigidBody from objects that contain CrowdAgent, then will not be problems between CrowdAgent and RigidBody. ))

**Comment by cadaver** [comment]
Please check if the commit in question fixes the issue. I couldn't verify directly from the CrowdNavigation sample, since it seemed to be working in any case.

**Comment by Commondor** [comment]
Yes, problem solved. Thank you.
