### ISSUE TITLE
Failed to build for android platform

### ISSUE THREAD

**Issue by lhinuz** [urho3d/Urho3D#1690]
......
 error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
     const char *str;
     str = (*mEnv)->GetStringUTFChars(mEnv, filesDir, 0);
 error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
         size_t length = strlen(str) + 1;
......
error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
     jobject assetManager = (*mEnv)->CallObjectMethod(mEnv, context, mid);
......

**Comment by weitjong** [comment]
I suppose the reason why SDL upstream devs do not catch this error themselves because they are already switching to use Android NDK Clang compiler toolchain. As Android NDK has started to remove their support for GCC in its latest version, I think we should start to phase out the support for GCC too in our build system when targeting Android platform.
