### ISSUE TITLE
[Feature Request] Docking system for Editor UI

### ISSUE THREAD

**Issue by SuperWangKai** [urho3d/Urho3D#1715]
I think it would be best if we can have a docking system for the Editor UI.

**Comment by eugeneko** [comment]
Most probably Urho's script editor will never have docking system and other useful things.
The last hope for you is reincarnation of Editor:
http://urho3d.prophpbb.com/topic2523.html

**Comment by JSandusky** [comment]
@eugeneko are you the guy doing a Qt editor? I've exposed most of Urho3D and attributes to Qt already and dealt with the majority of undo/redo nastiness. If you are the guy on a Qt editor, send me an email at jonathan@spruekit.com and I'll shoot you a link with a dump of all my Urho3D related Qt code (I'll be around to comment on why I did things "way X vs way Y"). 

I'm seriously doubting I'll ever have time to finish it up as an Urho3D editor, so I'd at least like to get it sent off somewhere that it might get used. Most of the missing functionality is in the extra editor commands (spline helpers, export OBJ, render cubes, etc), view-splits, and drag-and-drop nodes onto NodeID fields. It does all work however. Right now it's also tightly tied to VS, but since I all GUI is code based that's likely just a minor problem.
