### ISSUE TITLE
CommandLine.txt ignored when packed

### ISSUE THREAD

**Issue by Playermet** [urho3d/Urho3D#1754]
As stated in the title, game not loading anything when I pack all resources to Data.pak and CoreData.pak. But if I create empty folder Data, and copy CommandLine.txt there, all works just as needed. I used precompiled Urho3D-1.6-Windows-64bit-SHARED and Lua as scripting language.

Is this a bug or expected behavior?

**Comment by cadaver** [comment]
This is currently expected behavior, as the CommandLine.txt is read from file system and not resource system. However it shouldn't be impossible to change, as the Web platform is already reading it from resources.

**Comment by cadaver** [comment]
Also, note that just because passing actual command line arguments is enough to make Urho3DPlayer do something else, I certainly wouldn't recommend shipping an actual game with it, but to rather build a custom executable which uses Urho3D and performs exactly the engine setup + script loading you want.
