### ISSUE TITLE
Serializable attributes meta information.

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1766]
Inspired by Unity and #1741
I plan to implement a kind of attribute meta information.

Introduce new (probably virtual) class (e.g. `AttributeMetaInfo`).
Add optional pointer to `AttributeInfo` that specifies attribute meta information.
By design, meta information mustn't be used in Urho core and affect important processes like serialization.
However, it can (and will) be freely used by customers who need some facultative information about attributes.

Examples of meta info:
- Vector information from #1742
- Bitmask view flag
- Realtime apply control (now relatime apply is disabled for some hard-coded attributes)
- (New) Value ranges for numeric attributes and many other things.

I am going to work on it when I publish usable version of my Editor because I am going to use this feature for it. I am __not__ going to add any features to current script Editor.

Opened issue for discussion and as reminder.

**Comment by KonstantinTomashevich** [comment]
Is new class (e.g. `AttributeMetaInfo`) really needed? In my opinion, meta information can be stored to `VariantMap *metaInfo_`, which can be properly added to `AttributeInfo`. Of course, it requires changing destructor of `AttributeInfo`. Enum values and variant values can be stored to this map too. With it, we can easily add another meta information values for Urho3D attributes, such as value ranges and tooltips.

**Comment by eugeneko** [comment]
I am unsure now whether it is enought to just store variant map of attributes because some features may require custom _logic_. It's also non-trivial how to store const char** in Variant - StringVector will need extra conversion.
But just VariantMap as simple universal solution for the first time is ok.

**Comment by JSandusky** [comment]
IMO, the most useful place for meta, and in fact more than meta is in Resource attributes. Some resources are inherently compound (cubemaps, texture arrays, models, etc), it would be extremely handy to have more definition for cases where something is a very specific thing in resource.

Other resources have potential levels of interpretation. Such as SVG, what resolution should be inferred for an SVG resource? That's an excellent place for additional arbitrary property data.

Resources are so full of issues that I really think these need to be filled first before anything else in the attribute related cycle.

> Bitmask view flag

I think this is a GUI and configuration issue, providing options to name what flags are. Naming bits is a big win for usability (can keep the checkbox GUI but have a flyout window with the checkboxes named, and show tooltips for the checkbox matrix).

Urho3D itself can't realistically name lightmask bits.

> (New) Value ranges for numeric attributes and many other things.

This can be done with additions to the existing attribute flags. There aren't really that many valid "clamp" possibilities, most that would appear to be needed are really just some sort of foreign property check (world-bounds, nav-mesh bounds, etc ... and not generalizable).

I roughly modeled another serialization scheme on Urho3D's attributes and had additional traits for:

- SourceID (field is a "source" identifier, serialization neutral [I have to "clone" constantly, and need "sources" to relocate targets for the results of threaded tasks])
- Flags ("enumeration" values are flag bits [enumerations are a special type])
- UNormal_Range (0-1)
- SNormal_Range (-1 - 1)
- Tiny_Increment ('float scroll' operations by 0.01 instead of 1.0)
- Small_Increment ('float scroll' operations by 0.1 instead of 1.0)
- Visual_Consequence (mattered because that means invoking meshing, UV generation, and texture generation - gist is, a change here is a full object change)
- Decompose (matrix requires decomposition in display)
- No_Alpha (color ignores Alpha)
- Ray_Selectable (is something that can be ray selected, used for control points in cages/chains)
     - Assumes a given interface for the IEditable object
- Gizmo (field can have a gizmo activated, property type dependent for what gizmo features are available)
- Local_Space (whatever type attached is in object local space [matrix, vector, quat])
- Scale (just a marker for LocalSpace to differentiate translation and scale)
- etc

> Realtime apply control (now relatime apply is disabled for some hard-coded attributes)

I don't understand this one. Please elaborate.

**Comment by JSandusky** [comment]
Gotcha, thanks for elaborating.
