### ISSUE TITLE
Move SDL_Init() into Context

### ISSUE THREAD

**Issue by TheComet93** [urho3d/Urho3D#1781]
As discussed here: http://discourse.urho3d.io/t/sdl-init-doesnt-get-called-in-headless-mode/2746

Will submit a PR.

**Comment by cadaver** [comment]
Cool! It occurs we don't init Timer at all, but we do our own timing anyway so it's probably not going to hurt. Note some code convention issues, mostly spaces between parentheses, and we don't prefix globals with g_, it's fine to call the variable just sdlInitCounter, especially since it's static and can't be seen anywhere else.
