### ISSUE TITLE
RigidBody2D doesn't preserve b2Body* body_ field on moving from one scene to another

### ISSUE THREAD

**Issue by INait** [urho3d/Urho3D#1793]
Imagine, you have a Node with RigidBody2D component on a scene1.
You try to move it to some node of scene2
`someNode->AddChild(nodeWithRigidBody);`

In that case we see this code
`        // If old parent is in different scene, perform the full removal`
`        if (oldParent->GetScene() != scene_)`
`            oldParent->RemoveChild(node);`

which removes the node with components from the old scene.

The problem is that in such removing we lose body_ object from RigidBody2D, because on removing the function ReleaseBody() is called.
It results in wrong RigidBody2D component in a new node.
Unfortunately, I didn't manage how to fix it myself.

**Comment by cadaver** [comment]
In general, moving nodes between scenes is not a good idea (though you might think it would be natural for an indoor-outdoor transition for example) because that is a rather untested part of the engine. A more foolproof solution is to simply recreate the whole object in another scene.

However, what should happen here is that a new body gets created to the different physics world of the second scene. As far as I understand from the PhysicsWorld2D / Box2D code, that is inevitable; it's not possible to simply transport a rigidbody from one Box2D world to another.

**Comment by INait** [comment]
So the general advice is not moving nodes from one scene to another? I found it useful for custom prefabs, loading before the main scene creation.

**Comment by cadaver** [comment]
We did a pass on the engine code to make it work reasonably well in all components, but yes, it's not something I'd recommend if you can avoid.

**Comment by INait** [comment]
I'm closing as there is no architectural solution exists.
