### ISSUE TITLE
Convert Networking to RakNet

### ISSUE THREAD

**Issue by JSandusky** [urho3d/Urho3D#1810]
RFC:

I've done this, it works on NinjaSnowWar. This is about if it's really worth it or not? The change was not interface breaking beyond code touching networking and was largely straightforward (completed in approx. 4 hours).

Are RakNet's features worth the change? Such as LAN discovery which kNet cannot do?

**Comment by OldSnake22** [comment]
+1000 for this !

**Comment by cadaver** [comment]
It's true I wouldn't technically have opposition to moving to Raknet, but since originally voicing my opinion it seems to have been abandoned by its current owners, and others have continued development in forks.

**Comment by iSLC** [comment]
Unfortunately kNet shares the same fate. I suppose now it's a matter of features.

**Comment by OldSnake22** [comment]
Yes this is an important thing to consider but knet's official repository last commit is from 2014... So im agree with iSLC.

**Comment by cadaver** [comment]
kNet has a smaller codebase, so in theory it would be easier to fix than RakNet in case some new issue is discovered. Maybe the question could be phrased so that @JSandusky would you have interest in continuing the network work in case something further is needed, or is this just a one-off dump of code? In case of latter, it's less attractive.

**Comment by 1vanK** [comment]
What about https://www.libsdl.org/projects/SDL_net/ ?

**Comment by cadaver** [comment]
That's basically a crossplatform socket / packet abstraction, so you would have to rewrite the logic contained in kNet and RakNet which handles reliability over UDP, stuffing messages into packets, ordering streams etc.

**Comment by yushli** [comment]
It would be nice to have RakNet as an option that can be turned on/off so people can select on their own needs. But I agree that kNet would be kept as official version since it has smaller/simpler code base.

**Comment by eugeneko** [comment]
@yushli However this means that Urho will need some compile-time switches and duplicate code. It already has such stuff for rendering...

**Comment by cadaver** [comment]
Database also has two implementations, however these are for different usecases (SQLite vs full-blown ODBC). Networking is however always the same, sending packets, so IMO we should just have the one we have decided as best. In this case the choice is between more features over known and small code.

**Comment by OvermindDL1** [comment]
For note, I put in some of the original code in RakNet itself **years** ago, and consequently know its code-base well.  It has a few bugs and design decisions I would not have done, but (with the forks bug fixes) it is very solid, plus if you need anything done in it like any bug hunting or so, do please @overminddl1 me.  :-)

But I would definitely choose it over kNet.

As for your two points:

> Throttling was never officially included, so Urho includes a custom algorithm. It's by no means the best since I wrote it rather quickly without testing properly on different network conditions. This mostly affects the maximum transfer rate for UDP resource package transmissions.

Raknet has multiple styles built in that you can choose (or it did when I last used it), the default was finely tuned for real-time games by well using the possible packet options, which is that you can state a packet is one of different types of reliability and orderedness like:

- Reliability types
  1. Reliable, Will arrive, always (eventually if network issues, but will always arrive), think of this as TCP, but faster
  2. Unreliable, Can be dropped or abandoned, this is basically like UDP

- Orderedness
  1.  Perfectly ordered, every past one will be held in a queue until every previous one is received then delivered to the network handler in perfect order.
  2.  Sequenced, every one will be delivered to the network handler 'now', but any that were sent before but arrived later are ignored.
  3.  Non-Ordered, every packet is sent to the receiving network handler as received

So something like a first-person-shooter movement packets are best as 'Unreliable Sequenced', since you do not care about past positions, you just care about the most recent position.  It is also good to occasionally (every 5 seconds or so is common) send a 'Reliable Sequenced' version of it, just to make sure the clients get it.  Something like file transfers should be 'Reliable Ordered'.  Something like an RTS game ordering a unit would usually be 'Reliable Non-Ordered' from client-to-server but 'Reliable Ordered' from Server to Client.  Things like that, and this is all on a per-packet basis.

A side note on ordered and sequenced, they have an associated ID for those (a byte in size I think, channels 0 to 13 were reserved as I recall, there is an enum to use, something like ORDERED_USER_ID+14 or so) and things were ordered based on their 'channel id', so you could have multiple ordered streams that did not interfere with each other.

It was a very powerful system.  :-)

> Due to the threaded UDP packet send process, there is always a small delay to message transmission.

RakNet is threaded as well, it has its own send/receive thread, and you access it just by polling in your main loop, something like:
```cpp
while(gameRunning) {
  // Other main loop stuff here, like polling input events
  while(RakNet::poll(&packet)) {
    // Handle packet here, you can dispatch it around, use RakNet's dispatching abilities, etc..
  }
  // Other main loop stuff here, like updating AI and rendering and such
}
```
The delay was miniscule in receiving, and as for sending RakNet did a few things depending on the size and rate, first of all if the packet is larger than an MTU then it breaks it up and sends the large parts immediately, no delay.  If it is small ones then it holds on to it and batches them up to send multiple all within a single UDP packet or until a timeout was reached (default 50ms or something like that, configurable of course).

But yes, I've not seen a high level view on UDP yet that was better than RakNet even if I've not yet programmed on it in over 10 years.  Even 10 years ago RakNet was essentially 'done'.

**Comment by OvermindDL1** [comment]
Oh, I did not finish the throttling part, as for the sender it will drop unreliable packets if the connection reaches its throttle point or the receiver starts getting overloaded, which is also configurable.

**Comment by JSandusky** [comment]
@cadaver I don't think there would actually be a dependency on anyone at all for RakNet. I'll start preparing a PR so it can be looked at but it's one of those things that sounds really big, and then you look at it and it's actually quite small - the bulk of it is substitution so it was incredibly straight-forward. It was harder to convince myself to sit down and do it than to actually do it.

SprueKit is using Urho3D internally (exposing the underlying Urho3D primitives for power users), so in some capacity I can look over it as I'm sort of *stuck* with Urho3D for the foreseeable future.

Alternatively, I'm not opposed to placing it in a fork on its own for others to merge as they wish and the PR could be rejected.

**Comment by cadaver** [comment]
Yes, please do make a PR. We'll see then if there are any platform issues. I don't actually see it getting rejected without a serious reason (like if we just can't get some platform to work).

**Comment by JSandusky** [comment]
Published into https://github.com/JSandusky/Urho3D/tree/RakNet branch.

Several todo's to take care of (metrics, Lua bindings for setting/pinging the discovery beacons). I'm more concerned that things compile and function correctly on all the platforms where it should.

I don't expect it to be a fast process getting it forward towards a PR.

**Comment by rasteron** [comment]
Interesting development here, got it tested and working with VS2015. Looking forward to this and maybe some NAT punchthrough tests or demos since RakNet supports it.

Keep it up! :+1:

**Comment by JSandusky** [comment]
Thanks for the confirmation of good on VS2015 (I've checked VS2013 and VS2015, but external yeap, works is good).

NAT's been on my backburner. Once the Qt editor code gets pushed and I wrap up the other items I opened/tie-to-me I'll come back to it and the metrics recording (probably the 4th next month).

**Comment by ifarbod** [comment]
Fun fact: It works on VS2017 without any major problems too.

**Comment by rasteron** [comment]
Android works (not fully tested) but getting some compile errrors on MinGW (5.1). No problems with the latest version and ming btw..

log: https://pastebin.com/RDfqcuWe

**Comment by JSandusky** [comment]
@rasteron, thanks. It's the fully qualified enum names that GCC is upset about, I'll fix that.

**Comment by JSandusky** [comment]
@rasteron, pushed that fix out a few hours ago.

**Comment by rasteron** [comment]
works great now! thanks.

**Comment by rokups** [comment]
@JSandusky why was issue closed? Your branch with port is not available either. Are you no longer sharing code?

**Comment by OvermindDL1** [comment]
And for another data point, RakNet was forked since it was open-sourced (the original repo was dead, not accepting any PR's or anything at all) and has been updated, many bugs fixed, couple new features, etc, and the 'raknet community' (still small) is mostly rallying around it, it seems.  They just did their first release with all PR's merged, features brought it, and stability improvements to bring it up to a great product:  https://github.com/SLikeSoft/SLikeNet/releases/tag/v.0.1.0

**Comment by JSandusky** [comment]
@rokups I cut ties with Urho a while ago. This was killed because of a verbal dispute that was not resolvable. I will not treat with idiots, period. So I chose to nuke it.

**Comment by rokups** [comment]
@JSandusky this is unfortunate, though i think i know what you mean...

[Atomic](https://gitter.im/AtomicGameEngine/AtomicGameEngine) is very welcoming towards new people so please drop by and lets chat about gamedev-things. Alsp if you still happen to have that code and are willing to share we at Atomic would love to take a peek as we were discussing possibility replacing kNet. If not - still drop by ;)

**Comment by darrylryan** [comment]
@JSandusky Yes I second that... please do come chat to us on Atomic Gitter, we would love to have your ideas/help on this (even if you don't have the code any more).

**Comment by Alan-FGR** [comment]
@JSandusky come to our lovely Atomic community! A nice warm place by the riverside, where you can ride the camels, feed the badgers, and most importantly: experience the future... today! :P
(only camel caravanners will get the references :) )

**Comment by JSandusky** [comment]
I dug around a bit and found the code: here's a link to a zip with all the RakNet sources (https://1drv.ms/u/s!ApddaGejzZuYkHMBBpOALfhGzBPo), regarding 3rd party updates/fixes - anyone using it will want to do a diff check as most of those are probably are in there (only RakNet source change I made for Urho was adding a hash function and it should be properly marked).

Some of the contents are surely superflous, but since Scene, Angelscript, and LuaScript all touch networking (and CMake is whacky to piecemeal) I erred on including more rather than less. In total IIRC it was one solid day of work to switch to RakNet (when looking at the code it's quite obvious that's it practically just substitution, testing took a while though) and the only special bit of RakNet I implemented was LAN discovery-beacons as that's what drove me to switch to Raknet.

I have no concerns or vested interest in these sources so anyone can do whatever they like with it, was written under MIT headers and mindset as well.

On kNet vs. RakNet - it's all about developer availability. As long as the kNet developer is reachable it's viable, but even if RakNet is generally considered abandoned it is so well written and easy to work with/modify that a lack of any further development is less "it's dead" and much closer to "it's as done as done gets."

**Comment by eugeneko** [comment]
@JSandusky Thanks for sharing!

**Comment by JSandusky** [comment]
@eugeneko ask for it and I'll yield pretty much anything. Asking is hard, so I'll always acquiesce. I hope it's useful to someone.

Same deal with some potential bits in PBR in the past, it was asked - I yield and explain why I feel I have no claim.

That QT stuff, was commercial first, open last.
