### ISSUE TITLE
Using Recast navigation in 2D case

### ISSUE THREAD

**Issue by INait** [urho3d/Urho3D#1833]
For now, as I see in NavigationMesh.cpp, only 3D objects are taken into account when collecting geometries for navigation mesh.

`if (drawable->GetType() == StaticModel::GetTypeStatic())`
`    info.lodLevel_ = static_cast<StaticModel*>(drawable)->GetOcclusionLodLevel();`
`else if (drawable->GetType() == TerrainPatch::GetTypeStatic())`
`    info.lodLevel_ = 0;`
`else`
`    continue;`

only static 3D models and terrains. Is there any quick solution on how to use empty 2D space top-down as a passable area, and any staticModel2D as an obstacles?

**Comment by cadaver** [comment]
This sounds like it would be a misuse of Recast/Detour, because it builds the navmesh in 3D based on 3D geometry, ie. you have for example a terrain, and obstacles protruding from it. While sprites are only flat planes in 2D, so there's nothing to properly compare against.

You could use some crude workarounds like placing 3D box models into the scene just for the navigation geometry build, then removing them afterward so that they don't get unnecessarily rendered. Otherwise I'm not sure if "cheating" 3D navigation geometry from 2D sprites should actually be part of the engine.

**Comment by JSandusky** [comment]
The navigation API is entirely centered around 3d with a Y-up axis, which is the biggest obstacle. The Y axis is also the up-axis for 2D so in order to process any 2d geometry a basis change must occur when feeding the geometry into Recast and when interacting with Detour's API as it assumes everything it works with came from Recast.

It's possible in the case of a single-"surface" top-down / birds-eye view 2d (a platformer view is not a case for Detour). It would be incredibly nasty though and create a "bring all 3d Detour functionality to 2d" problem.

For 2d there are better options like running Marching Squares based on layers and building a half-edge mesh from it to pathfind against.

**Comment by INait** [comment]
Hi, 2d pathfinding in my case is needed for 2d not cell-based top-down realtime navigation. As I understand now, I have to write my own algorithms for this.

**Comment by JSandusky** [comment]
> for 2d not cell-based top-down realtime navigation

That's a bit ambiguous, I interpreted that as 2d *not* cell-based *and not* top-down, in which case you are pretty much on your own.

If top down it might be viable (I'm not familiar with Urho2d to know for sure) to make the 2d basis configurable so that the basics of Detour could be accessed sanely in an XZ instead of XY system.
