### ISSUE TITLE
Advanced terrain material

### ISSUE THREAD

**Issue by VinnyVicious** [urho3d/Urho3D#1843]
Today, Urho only supports 3 textures for terrain splat-mapping. It looks good for simplistic landscapes, specially if the camera is distant from it. However, for first person and third person perspectives, it can be really problematic. It would be nice to have support for advanced terrain materials in Urho's terrain. Something not so advanced or cutting edge, just a little more versatile. UDK's Terrain is a good example:

https://docs.unrealengine.com/udk/Three/TerrainAdvancedTextures.html

Or Unity's multi-material support:

http://www.bitsalive.com/how-to-create-awesome-terrains-in-unity/

**Comment by JSandusky** [comment]
IMO this is out of scope. The core objective of Urho3D (as I interpret it) is to serve as a solid baseline. With texture arrays you can easily expand further, other-wise you have to go down the dark texture atlas hole and pay the manual mip cost, which will be really bad if your view angle is mostly parallel to the terrain. Granted to do anything meaningful you still need to perform derivative sampling.

You can also leverage a base color-map and use the splatmaps as detail textures premixed in a -1 to 1 range then renormalized back to 0 - 1, which would be in strong alignment to what Bungie does (and has done as far back as Myth: TFL).

The shaders and materials are meant as references. I don't agree with the PBR shaders assuming non-linear inputs (apply pow(N, 2)), but they're references so getting rid of those assumptions is no big deal.

> UDK's Terrain is a good example:

Do you actually mean UDK's or do you mean UE4's. UE3 (which UDK used) did not support texture arrays and dealt with terrain as a multi-pass issue. Multiple passes for one object for identical purposes is not supported in any of the reference render paths in Urho3D, and not even internally supported - it's an odd notion. 

How to handle those differs greatly between forward, prepass, and deferred.

**Comment by cadaver** [comment]
@Jsandusky You got it right, the baseline of expectations is that Urho should not be missing major pieces of code functionality so that anyone can write their more advanced materials, but those materials or other advanced effects might not be there out of the box.

If someone happens to be interested in doing this then we'd naturally take it in, but it's risky to hold one's breath for that happening, considering we are relatively understaffed, and cannot compete with commercial engines in that sense.

**Comment by slapin** [comment]
I will be really very-very interested to see this in Urho too. As I have to ad-hoc my terrains as terrain + decals + mesh objects for now
@JSandusky could you please explain your terminology for us mere mortals (like me) trying to do
something good but not knowing how...

**Comment by JSandusky** [comment]
@slapin, sorry my bad. The dot-prod stuff is just using detail textures in an s-normal (-1 to 1) range (the 1.0 - (detResult * 2.0) below), you dot the blendmap with the channel packed grayscale detail textures, this gets you the weighted blend, converting to a -1 to 1 range then prevents excessive darkening where detail textures overlap. (Was covered pretty well in ShaderX4, I crossed my wires on Myth:TFL though - it's the Project-Magma updates that added that))

Shader code (GLSL):

    vec3 colMap = texture2D( terrainColor, texCoords).rgb; // Unique RGB terrain color texture map (sort-of res (4-8k))
    vec4 blendMap = texture2D(terrainBlend, texCoords).rgba; //RGBA detail map blend mask
    vec4 blendTex = texture2D(detailCompositeMap, texCoords * 300.0).rgba; //packed detail texture map (RGBA channels)
    float detResult = dot(blendTex, blendMap);
    detResult = 1.0 - (detResult * 2.0); // remap the range
    colMap += (-detResult); // mix with blend map

Gist is you use a unique color-map for low frequency color and then use the detail textures for high-frequency detail (since they are channel packed it's easy to cram in 8-12 of them, only changes whether the dot instruction can be used instead of a fully written out 8/12/16 element dot) and they can be used for getting normals from the derivative.

---

Using texture arrays is pretty straight forward if you don't care about soft blending, just remap a channel to an index. It's not-trivial to blend though. I think JTippets shared some terrain shaders in the forum a while ago that went up to I think 16 textures, it was with some terrain texture painting stuff he was doing.

**Comment by boberfly** [comment]
@JSandusky heh I remember doing that with fixed-function dot product texture combiner to do detail textures on old phones with ES 1.1 which could only sample 2 textures in 1 pass, Halo 1 I think did it for when they needed to port it to PC on Geforce4 MX hardware with similar limitations (DX7) which was everywhere at the time...

This is probably now the state-of-the-art terrain rendering:
https://666uille.files.wordpress.com/2017/03/gdc2017_ghostreconwildlands_terrainandtechnologytools-onlinevideos1.pdf
So just do that, hahaha!

**Comment by VinnyVicious** [comment]
I've checked the multi-texture example here: http://urho3d.wikia.com/wiki/Expand_default_terrain_material_to_6_textures_using_the_six_primary%26secondary_colors

However, this is a texture solution, not a "material" solution. I would like to be able to assign materials to terrains, including normal, specular and other maps. Does anyone know a similar implementation? I'm using WorldMachine to generate splatmaps and use them as masks for material setup.

**Comment by slapin** [comment]
Thank you so much!


On Fri, Mar 10, 2017 at 6:13 AM, Jonathan Sandusky <notifications@github.com

**Comment by carnalis** [comment]
[JTippetts' Urho3D Terrain](https://discourse.urho3d.io/t/terrain-editor/765) is the most sophisticated I have seen (and I have linked to it in the official [wiki](https://github.com/urho3d/Urho3D/wiki)) so it may be useful. It is still in development and there were some limitations to be aware of.
