### ISSUE TITLE
ReinsertToOctree code path slows down over time

### ISSUE THREAD

**Issue by rokups** [urho3d/Urho3D#1858]
Following histogram displays how much [ReinsertToOctree](https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Graphics/Octree.cpp#L455-L481) code block takes on android (galaxy s5). This is about 13 minutes of data. As you can see from the picture not too long after start it begins killing framerate and it gets only worse.
![image](https://cloud.githubusercontent.com/assets/19151258/23834036/5bea483a-0747-11e7-943d-2473dc98db1b.png)

My test scene is very simple - up to 10 objects move across the screen rotating randomly. Triangle count is stable (3.5k), batch count stable as well (about 20, goes up to 30 sometimes). One thing to note - on pc batch count is about 10 for very same scene (if it is of any relevance). Memory usage reported by debug hud is also stable.

This also seems to be happening on PC, although at much slower rate (also about 13 minutes of data) and has much less of an impact:
![image](https://cloud.githubusercontent.com/assets/19151258/23834187/1381fe3c-074a-11e7-8d57-a7fbc0b564bc.png)

**Comment by yushli** [comment]
I am quite interested in this investigation. Would you like to give more details about the issue, e.g., what is the cause of this profile diagram?

**Comment by rokups** [comment]
Its a shame to admit but nodes were not removed from the scene - basic mistake. I had code written to get them removed when animation finished but event was not triggering for some reason. I realized this when i saw that `drawableUpdates_` count is only rising.

**Comment by yushli** [comment]
Thanks for sharing this. The reason I am interested in this topic is that once I try to implement background repeating feature in Urho3D. It turns out that the background moves not very smoothly,sometimes fast, sometimes slow, even the scene contains nothing else. I suppose there is some place that can be improved but I cannot find out where. I asked in the forum but didn't get a solution. Hope to see more profile results from you.
