### ISSUE TITLE
Compiling option -DURHO3D_SSE=1 apparently not being honored on Debian 8.7 (amd64)

### ISSUE THREAD

**Issue by dev3456** [urho3d/Urho3D#1859]
Hello,

While compiling Urho3D 1.6 on Debian 8.7 (amd64) I noticed that, after running cmake, the `-DURHO3D_SSE=1` option apparently wasn't being honored.

```
./cmake_generic.sh . -DURHO3D_DEPLOYMENT_TARGET=generic -DURHO3D_SSE=1
[...]
--  CFLAGS:        -ffast-math -pthread -fdiagnostics-color=auto
--  EXTRA_CFLAGS:  -Wshadow -Wall
--  EXTRA_LDFLAGS: -Wl,--no-undefined
--  EXTRA_LIBS:    rt;m;dl;GL
[...]
```
I had to `export CFLAGS="-msse -msse2"` to it to be added.

```
export CFLAGS="-msse -msse2"
./cmake_generic.sh . -DURHO3D_DEPLOYMENT_TARGET=generic -DURHO3D_SSE=1
[...]
--  CFLAGS:        -msse -msse2  -ffast-math -pthread -fdiagnostics-color=auto
--  EXTRA_CFLAGS:  -Wshadow -Wall 
--  EXTRA_LDFLAGS: -Wl,--no-undefined
--  EXTRA_LIBS:    rt;m;dl;GL
[...]
```

The same happens on `cmake_mingw.sh`.

This, however, doesn't happen on Debian 8.7 (i386).

Since I'm new to Urho3D I'm not sure if that's intended or not, so I'm reporting it just in case. Please correct me if I'm wrong.

Best regards.

**Comment by weitjong** [comment]
Your issue could be caused by the CMake cache variables. We recommend to use out-of-source build tree because when in doubt you can safely just discard that build tree and  generate a new one, and when experimenting you can have multiple build trees to try out the build option combinations without worrying the CMake cache variables interference in between them. 

You may need to clear your CMake cache first before retrying, if you wish to keep your current setup.

**Comment by dev3456** [comment]
Oh, I see.

Tyvm for the reply.
