### ISSUE TITLE
Documentation does not mention replicating and connecting to local server

### ISSUE THREAD

**Issue by Halo14-** [urho3d/Urho3D#1878]
Although the SceneReplication sample works well, the server instance is not able to join as a client whilst hosting a local server. 

Whether or not this is a limitation is unclear, however something like this would be sufficient:-

```c++
void SceneReplication::HandleStartServer(StringHash eventType, VariantMap& eventData)
{
    Network* network = GetSubsystem<Network>();
    network->StartServer(SERVER_PORT);

    network->Connect(String("localhost"), SERVER_PORT, scene_);

    UpdateButtons();
}
```

Is this supported? If so, what is the correct method for replicating the local player across client objects?

**Comment by cadaver** [comment]
For simplicity, the samples are intentionally made so that it does not simultaneously run as both server and client. There should not be a technical reason in the Network subsystem that would prevent it, but you should have separate scenes in that case. Ie. server scene - simulation only, client scene - will be rendered. I remember this has been discussed on the (old) forums.
