### ISSUE TITLE
Cannot set iOS flag in cmake

### ISSUE THREAD

**Issue by milos1290** [urho3d/Urho3D#1948]
Getting this error when enabling iOS for Urho3d
```
CMake Error at CMake/Modules/UrhoCommon.cmake:72 (message):
  IPHONEOS_DEPLOYMENT_TARGET cannot be changed after the initial
  configuration/generation.  Auto reverting to its initial value.  If you
  wish to change it then the build tree would have to be regenerated from
  scratch.
Call Stack (most recent call first):
  CMakeLists.txt:43 (include)
```

**Comment by weitjong** [comment]
The original intention is once the build tree is generated with one deployment target (say 10.3) then it would warn user when user wants to reconfigure the build tree for another deployment target (say 9.1). This is because when changing the deployment target, certain initial detection needs to be redone again, especially when the detection result could be different (like the detection of the weak function symbols). You can avoid this warning by regenerating the build tree from scratch.

However, after thinking a little bit more about this, I believe there could be other ways to tell CMake that we need to redo the initial detection while keeping the same build tree. Will explore this when I have time.

**Comment by milos1290** [comment]
I was able to build Urho library for iOS, the same problem arise when trying to create build tree for iOS in my project. It also shows
`IPHONEOS_DEPLOYMENT_TARGET = 10.12` which is wrong.

**Comment by weitjong** [comment]
10.12? This tells me that you are mixing a single build tree between macOS and iOS platforms and you should not do that. You should have separate build tree for each platform.

**Comment by weitjong** [comment]
I am closing this for now. Feel free to reopen when you have anything more to update or that it is indeed a bug/issue in our build script.
