### ISSUE TITLE
Support to OpenVR  API

### ISSUE THREAD

**Issue by coldev** [urho3d/Urho3D#1956]
Thanks for this powerfull engine..

Is possible support OpenVR api  ? (  Include all VR' S in One )

**Comment by MajorMcDoom** [comment]
I'd like to second this request, please. VR is the future! :D

**Comment by OldSnake22** [comment]
+1 would be interested by this

**Comment by seanvolt** [comment]
Working on this right now. I've got a VR subsystem getting controller input and sending renders to the headset, all that's left is a few details and then splitting the code neatly from my internal project in a way that best fits the architecture of Urho3D.

**Comment by seanvolt** [comment]
I have gotten OpenVR working in Urho3D and have put up a fork at https://github.com/seanvolt/Urho3D_VR in order to get things moving further. I would love input and some help with things like CMake!

**Comment by weitjong** [comment]
Could you rebase your master branch against a known commit SHA from Urho3D official master branch? Not necessarily release 1.7. Choosing a commit closest to the point where you started your work will do. Then let the changes from your initial integration work as additional commits on top of it. This way from the commit history we could clearly see what have been changed and easier to review the work.

**Comment by kurikaesu** [comment]
I've started an implementation of OpenVR which you can find on my fork of a fork here:
https://github.com/kurikaesu/Urho3D

Here are my Windows MR motion controllers floating in one of the scenes.
![image](https://user-images.githubusercontent.com/6769666/34336039-ee46303e-e9a7-11e7-95a8-5a77202298c3.png)

I will have access to an Oculus Rift again in a few weeks time so I may implement the Oculus API as well when I get there.

**Comment by CG-SS** [comment]
Any update on this?

**Comment by commanderZiltoid** [comment]
Would also be interested in an update on this

**Comment by TrevorCash** [comment]
Just a FYI - I have started adapting this code to be a rbfx plugin - so far I have gotten it to work with the valve index.  I also fixed the projection hacks: https://github.com/TrevorCash/rbfx-openvr

**Comment by ArnisLielturks** [comment]
@TrevorCash Are you planning to adapt this for the upstream Urho3D too? Just curious.

**Comment by TrevorCash** [comment]
@ArnisLielturks Im not going to directly.  However you should be able to use the plugin for upstream with a few little adaptations (while still keeping it a plugin).  Actual code-wise it should work.

**Comment by JSandusky** [comment]
For a while I used an adaptation of @TrevorCash that eventually got gutted and reworked to prototype out how to work with OpenVR:

https://gist.github.com/JSandusky/99502966989ceb6652d711bcc9124c75

Doesn't work out of the box because I had to overhaul View, Batch, and VertexBuffer for single-pass-stereo. Only View changes need to be removed (dropping all of the single-pass stuff). 

- Single target side-by-side
    - Optionally can do single-pass stereo (assuming you've reworked batch-rendering to support it)
        - double all instanced draws (turns non-instanced into instanced draws) and sets the instance-data step-rate to 2 then does the clip and offset in the VS using `instanceID & 1` to index the relevant shader uniforms
    - Requires tweaking lots of shaders if you want to use it (~20 lines per shader)
- MSAA + target scaling (min: 0.25x, max: 2x), not automatic though
- Hidden area meshes (via forced depth-write)
    - With automatic masking utility (just remove the main clear command from your renderpaths)
- Properly loads controller meshes
- Controller loss/acquisition (but not mutation, that's unrealistic outside of swapping Vive/Index controllers on the fly [lunatics])
- Proper aim pose and ray
    - tested on WMR, Vive, Index (+PIMAX using Vive wands)
- PIMAX works (in two pass, not single-pass - single pass requires culling overhaul), only tested on the 8K
- Mostly setup for the newer input API
    - Probably bugged, that transition from legacy was where I said good enough and ported over to my engine (Urho3D was just for prototyping)
