### ISSUE TITLE
Samples are missing .html files to launch for Emscripten

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#1994]
Running with

```bash
git clone https://github.com/urho3d/Urho3d.git
cd Urho3d
mkdir build_emcc
./cmake_emscripten.sh build_emcc
cd build_emcc
make
```

ends up generating a `build_emcc/bin/` directory with content from all the samples, but each sample only contains a `.data` and a `.js` file and no `.html` file to launch. I wonder if the method to run has changed somehow, or if this is a regression?

**Comment by weitjong** [comment]
Hi Jukka, welcome back!

This is the new expected behavior now. The default "output" for Web platform is asm.js or wasm, instead of html. This has been noted down in our porting notes. User has to explicitly provide a custom shell in order to generate the HTML output. To quickly test Urho with the default shell (as it had in the past) you have to enable the URHO3D_TESTING build option. This would not only configure the build system to use your "emrun", but also force it to generate HTML output (using the default shell if user has not provided one).

**Comment by weitjong** [comment]
Feel free to reopen it.
