### ISSUE TITLE
CrowdManager get hang when received E_NAVIGATION_MESH_REBUILT event

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#2013]
When I build `DynamicNavigationMesh`, it sends `E_NAVIGATION_MESH_REBUILT` event and make `CrowdManager` hang because it re-subscribe to `E_NAVIGATION_MESH_REBUILT` inside event handler (see `SetNavigationMesh`) and then endlessly re-receive the same event.

Note: My `DynamicNavigationMesh` is _not_ stored in `Scene`, but the `CrowdManager` is.

I've patched event handler in `CrowdManager` but I am unsure that it is good fix.
Shall we probably do something at the level of event system?

Do we really want newly added listeners to receive "current" event?

**Comment by cadaver** [comment]
I think we've never really nailed down precisely how subscribing while event is sent should work, but since it gives opportunity to this kind of bug, the current behavior doesn't look good.

Check if you could simply take the current size of subscribers vector in Object::SendEvent before the subscriber loop begins. That means subscribers added in the meanwhile should get ignored. OTOH, subscribers removed simply leave holes until the subscriber group cleans itself up.

If it works good, you have my OK to make that change.

**Comment by eugeneko** [comment]
> Check if you could simply take the current size of subscribers vector in Object::SendEvent before the subscriber loop begins

I thought the same. I'll check it, this shall probably work ok.
