### ISSUE TITLE
cmake-gui does not use symlinks like console cmake

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2037]
When i use command
```
Urho3D/cmake_vs2015.bat Build -DURHO3D_OPENGL=ON -DURHO3D_SAMPLES=OFF -DURHO3D_LUA=OFF -DURHO3D_STATIC_RUNTIME=ON -DURHO3D_TOOLS=OFF
```
cmake create symlinks for objects in urho3d/bin directory, but when i use cmake-gui I recieve this warning

![1](https://user-images.githubusercontent.com/13021826/28497925-6b3cf96a-6f9b-11e7-876e-9787e2268ab0.png)

**Comment by 1vanK** [comment]
Ok, when I open folder to c:\Programs\CMake\bin\ and run Cmake-gui
```
execute_process (COMMAND cmd /C mklink test-link CMakeCache.txt RESULT_VARIABLE MKLINK_EXIT_CODE OUTPUT_QUIET ERROR_QUIET)
```
does not foud CMakeCache.txt in current dir and return 1

**Comment by 1vanK** [comment]
another problem mklink must recieve path with "\" instead "/" so this code resolve issue:
```
        string (REPLACE "/" "\\" FIXED_PATH "${CMAKE_BINARY_DIR}")
        execute_process (COMMAND cmd /C "mklink ${FIXED_PATH}\\test-link ${FIXED_PATH}\\CMakeCache.txt" RESULT_VARIABLE MKLINK_EXIT_CODE OUTPUT_QUIET ERROR_QUIET)
```

**Comment by 1vanK** [comment]
Ok, now symlinks will be created for all users and all users will have the same error as I did :)
https://github.com/urho3d/Urho3D/issues/1974#issuecomment-312571858

**Comment by 1vanK** [comment]
https://github.com/urho3d/Urho3D/pull/2040

**Comment by weitjong** [comment]
This is interesting. I have always assumed the `execute_process` command to default the working directory to CMAKE_BINARY_DIR and therefore almost all calls using this command in our build scripts do not use WORKING_DIRECTORY explicitly unless the directory other than the CMAKE_BINARY_DIR is desired. Perhaps, it is because I invoke the `cmake-gui` from the terminal. Really not sure how I could miss that :smiley: . Anyway, if that is the case then your PR just fixes one case among dozens others. Do you want to fix the rest of them in your PR? Or you want me to use the perl to search/replace automatically?

**Comment by 1vanK** [comment]
With this PR cmake-gui behaves the same way as console command from sources directory on my PC

**Comment by weitjong** [comment]
Ok. In that case I won't waste my time to double check it and just merge this is in as it is. Thanks for the PR!
