### ISSUE TITLE
Compiling Urho3D with Clang

### ISSUE THREAD

**Issue by hsnabn** [urho3d/Urho3D#2102]
Hello. I'm trying to compile Urho3D using Clang 4.0.1 on Windows x64 (built myself, not the binary version available on the website), and I'll try to document the issues I came across.

Of course, there's plenty of warnings. Should I make a new issue for those? I'll omit them as of now. I'll include them later.

I built with `URHO3D_NETWORK` and `URHO3D_URHO2D` disabled, as well as `URHO3D_SAMPLES`, and with `URHO3D_OPENGL` plus `URHO3D_C++11`. All done on the latest commit on master (usually keep updated). If anyone wants options changed though please ask and I'll try a build if possible.

* `error: unrecognized command line option "-fno-keep-inline-dllexport"`
Compiling fails with this error. Fixed by removing the occurrences near line 683:
```cmake
elseif (MINGW)
        # MinGW-specific setup
        # Removed -fno-keep-inline-dllexport from both
        set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -static -static-libgcc")
        set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static -static-libgcc -static-libstdc++")
```

* SSE disabled by default. Works fine when enabled manually.
```
CMake Warning at CMake/Modules/UrhoCommon.cmake:172 (message):
  Disabling SSE by default due to MinGW version.  It is recommended to
  upgrade to MinGW with GCC >= 4.9.1.  You can also try to re-enable SSE with
  CMake option -DURHO3D_SSE=1, but this may result in compile errors.
Call Stack (most recent call first):
  CMakeLists.txt:45 (include)
```

**Comment by weitjong** [comment]
I am a little lost. Which platform is you targeting? Clang compiler is supported in general but not sure how you ended up in your situation. Compiled with Clang but MINGW flag is true.

For MinGW we do have a number of checks before configuring because there are too many MinGW versions out there and packaged by different package manager or vendor. The accumulated tweaks that we have are mainly contributed by the MinGW users or in response to the problems they faced. If you are using Clang then it should be of no concerns to you. Perhaps I miss something. 

As for the compiler warnings, contribution is welcome to fix them. However, we in general do not modify 3rd-party source codes for this purpose. So, if you do decide to help then please keep this in mind.

**Comment by hsnabn** [comment]
Ah sorry, I forgot to mention the crucial point that I'm compiling on Windows 64-bit. Probably the cause of any issues.

**Comment by hsnabn** [comment]
The reason I'm getting `MINGW` flag true is probably this: Clang can't exist on its own on Windows as far as I know so I'm using it along with MinGW.

**Comment by weitjong** [comment]
In that case you are in neither here nor there situation. The build scripts are as confused as I am. I am afraid you will have to get your hand dirty to tweak the build scripts to suit your own need.

**Comment by hsnabn** [comment]
Well it certainly looks like I spoke too soon... getting a console full of linker errors. Should I close the issue till I sort things out?

**Comment by hsnabn** [comment]
Definitely bit off more than I can chew here. I'll hopefully get back to this if and when I manage to work out the linker issues. Thanks for your time anyways.
