### ISSUE TITLE
Task based resource loading

### ISSUE THREAD

**Issue by amerkoleci** [urho3d/Urho3D#2149]
Hi all,
Now we have possibility to load Resource/Scene in background, I was thinking about how it would be better if we have generic task system and then use wait or result on the task, in this way we can load in single way both async and sync.

Anyone working on something similar?

**Comment by Lumak** [comment]
this:
`bool Scene::LoadAsync(File* file, LoadMode mode)
`
along with ones for XML and Json are already there, and all three loads in a background task. Were you thinking of something else?

**Comment by eugeneko** [comment]
Now everybody have to manually split background and foreground loading logic into BeginLoad/EndLoad. Just look at that ugly Material loading.
I think such logic could be simplified and generalized.

**Comment by amerkoleci** [comment]
I know about Load/SaveAsync but maybe have some task system returning lets Task<Resource> or Task<SharedPtr<Resource>> would probably do the job, maybe then on task it can done something like wait, then etc.

https://github.com/Amanieu/asyncplusplus

**Comment by cadaver** [comment]
There's still quite nasty / limiting rules on what you can do outside the main thread. To properly correct this, to e.g. allow a safe scene load outside the main thread, would be a fairly large rework. The scene async load is really just doing a little bit on each main thread frame, and since it does one root level node at a time, it can actually take a long time if it turns out the root node has a huge hierarchy underneath.
