### ISSUE TITLE
consider removing rpms from sourceforge

### ISSUE THREAD

**Issue by barcharcraz** [urho3d/Urho3D#2166]
The shared RPMs don't even install on any reasonable system because the package fails to provide liburho3d.so (which is in the package). Also they all install to /usr/local which is not really a place rpm is supposed to touch.

**Comment by weitjong** [comment]
It is always easy to remove thing than to add something back later. So instead of removing them, it would be great if you can help to elaborate what went wrong with your experience. However, you are absolutely right about the `/usr/local` should not be target install location for packaged software. Contribution to fix it is welcome or you have to wait until one of core devs has time to fix it.

All the build artifacts (RPM or not) are just an after thought in our setup because we did not plan for it originally. We have also no extra resources and time to test and verify the artifacts each time we do the Urho release. We can only promise to get better the next time based on feedback like this.

**Comment by barcharcraz** [comment]
So my argument here is that cpack’s rpm and deb generators are not that
useful. I’ll post the errors later today.

I am also considering writing a .spec file that I could contribute, this
wouldn’t integrate into your existing release system though, which makes
things harder.
