### ISSUE TITLE
Add crunch texture support

### ISSUE THREAD

**Issue by amerkoleci** [urho3d/Urho3D#2174]
Unity has updated the crunch compression texture library, having that in urho would be nice

https://blogs.unity3d.com/2017/11/15/updated-crunch-texture-compression-library/

**Comment by rokups** [comment]
Crunch can save textures in .dds format which engine can read. While crunch suggests using their custom .crn format i dont think urho needs that. Main argument behind .crn is extra compression of encoded textures where .dds contains significant amount of redundant data which takes up extra space but otherwise compresses good. Since engine supports compressing resources to .pak files these .dds textures would compress good anyway and there is no benefit in using .crn. I believe there is nothing to be done here short of implementing actual texture asset pipeline. Well maybe only supporting extra compressed texture formats like ETC2 and ASTC that crunch supports.
