### ISSUE TITLE
Impossible to disable SSE in some configurations

### ISSUE THREAD

**Issue by rokups** [urho3d/Urho3D#2197]
At least in linux builds SSE is enabled despite specifying `-DURHO3D_SSE=OFF` as CMake parameter. I have read the warnings about it being sometimes unsafe to disable. If it is unsafe to disable completely - so be it, but this option at all times should allow user to opt out of SSE use by engine and it's dependencies.

**Comment by weitjong** [comment]
It is intentional that in some cases the SSE is not a build option at all. For example on 64-bit desktop platform. So, setting the variable as if it is a build option has no effect because the build script will automatically revert it back. Last time I checked there is no way to disable it on my 64-bit GCC.  Also checked the MSVC /arch option for 64-bit, you can only opt to go for AVX or AVX2, there is no option to go for IA32; in other words SSE/SSE2 is always on.

**Comment by rokups** [comment]
That is fine, however option should still make engine and it's dependencies not use any SSE code.

**Comment by weitjong** [comment]
But why?

**Comment by rokups** [comment]
In my case binding generator for some reason does not recognize SSE macros.

**Comment by weitjong** [comment]
Also some of the code may just check whether the compiler emits the `__SSE__ ` for code branching. Since there is no way we could pass a compiler flag to suppress that to happen, we might as well make our build variable consistent with it.

**Comment by rokups** [comment]
Sounds like it would do intuitive thing then. But if you do it, please use `#if __SSE__` instead of `#ifdef __SSE__`.  `#ifdef` will be enabled even if `__SSE__` is defined to 0 while `#if` will not be enabled if `__SSE__` is 0 or undefined. That way we would have a better control on what is enabled and what is not.
