### ISSUE TITLE
Very slow startup on Internet Explorer 11 unless developer tools are opened

### ISSUE THREAD

**Issue by Alexey-** [urho3d/Urho3D#2222]
Test page is available here:
http://test.sebbia.com/urho3d/test.html

Page prints urho logs directly on top of the canvas.

If you open this page in Internet Explorer 11, you'll see that it takes about ~30s to load hello world example (time between "Resources ready" and "Initialized engine").

However, if you open developer tools and reload the page, time will drop to ~0.3s.
That's 100 times faster than without developer tools.

IE11 is the only type of browser with this bug.
After the scene is loaded, everything will work ok and with good fps (and I'm not talking about hello world scene here - game with hundreds of objects, lights and shadows works great). So the problem is only about initialization time and it only happens in IE11.

HelloWorls.js inside example is built using the latest Urho3D source code.

IE11 has this problem when too many calls to console.log can slow it down substantially unless developer tools are open, however this is probably not the case here.

I have no clue what can I try to fix this problem.
Any suggestions?

**Comment by weitjong** [comment]
Have you tested other asm.js example on IE11? Just to isolate whether this is specific to Urho3D game engine or not.

**Comment by Alexey-** [comment]
I've launched ffmpeg (also compilled with emscripten) and it works just fine:
http://test.sebbia.com/ffmpeg/test_ffmpeg.html
It seems like asm.js works just fine.

**Comment by weitjong** [comment]
You should compare our sample with something similar. The ffmpeg is just a library without the “content”. Our sample loads the Urho library and the data files as the content. Also, unless you have made custom changes, the data files include the assets for all of our samples combined. We do that as it is a sample anyway, not for actual production use. So it is rather big for the initial download. Having said that, I have no idea why only IE is slower compared to FF or Chrome. They all have to do the exact same things because our engine doesn’t care which browser being used, i.e. there is no browser-specific logic at the moment (probably we will in the future but that’s for mobile vs desktop).

If the other browsers are fine and only IE has problem then I am afraid there is nothing much we could do to improve it. Also I think the IE performance issue should be reported to the IE devs and/or the Emscripten devs instead of us, unless you have a good reason to believe there is something else caused the issue.

**Comment by Alexey-** [comment]
Ok, thanks for your response anyway.

I'll try to find a solution and will write back if I find anything.
