### ISSUE TITLE
Support tile flipping

### ISSUE THREAD

**Issue by dev-plvlml** [urho3d/Urho3D#2223]
Hello there!
Are there any plans on implementing the tile flipping feature of TMX Map Format?
As described here: http://docs.mapeditor.org/en/latest/reference/tmx-map-format/#tile-flipping
For now, when any of these three highest bits of a tile gid is set, the tile is just nullptr'ed.

**Comment by weitjong** [comment]
Like it or not, Urho3D does not have a roadmap. Though this is the right place to register new feature request, you will find that it is faster to get the feature implemented yourself if you need it badly rather than waiting for someone else who has the same need, implemented it and decided to share it.

**Comment by Alan-FGR** [comment]
There's always bountysource too ;)

**Comment by dev-plvlml** [comment]
No need for any bountysource ;)
