### ISSUE TITLE
Automatically inserted exception handling in Object.cpp by ClangTidy

### ISSUE THREAD

**Issue by iSLC** [urho3d/Urho3D#2241]
Introduced by commit e2ecc52adcf146f6a5ca3bfe52932d62ecb2f912 there seems to be an exception handling block in `RegisterEventName` method from `Object.cpp`. This prevents the engine from being built when the `-fno-exceptions` flag is used.

I'm not sure if this was intentional or not.

**Comment by weitjong** [comment]
Thanks for pointing this out. That exception block should have been guarded by the `__EXCEPTIONS` compiler define similar to Application class, which has the exception handling block also. As the commit message implies, that particular commit is actually a WIP and not supposed to be merged yet. However, all the commits from the "clang-tidy-up" development branch were merged end of last year to avoid the potential merge conflict due to the license year automatic bump. See also the discussion in https://github.com/urho3d/Urho3D/issues/2113#issuecomment-359261310.

**Comment by weitjong** [comment]
The offending code has been reverted back instead in the dev branch. Once the dev branch is merged, this issue will be resolved.
