### ISSUE TITLE
UIElement Styling Lost on Parent changes.

### ISSUE THREAD

**Issue by TrevorCash** [urho3d/Urho3D#2265]
The following test code results in the text "Test Text" **not** being shown on the screen:

```
                UIElement* root = ui->GetRoot();
		SharedPtr<UIElement> mPElement = SharedPtr<UIElement>(new UIElement(context_));
		SharedPtr<Text> mTextElement = SharedPtr<Text>(new Text(context_));
		mTextElement->SetText("Test Text");
		mTextElement->SetStyleAuto();

		mTextElement->SetParent(mPElement);
		mPElement->SetParent(root);
```

However this code does show the text on the screen:

```
                UIElement* root = ui->GetRoot();
		SharedPtr<UIElement> mPElement = SharedPtr<UIElement>(new UIElement(context_));
		SharedPtr<Text> mTextElement = SharedPtr<Text>(new Text(context_));
		mTextElement->SetText("Test Text");
		mTextElement->SetStyleAuto();

		mTextElement->SetParent(mPElement);
		mPElement->SetParent(root);
		mTextElement->SetStyleAuto();//reseting styling.

```

It seems there is some issue with styling being lost on a UIElement when its parent is changed.

Also if I re-order the last 2 SetParent calls to the following it will work again:

```
                UIElement* root = ui->GetRoot();
		SharedPtr<UIElement> mPElement = SharedPtr<UIElement>(new UIElement(context_));
		SharedPtr<Text> mTextElement = SharedPtr<Text>(new Text(context_));
		mTextElement->SetText("Test Text");
		mTextElement->SetStyleAuto();

                mPElement->SetParent(root);
		mTextElement->SetParent(mPElement);
```

**Comment by weitjong** [comment]
There is no direct relationship between a style application (style is just a a specialized attributes for UI-element) with the element's parent. You may actually apply a style to a detached UI-element and then parent and/or reparent it without any problem. However, in order to do so, you must explicitly specifies the style-file (the UI theme or skin or stylesheet or whatever you want to call it) when calling `SetStyle()` or `SetStyleAuto()`. If you do not specify it explicitly then the UI subsystem will try to find the theme/skin/style-file by walking up the parental chain to see if a default theme/skin/style-file is set and use that if it find one. So, ultimately if you have a default set at the UI root level then it could possibly use for all of its children. This is what gives the erroneous impression for the style application to be effective then the element need to be parented first some how.

**Comment by TrevorCash** [comment]
Sorry I had forgot to put the styling setup in the test code.  Based on what you said the following code should work:

XMLFile* style = cache->GetResource<XMLFile>("UI/DefaultStyle.xml");
UIElement* root = ui->GetRoot();
root->SetDefaultStyle(style);
SharedPtr<UIElement> mPElement = SharedPtr<UIElement>(new UIElement(context_));
SharedPtr<Text> mTextElement = SharedPtr<Text>(new Text(context_));
mTextElement->SetText("Test Text");
mTextElement->SetStyle("Text");
mTextElement->SetParent(mPElement);
mPElement->SetParent(root);

But nothing is shown.  I see that it does work if I set the parent of mTextElement to root directly.  But in this example I am indirectly parenting it back into root using mPElement.

**Comment by weitjong** [comment]
Your parent chain has not fully established yet at the time when you called `SetStyle()`. If you want to use default style lookup approach then you should be setup the parent before applying the style or use the templated `CreateChild()` method to setup the parent-child relationship instead of creating new instance manually then parenting it.

**Comment by TrevorCash** [comment]
Thanks @weitjong.  usually I do directly create the elements as children directly.   I am in a scenario where I want to pre-create many UIElements that are fully setup (styles applied etc) but do not belong to the UI graph until later.  I may also be removing them and re-adding them. I guess I can temporarily parent to root and then unparent after styles are applied. Thanks.

**Comment by weitjong** [comment]
Or you can pass the style file explicitly to your detached elements. Also note that the UI subsystem does not impose any limit on the number of the style files that can be used. It does not also care whether you have one default style set at the root or ten style files at each of the temporary parents you may have that temporarily contain your child elements.
