### ISSUE TITLE
nativeRunMain(): Couldn’t find function SDL_main in library

### ISSUE THREAD

**Issue by rifai** [urho3d/Urho3D#2267]
I got this error "Couldn’t find function SDL_main" on my Android logcat. I've build latest source code with default setting from cmake_android.bat. 

But, if I change URHO3D_LIB_TYPE = SHARED, the program (Urho3Dplayer & samples) run without any problem.

**Comment by weitjong** [comment]
This is a known problem. See https://discourse.urho3d.io/t/android-once-and-for-all/3676/62
Thanks for raising it as an issue. I will revisit this later when I get the time to revamp the Android build to use Gradle with gradle-kotlin-dsl.

**Comment by slapin** [comment]
Well, this is very easy fix, there is no huge lifting required.
Android .so libs are built with -fvisibility=hidden and SDL_main is not set to __attribute__((visibility("default"))). As I understand URHO3D_API sets that. A problem is that for SDL_main it is set incorrectly - it should be set in declaration part, not definition part.
After moving URHO3D_API to proper place, SDL_main becomes visible and accessible via JNI interface.

**Comment by slapin** [comment]
So it is actually not build system related, but wrong placement of ```__attribute__```

**Comment by weitjong** [comment]
Thanks for that. I didn't have time to investigate it yet since I know about the issue. My gut feeling told me it is related to symbol visibility,  so in the discourse discussion I stated that URHO3D_API should have fixed it, but it proven not to be the case, which misled me to believe there is other build system problem causing the macro in the URHO3D_API off.

**Comment by weitjong** [comment]
Moving the `URHO3D_API` macro to the right place also does not produce the `SDL_main` symbol in the Static build configuration as expected because the way how our build system works (that macro would resolve to empty define in Static build config). However, instead of using that macro we can just use the `__attribute()` directly. Note that this will make our Android build setup to be compatible with GCC/Clang only, which is not a big deal considering we have never officially supported Android build using other compilers anyway.

**Comment by weitjong** [comment]
This is the result from a quick build test locally.

```
readelf -s ../android-x86_64-Build/libs/x86_64/lib01_HelloWorld.so |grep SDL_main
     4: 000000000027ca10    12 FUNC    GLOBAL DEFAULT   11 SDL_main
```

**Comment by Zingam** [comment]
Can that SDL issue be solved in another way but the fix in the patch? Compiler flag, etc?
