### ISSUE TITLE
Why forced update to master?

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#2278]
WTF?
What is going on?

**Comment by weitjong** [comment]
Watch your language. This is not the first time and won't be the last one also.

**Comment by weitjong** [comment]
For others. You can `git reset HEAD~` or replace the "HEAD~" which is a last known commit SHA to recover easily.

**Comment by slapin** [comment]
Too sad the professional level is so low. I had much better opinion of Urho3D maintainers.

**Comment by weitjong** [comment]
Hah! And you are still wondering why I single you out and calling you a troll. If you have asked the question professionally earlier then I will be most happy to answer you back politely.

If you genuinely hit the inconvenience due to the `git pull` error then go and do the recovery action. If you just saw the force push message while git pulling though then just go and don't bother to troll me again here.
