### ISSUE TITLE
How to Create Executable File

### ISSUE THREAD

**Issue by nicolasshu** [urho3d/Urho3D#2307]
Hello!
I apologize. I went through the issues, but could not find any instructions that worked. Feel free to mark this as a duplicate, and if so, I'd appreciate if you could also refer me to instructions
(I'm working on a Ubuntu 16.04)

How exactly do I build/compile a project?

This is one of the things I was trying as the simplest case scenario

1. I copied the HelloWorld samples project folder to my Desktop. It is so simple that I don't think it has any dependencies on anything
2. Create a new folder "build"
`mkdir build`
3. Enter the "build" folder
`cd build`
4. Run cmake
`cmake ..`
5. Run make
`make`

At that point, I see no executable files to run or anything. 
Please help!
Thank you very much!

**Comment by JohnathanFL** [comment]
So to be clear, you just copied the 01_HelloWorld folder from the samples folder? The CMakeLists in that folder don't actually include Urho3D on their own, they rely on the fact that the normal build system is including **them**, rather than the other way around. To make a new project, either follow the instructions [Here](https://urho3d.github.io/documentation/HEAD/_using_library.html) or I just made a quick template [Here](https://github.com/JohnathanFL/Urho3D-Template).

**Comment by nicolasshu** [comment]
Thank you so much, man! I really appreciate it! :D :D :D :+1:
