### ISSUE TITLE
Tiled support updated

### ISSUE THREAD

**Issue by lukadriel7** [urho3d/Urho3D#2312]
Hello, I was wondering if there was any plan to update the tiled version support. The documentation states that tiled 0.9.1 is the latest supported version but since then many features were added (like animated tiles).
It would be nice to be able to use the new features in urho too

**Comment by Lumak** [comment]
Urho3D's policy is not to include any viral licensed third party software -- any GPL, LGPL, which is probably one of its appeal. So, the answer is no.

**Comment by lukadriel7** [comment]
Lumak, as  weitjong said an implementation to parse the files generated wouldn't fall under the GPL license.
If support already exist for the 0.9.1 version which was GPL licensed, an update is surely possible. The question being is there any interest in doing an update for the new format support or not. It would be nice because Tiled is one of the most feature rich 2d map editor I have seen. Since there is an outdated implementation (4 years old ? ) updating it would be interesting.

**Comment by Lumak** [comment]
To further your distaste for GPL/LGPL - read the **History** section -- https://en.wikipedia.org/wiki/Viral_license

**Comment by lukadriel7** [comment]
I understand your hate for GPL and trust me you aren't alone. However I think it has it's reasons to exist. Many company offer two licenses (GPL and commercial) to protect their work while being able to contribute to free software. Coming back to tiled, maybe I should have said support for tmx format. On their website (http://doc.mapeditor.org/en/stable/reference/tmx-map-format/) they give a description of the format which can be used as basis for a parser implementation. No need to reverse engineer the software tiled itself. Of course basing the update on the libtiled, which I guess is in java, is an option since it is made by the author of tiled himself.

**Comment by Lumak** [comment]
Two versions of libtiled:
libtiled             src/libtiled              BSD 2-clause license
libtiled-java        util/java/libtiled-java   BSD 2-clause license

libtiled, https://github.com/bjorn/tiled/tree/master/src/tiled, has cpp files.

**Comment by lukadriel7** [comment]
The cpp version seems to use Qt, is it possible to put it under BSD ?

**Comment by Lumak** [comment]
Oh, that then sounds like it's an editor.  There's nothing there.  Aside from that Qt is LGPL, and that trumps their BSD license.

**Comment by lukadriel7** [comment]
Hey, just in case people are interested, the format used in Tiled maps is described in the following links:
http://doc.mapeditor.org/en/stable/reference/tmx-map-format/
http://doc.mapeditor.org/en/stable/reference/json-map-format/

**Comment by Modanung** [comment]
@Lumak Microsoft is a logical party to be smearing open source.

**Comment by bjorn** [comment]
> To further your distaste for GPL/LGPL: https://en.wikipedia.org/wiki/Viral_license -- pay particular attention to the History section

Please also pay close attention to the section "Criticism of the term", which I think is more accurate and less encumbered by FUD. In particular Richard Stallman saying "The GPL's domain does not spread by proximity or contact, only by deliberate inclusion of GPL-covered code in your program.". This addresses your earlier comment where you stated "No, I get how good Tiled is, just don't like anything GPL.", which is clearly irrational since users of Tiled only benefit from it being GPL (having the freedom to use it for any purpose, to share it, modify it, and to share modified versions). The only thing they can't do, is to modify it and then to share it without granting those basic freedoms, which I would consider a little bit evil.

> Oh, that then sounds like it's an editor. There's nothing there.

While libtiled is not the editor, it is using Qt for XML and JSON parsing, image loading, rendering and for the generic container classes. As such it is not suitable for direct inclusion in Urho3D, however since it is also C++ it should not be hard to take and adjust specific pieces of code. Whether it is helpful remains to be seen of course.

> Aside from that Qt is LGPL, and that trumps their BSD license.

This is inaccurate. The LGPL does not affect the license of the works linking with it (this is the main difference between the GPL and the LGPL).

**Comment by lukadriel7** [comment]
Well as the author himself said, one could change the usage of Qt for xml, json and image loading and rendering by using tinyxml, rapidjson and SDL which are already part of the engine.

**Comment by lukadriel7** [comment]
Hello, It has been more than a year since I checked this engine (busy with other stuffs).
While going around, I found a tmx parser for Tiled up to v1.0 : https://github.com/fallahn/tmxlite .
If anyone is still interested in updating the feature I thought that might be an interesting addition.
The code is under zlib license

**Comment by weitjong** [comment]
We are short-handed. The best chance for that to happen sooner if someone who is interested in this makes the the PR first.
