### ISSUE TITLE
gcc 8.1 incorrect code

### ISSUE THREAD

**Issue by alex-rass-88** [urho3d/Urho3D#2326]
Bug in gcc 8.1. Incorrect code is being compiled. It's like an inside-out image.
![06-bug](https://user-images.githubusercontent.com/7008147/41107292-c0998e66-6a7a-11e8-9294-cd81c40d8aa8.png)

In gcc 7.3 normal:
![06-norm](https://user-images.githubusercontent.com/7008147/41107323-cebc966e-6a7a-11e8-8fad-1a90babb0c4c.png)

How to get workaround the problem I do not know yet. So keep in mind.

**Comment by weitjong** [comment]
Reproduced on my GCC 8.1.1. I have been using Clang 6.0 lately, everything is normal/OK there too.

**Comment by weitjong** [comment]
Didn’t have enough time to conclude anything last night, but at least I was able to narrow the issue down a little bit to compiler optimization problem. As soon as any -O level is given then the emitted code becomes wrong. My gut feeling is, it has something to do with vectorization. If so, it is our code base that needs to adapt to the new GCC 8.x. It does not seem like a compiler bug to me. But like I said, this is just my inconclusive opinion.

**Comment by alex-rass-88** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80898

**Comment by alex-rass-88** [comment]
In Debug and Release with gcc 8.1 difference worldTransform matrix in camera node.
Problem in Matrix3x4 constructors (Matrix3x4.h lines 172 and 186). If disable SSE code it work normal.

```
    Matrix3x4(const Vector3& translation, const Quaternion& rotation, float scale) noexcept
    {
#ifdef URHO3D_SSE_HIDE
        __m128 t = _mm_set_ps(1.f, translation.z_, translation.y_, translation.x_);
        __m128 q = _mm_loadu_ps(&rotation.w_);
        __m128 s = _mm_set_ps(1.f, scale, scale, scale);
        SetFromTRS(t, q, s);
#else
        SetRotation(rotation.RotationMatrix() * scale);
        SetTranslation(translation);
#endif
    }

    /// Construct from translation, rotation and nonuniform scale.
    Matrix3x4(const Vector3& translation, const Quaternion& rotation, const Vector3& scale) noexcept
    {
#ifdef URHO3D_SSE_HIDE
        __m128 t = _mm_set_ps(1.f, translation.z_, translation.y_, translation.x_);
        __m128 q = _mm_loadu_ps(&rotation.w_);
        __m128 s = _mm_set_ps(1.f, scale.z_, scale.y_, scale.x_);
        SetFromTRS(t, q, s);
#else
        SetRotation(rotation.RotationMatrix().Scaled(scale));
        SetTranslation(translation);
#endif
    }
```

**Comment by weitjong** [comment]
I have the same suspicion on those lines. Thanks for confirming it. Saving me the trouble.

**Comment by weitjong** [comment]
See https://github.com/urho3d/Urho3D/issues/2282. It looks like GCC has finally caught up with the UB.

**Comment by alex-rass-88** [comment]
I temporarily switched to clang. But I'll think about fixing it.

**Comment by weitjong** [comment]
> But I still don't get what's the point of SSE copying there.

I have no objection if you want to remove it. In fact I was this close to do that myself and not only for this class but all the value classes in the Math directory so that they become trivially copiable. What stopping me was I didn’t want to spend time to perform the regression/performance testing.

**Comment by weitjong** [comment]
Just commit a patch that does the minimal necessary to fix this issue.

**Comment by alex-rass-88** [comment]
Thanks.

**Comment by eugeneko** [comment]
Thanks. BTW, there was UB only in copy ctor.
Are changes in other ctors required due to some GCC bug?

**Comment by weitjong** [comment]
As I said, it is just a quick fix. I didn't spend time to really understand why the new GCC 8.x compiler optimization is not happy with the two ctor pointed out by alex-rass-88. If you read the GCC 8.x release notes it claims that the new GCC 8 series is differed from the previous releases in a number of ways. Those contributed SSE optimization code may be necessary in the past, but they might not work anymore on a newer breed of compiler which does better job on auto-vectorization than its predecessor. Seriously, I don't know for sure also without digging deeper.

The copy ctor and the assignment-op are changed to default instead of user-defined just to make the class becomes trivially copyable. I have explained before why this is better (at least to me) and to ensure we don't have any UB in relation to this class that may manifest itself in other ways later on.

**Comment by weitjong** [comment]
Reopen the issue as user has reported physics simulation problem with GCC 8.1.1. So, there is something else broken.

**Comment by alex-rass-88** [comment]
I'm still on the trip. I'll start experimenting in a couple of days.

**Comment by alex-rass-88** [comment]
The problem is repeated also on Windows using mingw 8.1.
I have not figured out the reason yet.

**Comment by alex-rass-88** [comment]
All demos with Physics broken.
![bug](https://user-images.githubusercontent.com/7008147/42091752-3169169e-7baf-11e8-9872-f72238fdda56.png)

**Comment by alex-rass-88** [comment]
I found problem. If disable GCC option "-ffast-math" all works.
