### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by 360CodeSafe** [urho3d/Urho3D#2331]
This is 360 CodeSafe Team, we found a suspicious dead code, like https://github.com/urho3d/Urho3D/blob/dff13213e61c3e958ceae41e8e09822c349f9c68/Source/ThirdParty/Box2D/Box2D/Collision/b2Distance.cpp#L536. The local variable `wBLocal` is never used, we think it should be deleted.

Please also confirm follow cases:

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/Bullet/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp#L197

- https://github.com/urho3d/Urho3D/blob/master/Source/Samples/39_CrowdNavigation/CrowdNavigation.cpp#L637

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L2485

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L2491

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L2598

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L2930

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L1823

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L1824

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L1825

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L1826

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L1871

- https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/StanHull/hull.cpp#L1872

- https://github.com/urho3d/Urho3D/blob/master/Source/Samples/40_Localization/L10n.cpp#L200

Sorry for the long and boring list : ). Since I'm unfamiliar with `Urho3D`, please forgive me if there is anything wrong with my description.

Qihoo360 CodeSafe Team

**Comment by weitjong** [comment]
I didn't check all those lines but it is not surprised to find unused variables or even other warnings/errors that normally can be reported by static analyzer because we intentionally do not want to perform any such fixes on our 3rd-party library source code. It is not our responsibility and at the same time we don't want to keep our local changes as minimal as possible so that upgrading the 3rd-party lib with upstream changes can be done more easily. The are two highlighted belongs to our samples, but they are not critical. Thanks for your report though.
