### ISSUE TITLE
Something wrong with AnimatedModel.

### ISSUE THREAD

**Issue by dudochkin-victor** [urho3d/Urho3D#2354]
I have a problem to import my model as Animated Model. I was created model in blender, rigged it and animated. And when i try to insert it into scene as static model - all fine.. but when i try to change in one line one word to other i see nothing..

1.  StaticModel@ object = objectNode.CreateComponent("StaticModel"); // works
2.  AnimatedModel@ object = objectNode.CreateComponent("AnimatedModel"); // dont

With "Jack" is all fine. 

I used:
- Blender 2.79
- Urho3D-Blender from github.
- latest Urho3D.

So WHAT I DO WRONG? Pls help.

**Comment by carnalis** [comment]
Hello,
Perhaps there is an error reported in the .log or console (F1)?

**Comment by Causeless** [comment]
I've had this same issue. 

It seems inconsistent, and can depend on performance, perhaps. I've also found that sometimes the model will not render if the camera is initially set up to be looking at the model, but that models outside the camera frustum during setup will later render correctly when they come into the camera view.

**Comment by Causeless** [comment]
My one certainly does not, I'm using skeletons imported from Rome Total War.

**Comment by dudochkin-victor** [comment]
Ok... I was found where the problem. Let me make a detailed tutorial how to export models from blender correctly. I ll publish it and u can repost it. ok?

**Comment by dudochkin-victor** [comment]
y of course i used standard tutorial for blender to create model with skeleton,, so i has a lot of bones, which hasnt a root of them. so urho cant to find the root of skeleton. (i hope i write correctly :) ).  in a short words --- user which exported their own model should use meta-skeleton with root bone. its more complicated but there are no other way (of course u can try to implement simple hack to find bone which named "root" :) )

**Comment by Causeless** [comment]
I'm still having issues here too, although I expect it's different. These issues seem to only happen when having a large count of animated models, but it occurs even with the Jack model and animations.

I can try to make a simple reproduction test project, however the issue seems dependant on the machine I run it on - when I try using a slower or older PC (or build in debug, thus making the software slower), issues will occur with animated models never appearing, but it works fine when building in release on my main PC.

I'll note that the current project I'm working on uses a relatively substantially modified version of Urho3D, but none of these modifications have touched the model components - and this issues occurred even before I made these changes.
