### ISSUE TITLE
warnings in Vector class

### ISSUE THREAD

**Issue by chenjie199234** [urho3d/Urho3D#2361]
i'm using the newest prebuild urho3d from sourceforge
there are a lot of warnings when i complite my project.
all warnings come from Vector.
there used to be none.
here is the warnings:
[warnings.txt](https://github.com/urho3d/Urho3D/files/2292560/warnings.txt)

**Comment by weitjong** [comment]
I am probably not the best person to comment on this issue since I am not a VS user and not familiar with it, but what you have described is not new and is a known issue for VS (see https://ci.appveyor.com/project/urho3d/urho3d/branch/master/job/rbbmwog134rtqet9/messages). I agree that it looks a little bit out of hand now, especially when building for 64-bit. Perhaps someone familiar with VS can help to fix those C4244. Perhaps using `auto` instead of `unsigned` data type may make MSVC happy and at the same time does not cause problem with GCC and Clang.

**Comment by SuperWangKai** [comment]
Duplicated: #2338
