### ISSUE TITLE
Loading material from MemoryBuffer assumes JSON

### ISSUE THREAD

**Issue by deakjahn** [urho3d/Urho3D#2395]
I try to load resources (materials in this specific case) from a `MemoryBuffer` rather than from files via the resource cache. It seems that `Material::BeginLoad()` assumes a JSON because it can't see any file extension telling it otherwise. Consequently, I get a "Could not parse JSON data" error message. The file is a XML, of course. The source suggests that with a failed JSON input, it goes on to check if it's XML but it doesn't seem to work.

**Comment by JSandusky** [comment]
Does the material actually load from XML? As in you're just getting an annoying log-message you don't want?

That's quite deep in calls and the JSON->XML fallback is just a big hack.

It would be more appropriate to add a mime-type to `Deserializer` (defaulting as binary) and implement in `AbstractFile` so that appropriate mime-types such as "text/xml" etc can be specified and the code can do the correct thing instead of relying on shark-jumping hacks.

**Comment by deakjahn** [comment]
No, it doesn't load at all.

I don't try to use it any more, either. Not only because of this, other problems pushed me to using .pak (but I'd be glad to see plain .zip files supported in the same way). I know I could subclass and implement it in C++ but I happen to be in C# using UrhoSharp where such things are not possible or would require a deeply coordinated effort between the two packages. Anyway, using .pak works but of course, is much less comfortable than a simple .zip that can be handled with any other usual tool.

**Comment by SuperWangKai** [comment]
May related - https://github.com/urho3d/Urho3D/pull/2422
