### ISSUE TITLE
.mdl file

### ISSUE THREAD

**Issue by WongKianTat** [urho3d/Urho3D#2434]
May I know what software i can use to create .mdl model? Does this engine support loading other type of 3d model?

KT

**Comment by weitjong** [comment]
The .mdl is a custom format, see https://urho3d.github.io/documentation/HEAD/_file_formats.html. The Urho3D project provides two importers, see https://urho3d.github.io/documentation/HEAD/_tools.html. There is one Blender exporter provided by the community, see https://github.com/reattiva/Urho3D-Blender.

For further questions, please ask them in our forum instead of here.
