### ISSUE TITLE
VS 2019 generate x64 project instead x32

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2456]
VS 2017 generate x32
```
cmake.exe ../Urho3D -G "Visual Studio 15" -DURHO3D_OPENGL=1 -DURHO3D_ANGELSCRIPT=1 -DURHO3D_LUA=0 -DURHO3D_STATIC_RUNTIME=1 -DURHO3D_SAMPLES=0 -DURHO3D_TOOLS=0 -DURHO3D_DOCS=0
```

VS 2019 generate x64 even with URHO3D_64BIT=0 option
```
cmake.exe ../Urho3D -G "Visual Studio 16" -DURHO3D_64BIT=0 -DURHO3D_OPENGL=1 -DURHO3D_ANGELSCRIPT=1 -DURHO3D_LUA=0 -DURHO3D_STATIC_RUNTIME=1 -DURHO3D_SAMPLES=1 -DURHO3D_TOOLS=0 -DURHO3D_DOCS=0
```

(I run commands from simple bat-files, not from Developer Command Prompt)

**Comment by weitjong** [comment]
Unlike other generators, VS generator needs to be told upfront to target which arch: win32 (old default) or win64. By the time our build script processes the `URHO3D_64BIT` build option it would be already too late. The workaround is to preprocess that build option in the provided convenience batch file which you did not use above.

Note that the provided batch file is also outdated if you use it with recent versions of CMake. This is because CMake has changed how these arch parameters is passed to support ARM/ARM64. Based on your description I would also bet that the new default is now x64 when the expected parameter is not given.

**Comment by UNDEFINED-BEHAVIOR** [comment]
With newer cmake you can specify arch with "-A" option.
> -G "Visual Studio 15 2017" -A x64
https://cmake.org/cmake/help/v3.15/generator/Visual%20Studio%2015%202017.html

Or just activate vcvars64/32/all.bat yourself before calling cmake

**Comment by 1vanK** [comment]
> -A Win32

It works, thanks!

**Comment by weitjong** [comment]
That is exactly I was referring to. I think it is time to update the batch file to catch up with CMake.
