### ISSUE TITLE
Fix web build using emscripten latest.

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#2497]
Doing a web build using latest emscripten chokes during a pre-process pass of the shell file when it encounters #!/usr/bin/env

@weitjong I can build your fork just fine with latest emsdk because you have committed some changes to fix this bug. Any chance of those changes being merged into upstream?

**Comment by weitjong** [comment]
It was part of the SDL 2.0.10 changes. I had originally plan to have other changes to the Engine as well to take advantage of the new game controller support, but I had lost lost the interest to continue since then, also partly because I have other pet project to work on in my spare time now. If you cannot wait, you can cherry pick the changes yourself to be merged to upstream.
