### ISSUE TITLE
Bug in bloom and bloomhdr shaders post 1.7 release

### ISSUE THREAD

**Issue by PsychoCircuitry** [urho3d/Urho3D#2542]
I had noticed that sometime after the 1.7 release the bloomhdr shader started looking awful, pixelated and not very “bloomy”. I spent some time looking into it today and discovered the cause.

The bloom shader uses the passed in uniform variables for inverse size and offset. Documentation for renderpath says these uniforms are case sensitive to the render target name. Well apparently the cases don’t match between the render targets and uniforms, so what was happening was just stacking pixelated textures with no blur.

The fix is simple, either capitalize the render target names in the render path xml or change the uniform definitions to lowercase.

I’m not sure what the preferred approach is as render targets seem to always be defined with lowercase names and uniforms always start c-uppercase.

This issue only occurred post 1.7 release.

The ldr bloom shader is also affected by this same issue.

**Comment by weitjong** [comment]
I prefer changing the render target names to match, but I am fine either ways. Could you help us submit a PR to fix this?

**Comment by PsychoCircuitry** [comment]
Submitted a PR. I changed the render target names, as it's one fix for both shader languages. Sorry for 3 commits to the bloom.xml file, still new to github.

**Comment by weitjong** [comment]
Thanks for your PR. We have other sample post-process beside bloom which I believe could also have the same issue[?], if not corrected. Now I actually wonder why it happened in the first place. In the master branch (after 1.7.1) we have changed the StringHash class to be case-sensitive in calculating the hash value. But how it relates to this bug is still unclear to me, I haven't got time to debug this yet.

**Comment by PsychoCircuitry** [comment]
Yeah, it looks like autoexposure and blur have the same issues as well. I will work on that soon.
