### ISSUE TITLE
Upgrade Bullet to 2.89

### ISSUE THREAD

**Issue by dsakurai** [urho3d/Urho3D#2550]
On my Mac, I get this error due to the Bullet library being old:
~~~
Source/ThirdParty/Bullet/src/LinearMath/btVector3.h:343:7: error: argument value 10880 is outside the valid range [0, 255]
      [-Wargument-outside-range]
                y = bt_splat_ps(y, 0x80);
                    ^~~~~~~~~~~~~~~~~~~~
/opt/projects/programs/urho3d/Urho3D-vcs/Source/ThirdParty/Bullet/src/LinearMath/btVector3.h:47:32: note: expanded from macro 'bt_splat_ps'
#define bt_splat_ps( _a, _i )  bt_pshufd_ps((_a), BT_SHUFFLE(_i,_i,_i,_i) )
~~~

If you have a look at the Bullet 3 repo, they fixed it by modifying this line in `LinearMath/btVector3.h`:
~~~
#define BT_SHUFFLE(x, y, z, w) (((w) << 6 | (z) << 4 | (y) << 2 | (x)) & 0xff)
~~~
https://github.com/bulletphysics/bullet3/blob/master/src/LinearMath/btVector3.h

I think Urho3D should upgrade Bullet3. Do you agree?

**Comment by weitjong** [comment]
Thanks for letting us know. Yes, we should upgrade. The real question is, who will have time to do it first. Once upgraded, we can remove these lines. https://github.com/urho3d/Urho3D/blob/master/CMake/Modules/UrhoCommon.cmake#L733-L738

**Comment by weitjong** [comment]
I have upgraded Bullet from 2.86.1 to 2.89 (still testing it in my fork repo). To my surprise the Bullet code base actually has also IK support. Somehow the last person who contributed the Bullet upgrade work from version 2.83.6 to 2.86.1 has not done a great job. Now I am in a dilemma because we already have another standalone IK library contributed by @TheComet. On one hand I want to quickly get my Bullet upgrade work merge to Urho3D upstream master branch without spending more time (nor that I have the expertise) to integrate the IK from Bullet. On the other hand I am afraid we are missing something important if we keep ignoring the IK code from Bullet, with all due respect the IK library that we currently have should be less mature than the one from Bullet. Any thought?

**Comment by TheComet** [comment]
If bullet has a better IK solver then by all means, use that. Using worse code out of courtesy towards me doesn't help Urho3D.

I will take a closer look at Bullet's solver and get back to you with pros/cons.

**Comment by TheComet** [comment]
Okay so it looks like someone hand-rolled their own IK lib like I did but for Bullet, and called it ```BussIK``` named after himself.

# Differences in Functionality

The main difference are the algorithms. BussIK and my library share none in common.

BussIK supports all of the Jacobian solvers (pseudo-inverse, transpose, DLS/SDLS). These require many hundreds (sometimes thousands) of iterations to reach a solution and can be somewhat unstable. I ran the demo to see what the quality was like and it looked fine. SDLS was the most stable while pseudo-inverse was pretty much unusable.

My library on the other hand implements FABRIK and analytical solvers which converge much faster. FABRIK converges within 10-50 iterations and the analytical solvers converge, well, immediately.

BussIK supports multiple end effectors and so does my library, so there's no difference here.

BussIK does not support constraints and neither does my library, also no difference here.

My library has a few extra features that BussIK does not have, such as setting the end effector's weight (influence), which is something that you really want to have for games.

# Differences in Code

I should point out that BussIK is NOT part of bullet itself, but is an external thirdparty library. It does not use any Bullet specific structures/classes nor does it make any effort to integrate with the rest of Bullet. This means that by downloading bullet you don't automatically get any IK functionality. Extra work needs to be done to interface the two with each other.

This is of course also true for my library.

I'm actually not even sure if the BussIK headers are available via any public interface. I only glanced at the build system and it doesn't look like the target gets installed inside bullet's include directory, but I might be wrong.

BussIK doesn't put anything behind a namespace. It uses very generic class names such as ```VectorR3``` or ```Node```. There is some danger of name collision with ```Urho3D::Node``` or possibly class names with other libraries Urho3D uses.

My library on the other hand exports a single public symbol called ```ik```. This name is also configurable from CMake.

# Conclusion

I feel like ```BussIK``` was written as a student's assignment and does the bare minimum. It would be nice to have Jacobian solvers in Urho3D, however, I feel that for games in particular, you really want to use FABRIK due to performance and stability.

Given that it's not actually part of bullet, I do not think it is worth replacing my library with this. If the plan is to replace my library then I would recommend finding a better inverse kinematic solver library instead.

Thoughts?

**Comment by weitjong** [comment]
@TheComet Thanks for the detail explanation. In that case we will keep thing as it is, as per your advised.
