### ISSUE TITLE
High DPI on D3D

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2557]
I noticed that we just set the graphics highDPI_ to match the argument in the D3D renderers. I was wondering if that should be changed to say that highDPI_ = false for those renderers? Either approach works for me, but I felt that if we aren't actually checking if we got a highDPI window, we should set it to false. If I'm not mistaken, the OGL renderer sets the flag based solely on whether SDL opened a high DPI window (logical size != actual size), so I feel that would be more consistent behavior between the APIs.

This was just from a brief look at the code while I was adding some logging for the high DPI flag, so I may be mistaken.

**Comment by weitjong** [comment]
AFAIK, we only have initial support for high DPI on MacOS platform. All other platforms will effectively have this flag reset to false. Even on MacOS the support is still not mature because at the time when it was added, none of maintainers actually had the Retina display to test it properly. I don't think thing has changed much since then.
