### ISSUE TITLE
Using as external lib:  incomplete types

### ISSUE THREAD

**Issue by ArcaneBlackwood** [urho3d/Urho3D#2624]
Im using the Arch package 'urho3d' without modification.  Upon compiling with `g++  -O2 -g -Wall -Wl,-z,now -lUrho3D -lSDL -I/usr/include/ -o Source/main.o Source/main.cpp`  I get many errors such as: 
```
/usr/local/include/Urho3D/Container/Ptr.h:223:19: error: invalid use of incomplete type ‘class Urho3D::Text’
  223 |             ptr_->ReleaseRef();
      |             ~~~~~~^~~~~~~~~~
...  error: invalid static_cast from type ‘Urho3D::Resource*’ to type ‘Urho3D::Font*’
... error: incomplete type ‘Urho3D::Font’ used in nested name specifier
```
Ive been going bonkers over this and I am completely lost, Ive tried compiling manually from source and I get the same error, Ive also tried many different arguments for gcc and even manually creating the urho library.  As you can tell Im not too great in this field, so any help is appriciated

**Comment by weitjong** [comment]
You didn't tell us what steps have you taken. There is no canonical way to build and use Urho3D library. And from the description you have given, it does not seem like you are following our online documentation for building and using the library. 

https://urho3d.github.io/documentation/HEAD/index.html

Since you are using Linux, you may want to try these steps below. Assume you have Rake/Ruby and cmake, GCC, and all the other prerequisites mentioned in the online docs properly installed.

In the directory where you have cloned the Urho3D repository.
```
[Urho3D] $ rake cmake && rake make
[Urho3D] $ NATIVE_BUILD_TREE=$(pwd)/build/native
[Urho3D] $ rake scaffolding dir=/tmp/myproject
[Urho3D] $ cd /tmp/myproject
[myproject] $ rake cmake URHO3D_HOME=$NATIVE_BUILD_TREE && rake make
[myproject] $ build/native/bin/Main
```
The last command should launch Ninja Snow War demo. If you still have questions, please raise them in our Forum and not in our Issue log.
