### ISSUE TITLE
MinGW64/Windows build script fails

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [urho3d/Urho3D#2666]
After updating my MinGW64 to the latest version of G++ compiler (10.1.0) build scripts from the master branch no longer work.
![image](https://user-images.githubusercontent.com/51226895/88166814-8de77f00-cc20-11ea-9d91-eb92f789f8fc.png)

**Comment by IlyaStuurFedorov** [comment]
This is what that build.make file looks like:
![image](https://user-images.githubusercontent.com/51226895/88168718-7958b600-cc23-11ea-9e29-f4a03a7e09fa.png)

**Comment by IlyaStuurFedorov** [comment]
Seems to be some kind of a problem with URHO3D_PCH

**Comment by weitjong** [comment]
The PCH has not been working correctly since we switch to C++11 standard. Unfortunately most of the compilers falling back silently, so nobody look at it closely. It should be an easy fix.

**Comment by weitjong** [comment]
I have made some changes in the build scripts in order to fix the PCH generation for most of the cross-compiler toolchains that I managed to get my hands on. The changes are available [here](https://github.com/urho3d/Urho3D/tree/upgrade-toolchains) in one of the dev branch. However, I could not test it on MinGW with GCC 10 myself, so I would appreciate if you can help to check the dev branch out to see whether it works OK for your new MinGW toolchain. Thanks.

**Comment by weitjong** [comment]
The aforementioned branch has been merged into master branch. I believe whatever the issue was should be fixed now. Closing this issue for now. Feel free to reopen if it is not the case for you.
