### ISSUE TITLE
Manual AngelScript binding is broken

### ISSUE THREAD

**Issue by YuriAzathoth** [urho3d/Urho3D#2744]
#### System Information
- Urho3D Version: latest/master
- Operating System: Windows 7 x64
- Compiller: gcc.exe (Rev6, Built by MSYS2 project) 10.2.0 x64
- Urho3D lib type: Shared

#### Detailled description
The engine is used as a shared library. Third-party components are written in C++ and manual bindings to AngelScript.
Link error started to occure after commit https://github.com/urho3d/Urho3D/commit/ef1dfe3417fed9e94a492e819df5dcb34faa6514 when I use `RegisterComponent` in my project. Before that everything worked fine.
Error message:
```
undefined reference to `Urho3D::SerializableGetAttributeInfo(unsigned int, Urho3D::Serializable*)'
```

**Comment by 1vanK** [comment]
There is not enough information.

**Comment by 1vanK** [comment]
Pls provide minimal project for reproduce

**Comment by YuriAzathoth** [comment]
https://github.com/YuriAzathoth/Urho3DASManualBindingBrokenDemo

**Comment by 1vanK** [comment]
In old bindins `static const AttributeInfo& SerializableGetAttributeInfo(unsigned index, Serializable* ptr) { ... }` was placed in APITemplates.h. Therefore, when you included this file in your app, this function was duplicated in your application.

In the current version, this function has been moved to cpp file. Therefore, when you compile the engine as shared, your application has no access to this function.

I will think about which option is better, but as a temporary solution you can replace in file Manual_Scene.h

```
const AttributeInfo& SerializableGetAttributeInfo(unsigned index, Serializable* ptr);
```
to
```
URHO3D_API const AttributeInfo& SerializableGetAttributeInfo(unsigned index, Serializable* ptr);
```

**Comment by YuriAzathoth** [comment]
Thank you

**Comment by 1vanK** [comment]
At the moment, I am modernize binding generator into templates to minimize the generated code and speed up compilation.
I faced such a problem that child classes can hide methods of the base class and this must be taken into account when generating. In other words, you can hide some methods in your component and when you call `RegisterComponent<...>(engine, "...");`  an error will occur. A prime example of this problem `template <class T> void RegisterUIElement(asIScriptEngine* engine, const char* className, bool isSprite = false)` that conataisn hack for registering Sprite.
Since the bind generator doesn't know anything about your code, the only correct way to create bindings for your code is to take the generated templates and modify them manually.
