### ISSUE TITLE
Error building: VS + shared + Win32

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2760]
The problem only occurs when compiling Shared x32 version of the engine with Visual Studio. 

```
cmake.exe ../Urho3D -G "Visual Studio 16" -A Win32 -DURHO3D_LIB_TYPE=SHARED -DURHO3D_OPENGL=1 -DURHO3D_ANGELSCRIPT=1 -DURHO3D_LUA=1 -DURHO3D_STATIC_RUNTIME=1 -DURHO3D_SAMPLES=1 -DURHO3D_TOOLS=0 -DURHO3D_DOCS=0 -DURHO3D_DATABASE_ODBC=1 -DURHO3D_GENERATEBINDINGS=1
```

The problem appeared in the following commits:

https://github.com/urho3d/Urho3D/commit/0e4d095cfabb61632ebe54d168d3689465445150

```
1>LINK : fatal error LNK1104: cannot open file '\WHOLEARCHIVE.obj'
```

https://github.com/urho3d/Urho3D/commit/3ba62f036e6bb7d51286ff1a6bfacb425e6d6460

```
1>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/FORCE' specification
1>gdi32.lib(GDI32.dll) : warning LNK4006: __NULL_IMPORT_DESCRIPTOR already defined in user32.lib(USER32.dll); second definition ignored
1>C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86\gdi32.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x23054
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6006: "link.exe" exited with code 1107.
```

@weitjong any ideas?

**Comment by weitjong** [comment]
I am able to quickly reproduce this locally on my Win7 VM. I think it has
to do with the removal of one of my old CMake hack specifically to let MSVC
to support SHARED lib type. I have replaced the hack with a proper linker
flag "/WHOLEARCHIVE". See
https://docs.microsoft.com/en-us/cpp/build/reference/wholearchive-include-all-library-object-files?view=msvc-160.
This flag closes the gap of MSVC linker compared with others. It has been
available since VS 2015. And since I have dropped support for VS 2013, it
should be no problem, at least that was what I thought. It turns out when
the arch is "Win32" (32-bit mode) then the linker does not recognize the
flag as it should [?], but everything is OK when the arch is "x64". I have
no idea why. Perhaps someone should confirm this with a minimal project
setup before filing a bug report to Microsoft. If you or someone else want
to put back the old hack, I have no issue with that. I personally will
probably not touch Urho3D (old) CMake build scripts again.

Note that our CI/CD workflow does not test 32-bit desktop Windows build
anymore, but it was not set up for other technical reasons.

**Comment by 1vanK** [comment]
Why is this option WHOLEARCHIVE needed? I compiled successfully without it.

**Comment by weitjong** [comment]
it is used to get as many symbols as possible from a static library when
building a shared lib.

**Comment by 1vanK** [comment]
Do you mean direct use of Bullet functions and the like?

**Comment by 1vanK** [comment]
Actually I can't build https://github.com/1vanK/Urho3DKinematicCharacterController (which uses direct calls of Bullet functions) with SHARED version of the engine even with WHOLEARCHIVE

```
1>CharacterController.obj : error LNK2019: unresolved external symbol "void * __cdecl btAlignedAllocInternal(unsigned __int64,int)" (?btAlignedAllocInternal@@YAPEAX_KH@Z) referenced in function "public: static void * __cdecl btCapsuleShape::operator new(unsigned __int64)" (??2btCapsuleShape@@SAPEAX_K@Z)
1>CharacterController.obj : error LNK2019: unresolved external symbol "void __cdecl btAlignedFreeInternal(void *)" (?btAlignedFreeInternal@@YAXPEAX@Z) referenced in function "public: static void __cdecl btCapsuleShape::operator delete(void *)" (??3btCapsuleShape@@SAXPEAX@Z)
1>CharacterController.obj : error LNK2019: unresolved external symbol "public: __cdecl btCapsuleShape::btCapsuleShape(float,float)" (??0btCapsuleShape@@QEAA@MM@Z) referenced in function "public: void __cdecl CharacterController::CreatePhysComponents(float,float)" (?CreatePhysComponents@CharacterController@@QEAAXMM@Z)
1>CharacterController.obj : error LNK2019: unresolved external symbol "public: __cdecl btPairCachingGhostObject::btPairCachingGhostObject(void)" (??0btPairCachingGhostObject@@QEAA@XZ) referenced in function "public: void __cdecl CharacterController::CreatePhysComponents(float,float)" (?CreatePhysComponents@CharacterController@@QEAAXMM@Z)
1>CharacterController.obj : error LNK2019: unresolved external symbol "public: __cdecl btKinematicCharacterController::btKinematicCharacterController(class btPairCachingGhostObject *,class btConvexShape *,float,class btVector3 const &)" (??0btKinematicCharacterController@@QEAA@PEAVbtPairCachingGhostObject@@PEAVbtConvexShape@@MAEBVbtVector3@@@Z) referenced in function "public: void __cdecl CharacterController::CreatePhysComponents(float,float)" (?CreatePhysComponents@CharacterController@@QEAAXMM@Z)
1>CharacterController.obj : error LNK2019: unresolved external symbol "public: void __cdecl btKinematicCharacterController::setMaxJumpHeight(float)" (?setMaxJumpHeight@btKinematicCharacterController@@QEAAXM@Z) referenced in function "public: void __cdecl CharacterController::CreatePhysComponents(float,float)" (?CreatePhysComponents@CharacterController@@QEAAXMM@Z)
1>CharacterController.obj : error LNK2019: unresolved external symbol "public: void __cdecl btKinematicCharacterController::setGravity(class btVector3 const &)" (?setGravity@btKinematicCharacterController@@QEAAXAEBVbtVector3@@@Z) referenced in function "public: void __cdecl CharacterController::CreatePhysComponents(float,float)" (?CreatePhysComponents@CharacterController@@QEAAXMM@Z)
1>CharacterController.obj : error LNK2019: unresolved external symbol "public: class btPairCachingGhostObject * __cdecl btKinematicCharacterController::getGhostObject(void)" (?getGhostObject@btKinematicCharacterController@@QEAAPEAVbtPairCachingGhostObject@@XZ) referenced in function "private: virtual void __cdecl CharacterController::FixedUpdate(float)" (?FixedUpdate@CharacterController@@EEAAXM@Z)
1>G:\MyGames\Kinemati\Build\bin\Game_d.exe : fatal error LNK1120: 8 unresolved externals
```

**Comment by weitjong** [comment]
No. We want to build a STATIC/SHARED Urho3D lib that contains the symbols coming from the engine as well as all the underlying 3rd-party static libraries in such a way that Urho3D library user just need to know the dependent app  is just dependent on a single Urho3D library, instead of specifying a list of all the 3rd-party libs. Without the whole archive linker flags, it may optimize away many symbols that Urho3D engine does not use directly. This is OK when you are building an app already, but it is a problem when we are actually still building Urho3D library and we want to preserve the symbols for the library users.

We do not use CMake transitive dependency management here because at that time we would like to say using CMake is not a must. Library user could use `pkg-config` tool or even manually specify where the include and where the lib in their own project in order to use Urho3D engine. But if someone else would like to rewrite the build system, I will say to go all the way with modern CMake. Let it manage the transitive dependency for us even when it means the library users will be locked in to use CMake. It is almost the case now anyway.

**Comment by weitjong** [comment]
Just saw your last comment. I only say we try to preserve as many symbols as possible.
