### ISSUE TITLE
Vulkan support please？

### ISSUE THREAD

**Issue by SoNewBee** [urho3d/Urho3D#2805]
It has been a long time since Vulkan API released.Urho3D project is so good and it is unbelievable that Urho3D doesn't support Vulkan for a long time.No offence,but I really think Urho3D is better than Godot in many aspect.

**Comment by eugeneko** [comment]
> it is unbelievable that Urho3D doesn't support Vulkan for a long time

Godot has paid full-time development team, Urho does not. So, it's not really "unbelievable".
I love Urho, but I am realistic enough to realize that if I want some feature, I have to either implement it myself or hire someone to get it done in my stead.

Having said that, I have long term plan to try integrating The Forge framework into Urho fork (cannot be main repo due to massive breakage of forward compatibility). And even with such massive breaking changes it would be huge task to add Vk support, so I won't make any promises here.

**Comment by SoNewBee** [comment]
> > it is unbelievable that Urho3D doesn't support Vulkan for a long time
> 
> Godot has paid full-time development team, Urho does not. So, it's not really "unbelievable".
> I love Urho, but I am realistic enough to realize that if I want some feature, I have to either implement it myself or hire someone to get it done in my stead.
> 
> Having said that, I have long term plan to try integrating The Forge framework into Urho fork (cannot be main repo due to massive breakage of forward compatibility). And even with such massive breaking changes it would be huge task to add Vk support, so I won't make any promises here. _But_ if you just want to see something Urho-ish with Vulkan, there is >0% chance it would happen in a couple of years.

Yes,that is what I want to talk about.Godot got plenty of support,but the efficient and function of it is far more less than Urho3D in many aspect.Urho3D got higher quality code,faster speed and etc.And the support that urho got is far more less than Godot.I admire your group for the sprite of you.People like me just do not want to see this project can not keep up with the times.What's more,I strongly suggest Urho3D or someone write a tutorial for beginners and a detailed API reference like panda3d.
Maybe I raised many unrealistic suggestion,if so,I apologize.
