### ISSUE TITLE
Material Shader Parameter Animation Not Reset In ResetToDefaults()

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2826]
As best I can tell, `Material::ResetToDefaults()` clears and resets the `shaderParameters_` but it does not clear the `shaderParameterAnimationInfos_`.

**Comment by weitjong** [comment]
Most probably it is  a bug since when the shader parameter animation was introduced by Aster 8 years ago. From the commit history you can see that Aster's commit did not touch the `Material::ResetToDefaults()`. The latter was last changed by Lasse about 9 to 10 years ago. My point is, the `shaderParameterAnimationInfos_` was not added by the original author of the engine. I agree with you that it should be cleared like the rest. If you submit as PR, I will help to merge your fix.

**Comment by PencilAmazing** [comment]
I could give it a try.

**Comment by SirNate0** [comment]
Sorry, it got pushed to the back burner. I think Material should also update (clear) its event subscriptions when reset, otherwise it would be listening to events it no longer acts on. Added a fix for that with #2843.
