### ISSUE TITLE
Global illumination(radiosity), lightmapping and light probes?

### ISSUE THREAD

**Issue by torugok** [urho3d/Urho3D#404]
I think which this things are fundamental for mobile development, and I suggest the implementation...
http://en.wikipedia.org/wiki/Radiosity_(computer_graphics)
http://docs.unity3d.com/Manual/LightProbes.html
http://docs.unity3d.com/Manual/Lightmapping.html
(Sorry for bad english)

**Comment by dragonCASTjosh** [comment]
Once I finish with PBR I may look into implementing both dynamic GI and static Lightmaps. I think it will be a fun project to try

**Comment by zzz125** [comment]
unreal 4.11 use this for light backing:
https://embree.github.io/
https://www.unrealengine.com/blog/unreal-engine-4-11-released

it seems fast and opensource

**Comment by boberfly** [comment]
Hi @zzz125 
Unreal is still using their lightmass baking system, Embree is there to purely doing BVH builds (accelerated structure for geo) and SIMD-accelerated raytracing instead of using their own one, so it's not really rendering with Embree per-se, like how V-Ray and other renderers uses Embree.

Something suggested by myself and I think @JoshEngebretson of AtomicEngine, using [Cycles standalone](https://wiki.blender.org/index.php/Dev:Source/Render/Cycles/Standalone) would be a better choice for lightmap baking as it already has functionality to do baking through Blender. The standalone just needs to be patched to work this way (and perhaps not use the XML API but rather use the [C-API](https://github.com/jesterKing/CCSycles) and maybe share Urho3D's vertex shadow buffers and convert materials to Cycles equivalents, same for lights that are tagged for baking or indirect). It's also a back-burner project of mine :) so the first one to do that would be great!

**Comment by hdunderscore** [comment]
That does sound like a better way. You could probably even automate the UV2 generation with the Blender Texture Atlas addon.

**Comment by mattbenic** [comment]
@boberfly I need to look into this for our artists. We're working in Atomic and finding getting lightmaps generated externally matching up to scenes assembled in Atomic to be a real challenge. So after a brief chat about it with @JoshEngebretson I'm going to start digging into Cycles

**Comment by boberfly** [comment]
@mattbenic nice! From memory the things that I was going to investigate was seeing how the Blender interface works for texture baking like what function is used from python or whatever, and then adapting this to the standalone runtime of Cycles so that it uses this function instead of the default perspective camera render entry point.

The next thing was to make Cycles just access Urho's scene/mesh formats or convert directly to what Cycles wants (alternatively you could just dump to its XML format, but it might get heavy). Then to drop off the dependency of OIIO+OSL, make it uses Urho's Image class instead (I'd keep OIIO myself if it is just a pipeline tool, but if I was running Cycles in the runtime itself if you were to use it like Enlighten middleware, I'd do this).

Also depending on if you're going to bake from original source assets like 16-bit high-res EXR textures and don't have large RAM machines, I believe the only way to make Cycles use texture caches is to go CPU-only and OSL-only, as this path uses OIIO's texture cache. The downside is no GPU accel and you can't use SVM shader nodes.

Good luck!

**Comment by mattbenic** [comment]
Thanks, yeah I think I'll need all the luck I can get :)
