### ISSUE TITLE
Auto generated bindings for scripts

### ISSUE THREAD

**Issue by sharpdigger** [urho3d/Urho3D#490]
Script binding is manually generated. Some low-level classes and methods are not exported. We have to handle two (for now) or more script languages and add bindings to them. There should be some way to auto generate all the glue layer so we can even write the game using script only.

**Comment by billyquith** [comment]
:bulb: Another suggestion is to add reflection and expose the C++ object manually. This is similar to what you have in C#.

You might use a library like [CAMP](https://github.com/billyquith/camp). This fork is one where I removed the Boost dependency.

The idea here is that you declare the parts of your C++ API that you would like public, e.g. 

```cpp
camp::Class::declare<Person>("Person")
    .constructor<std::string>()
    .property("name", &Person::name)
    .property("age", &Person::age, &Person::setAge)
    .function("speak", &Person::speak)
    ;
```

Then, because you have reflection, you can generate a binding for your language on the fly (as a pre-game, once only process). Each language then needs a reflection-reading binder instead of a binding. You could also add auto property inspection for objects exposed.

**Comment by kkimdev** [comment]
FYI: not a script binding, but I'm trying to generate Rust binding for Urho3d C++ API using https://github.com/servo/rust-bindgen .  I've noticed few bugs that need to be fixed so I filed these issues:

- https://github.com/servo/rust-bindgen/issues/402
- https://github.com/servo/rust-bindgen/issues/404
- https://github.com/servo/rust-bindgen/issues/405

They are all minor, and I could successfully compile if I just comment out the few functions affected by those bugs.

**Comment by kkimdev** [comment]
@emilio FYI

**Comment by devmacmari** [comment]
@kkimdev sorry to bother you, but do you have some sample rust+Urho3D projects I can look into? using rust + urho3d seems to a good idea 👍

**Comment by kkimdev** [comment]
@devmacmari Sorry but I switched to Oryol engine and for now I'm just using straight C++ for my project :(
