### ISSUE TITLE
Build system refactoring

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#556]
This issue will be used to track the build system refactoring process. The issue description here will be kept updated to reflect what have been done and what are planned to do next, so far. You are welcome to comment to add or reject the planned items. Only items that made into the list below counts.

Succeeded
=========
- Shell scripts and batch jobs require external user input to determine the build tree location, similar to cmake-gui.
- Collapse the project logical structure so that the repo root is the CMake's source tree. The build tree location is totally user defined and not being assumed. The project physical structure will be kept as it is.
- Add another engine parameter to set the location of the asset directory (which contains the CoreData and Data subdirs).
- Re-explore new approaches to configure native tool building while configuring for cross-compiling LuaJIT library build so that both native and cross-compiling targets can be built in one build process.
- Creating an SDK-like include directory structure.
- Remove the existing abstraction that makes headers appear to be flatten. The implementation file will now include the header file from its corresponding physical sub-directory where it belongs to. The header file will now use a relative pathspec to include other header files.

Failed
=====
nil

Planned
=======
nil

**Comment by weitjong** [comment]
@cadaver, MSVC should be able to build now with the new build system. I have tested it with VS 2013 on Win7 (with and without MKLINK privilege). As explained in ealier comment, when wihout MKLINK then the buildsystem would fallback to use file copy in the library post-build step. i.e. the copying happens as necessary when the corresponding library is being built. This is to avoid stale version of the header files in the build tree.

I also find out that MSVC does not handle the relative include pathspec correctly, or at very least not the same as GCC and Clang. I come out with a workaround solution to fix this problem. You may want to review these:
https://github.com/urho3d/Urho3D/blob/buildsystem/Source/Urho3D/CMakeLists.txt#L82-L88
and
https://github.com/urho3d/Urho3D/blob/buildsystem/Source/Urho3D/LuaScript/CMakeLists.txt#L78-L84
to see whether you are OK with the workaround. I am not familiar with MSVC, so may be you know a better way to solve it.

BTW, Happy New Year!

**Comment by cadaver** [comment]
Verified the Windows build working now, thanks!

The "workaround" include thing is slightly not-nice, but at least it doesn't have to copy any extra files around. I currently see no better way to do that.

In my playground engine Turso3D I've taken the approach of strictly relative include files within the engine, for example #include "../IO/File.h". It doesn't have an SDK install step as such yet, but when it does, it will likely keep the include subdirectory structure, so clients would have to do #include <Scene/Scene.h> instead of just #include <Scene.h>

It's worth considering if the same structure would be appropriate for Urho3D too, instead of flattening the include files for the SDK. It's slightly more work for clients as they have to remember the subdirectories the files come from, but then the include directory structure would be same for the engine build and SDK use, and the engine build would not require each engine subdirectory to be added as an include directory. However, as that breaks existing include statements for all clients, I'm not insisting on that change.

**Comment by weitjong** [comment]
If I understood you correctly then you want to throw away the abstraction between the physical layout and the logical layout of the project structure. The installed include dirs appear to be flatten because currently we do have CMake constructs to make them appear flat logically. I thought that what we want long time ago :) To throw away this abstraction layer, in order to see the physical layout directly, we literally just need to throw away some of the constructs in our existing CMake build scripts instead of adding more constructs. In fact I could foresee that we could even delete all the CMakeLists.txt for the engine subdirs. However, I am not sure which one is better to library user: a flatten logical view or a hierarchical physical view, because we do have a lot of subdirs.

I would like to hear the opinions from others too. I intend to wrap up this one soon as it has taken more time than I anticipated. We can shape it anyway we like while it is still hot.

**Comment by dervus** [comment]
Random user of the library is here.

IMHO, that include path abstraction is actually a bad thing because it complicates configuration of code navigation, completion, and analysis tools. In my personal case, I'm forced to manually list all the include paths within Urho's git source tree for my toolset. Ideally, there should be only one `-I` for the whole library.

I also believe paths like `#include <Urho3D/Scene/Component.h>` are better, since they give a clear view of which part of the library this header belongs to.

**Comment by weitjong** [comment]
Ok. I buy it. Earlier I had a concern that library users will not only have to remember which header to include but also have to remember from which part of the library the header belongs to after this change. But after considering more about it, I believe most users would simply just copy-paste the ```#include``` statements from one code to another. i.e. once they get a hang of it then it would become natural. I will add this into the planned item. Hopefully, this will be the last big ticket item in this issue.

**Comment by weitjong** [comment]
Progress update - the include path abstraction is removed now. I have not checked the build with MSVC on Windows yet. With the abstraction removed, I hope MSVC is able to handle the relative include pathspec now. So, I have removed the "workaround" that I have introduced earlier.

@cadaver, let me know if you are OK for the merging of this branch. Thanks.

**Comment by dervus** [comment]
What's about third party libraries? I've just looked through buildsystem branch and noticed that include paths for most of them (not all) doesn't conform the physical file layout. I mean there are `#include <AngelScript/angelscript.h>` for example, but the real file location is `AngelScript/include/angelscript.h`

**Comment by weitjong** [comment]
No, that's different. The include path for the third party libraries are more the decision already been made by their developers. If the lib uses relative include paths internally in their header files then we can get away with it to relocate them to where we want during install step. But more often than not, this is not the case.

**Comment by weitjong** [comment]
I give up on MSVC. The "workaround" is still need some how. I will commit some more changes to fix the MSVC build soon.

**Comment by cadaver** [comment]
Thanks for the effort again! Verified a successful MSVC2013 compile. I believe this is good to merge. I can look into the workaround path too now that the includes have been normalized.

Include paths like <Urho3D/Scene/Scene.h> are very unambigous and will be excellent for example to the tundra-urho3d project, which has "existed on damnation's edge" and made some nasty hacks to ensure that it distinguishes between its own Scene.h and Urho's.

**Comment by dervus** [comment]
I didn't meant third party include paths should be relative. They shouldn't of course. I meant that you've changed these include statements by adding library names into them.

Current master branch:
[Script.cpp#L34](https://github.com/urho3d/Urho3D/blob/ce28af535751ec375f7aac3af7a44ce0c9de4d06/Source/Engine/Script/Script.cpp#L34)
[PhysicsWorld.cpp#L41-L48](https://github.com/urho3d/Urho3D/blob/c1ea1f9e0637747f4e9c2aebe95fbfe5f1f817cc/Source/Engine/Physics/PhysicsWorld.cpp#L41-L48)

Current buildsystem branch:
[Script.cpp#L34](https://github.com/urho3d/Urho3D/blob/b3ecf92d818a56fbfa3e5494aaae24e90fce539d/Source/Urho3D/Script/Script.cpp#L34)
[PhysicsWorld.cpp#L41-L48](https://github.com/urho3d/Urho3D/blob/b3ecf92d818a56fbfa3e5494aaae24e90fce539d/Source/Urho3D/Physics/PhysicsWorld.cpp#L41-L48)

I think I understand the reason, but there is an issue. There may be include statements within libraries' own headers that expect to have same include search paths as they were in the master branch. [There is Bullet's btSoftBody.h for example.](https://github.com/urho3d/Urho3D/blob/02512cecf928c89863d1c5ec6874e5f4abcfaeb6/Source/ThirdParty/Bullet/src/BulletSoftBody/btSoftBody.h#L25-L26) I know it's not used by Urho yet, but anyway such situation is possible for every third party library. So if your intent was to provide single `-I` for the whole SDK, I suppose it has problems.

**Comment by weitjong** [comment]
Well, that is exactly one of the reason of this refactoring. In the master branch, we include the headers from 3rd party libs directly from its source code. In the new buildsystem branch, all the 3rd party lib's headers are "installed" in the build tree, so when building Urho3D library, we can reference them like an installed SDK. Subsequently, after Urho3D library is built, we too "installed" Urho3D headers into the build tree so that the library user's code can reference the Urho3D library as if it is also an installed SDK. I have opted to use the <LibName/header-name.h> syntax, like <Urho3D/Urho3D.h>. For consistency sake, I also change the include path to 3rd party libs to use the same syntax.
```#include <angelscript.h>``` becomes ```#include <AngelScript/angelscript.h>```
```#include <kNet.h>``` becomes ```#include <kNet/kNet.h>```
I hope that clarifies.

**Comment by dervus** [comment]
Yeah, I got that. Now I'm taking about include search paths. :smile: There is a real example. `PhysicsWorld.cpp` includes `Bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h`, which includes `LinearMath/btAlignedObjectArray.h`. Obviously this makes us to register both `${INCLUDE_DIR}/Urho3D/ThirdParty` and `${INCLUDE_DIR}/Urho3D/ThirdParty/Bullet` as include search paths.
So if I understand you correctly, your idea was about a single include search path for all third party libraries, and it may not work in case of Bullet. This can be fixed by changing Bullet's headers as well, but it looks like a really bad idea.

**Comment by dervus** [comment]
> See https://github.com/urho3d/Urho3D/blob/buildsystem/Source/Urho3D/CMakeLists.txt#L131-L147.

Ah, it's clear now. Thanks for the explanation and your work on this!

**Comment by weitjong** [comment]
You are all welcome. If there are no more objections then I will start to work on the merge.

**Comment by aster2013** [comment]
great, please move debugnew.h to urho3d folder.

**Comment by weitjong** [comment]
Yes, that makes sense. We can do that directly in the master branch after the dust has settled down. I have made a few tweaks in the RPM and DEB packaging logic and I expect to get some teething problem as usual.
