### ISSUE TITLE
Just can't get started.

### ISSUE THREAD

**Issue by xpol** [urho3d/Urho3D#604]
I have tried to build Urho3D under MacOS 10.10 (for desktop and iOS) and Windows 7 (VS2013) none of them succeed.

Build errors under MacOS is `Undefined symbols for architecture ...`.

Build errors under Windows is just can't find <SDL/SDL.h> etc...

I have tried to build Urho3D for weeks, but never succeed, this stops me from further learning and using Urho3D.

**Comment by weitjong** [comment]
I think you have to be more specific than that. Try to elaborate what did you do and what was the exact error. Thanks.

**Comment by meiry** [comment]
i dont know if its related but i can't build it still for ios 8.2 device in mac 
see this : 
https://github.com/urho3d/Urho3D/issues/498

**Comment by weitjong** [comment]
Until we get the full details from OP, there is no point to speculate but I highly doubt that it relates to your specific issue.

**Comment by meiry** [comment]
sure,just frustrated i can't start develop with the engine .
also i didn't saw any ios device examples

**Comment by xpol** [comment]
1. in Urho3D porject root run `./cmake_macosx.sh Build.MacOS -DURHO3D_LUA=1 -DURHO3D_ANGELSCRIPT=0 -DURHO3D_LIB_TYPE=STATIC`
2. open generated Xcode project
3. build
4. failed error: ` Undefined symbols for architecture x86_64: "_FT_Done_Face", referenced from:...`
5. set options Build Active Architecture Only to `No`
6. build
7. same error as above.
8. Select running target to `My Mac (32-bit)`
9. build
10. error:`Undefined symbols for architecture i386: "_FT_Done_Face", referenced from:...`

**Comment by weitjong** [comment]
For MacOSX build, this begins to sound like a duplicate issue of #498 (as suspected by @meiry). Unfortunately, we do not have definite fix to that issue. We have conflicting reports from different user that everything is fine on Xcode 6.1. Personally, I am not able reproduce any of the errors on my "good old" Xcode 5.1 running on Mountain Lion still in a VirtualBox. Following the steps above, build the Urho3D project successfully on my VM. We also do not have any errors on our CI build which uses Xcode 6.1 (see a sample build log [here](https://travis-ci.org/urho3d/Urho3D/jobs/46694660)).

At this point we can only confirm that there could be a problem with our project build configuration but until we could better understand the root cause from the information you give or that we could reproduce the error ourselves then there is little we can do for now to fix it.

**Comment by xpol** [comment]
I finally figure out that for OS X Yosemite 10.10.1 with Xcode 6.1.1:

The key is `OSX_DEPLOYMENT_TARGET` and `URHO3D_LIB_TYPE`.

OSX_DEPLOYMENT_TARGET  \  URHO3D_LIB_TYPE | STATIC | SHARED
-------------------------------------------------------------------------|------------|-------------
10.10 (default for Xcode 6.1.1 on OS X 10.10)                                       | Fail       | Fail
10.9                                                                                 | Fail       | Succeed   

That is must specify `OSX_DEPLOYMENT_TARGET` to `10.9` (or lower maybe) and `URHO3D_LIB_TYPE`  to `SHARED` for OS X Yosemite 10.10.1 with Xcode 6.1.1.


eg.

~~~~
./cmake_macosx.sh path/to/build/tree -DURHO3D_LIB_TYPE=SHARED -DOSX_DEPLOYMENT_TARGET=10.9
~~~~

**Comment by xpol** [comment]
I think above information about OS X Yosemite 10.10 with Xcode 6 should documented in [Building Urho3D](http://urho3d.github.io/documentation/HEAD/_building.html).

The next issue if for Windows, I'll try to explain later.

**Comment by xpol** [comment]
Update: as SDL requires OS X 10.5. So set `OSX_DEPLOYMENT_TARGET` to `10.4` would not work.
And I tested `10.5` and it works.
So should be valid set `OSX_DEPLOYMENT_TARGET ` to any of `10.5`, `10.6`, `10.7`, `10.8`, `10.9`.

**Comment by xpol** [comment]
Just checked Windows 7 with VS2013 build errors are just sometimes can't access custom build script in temp dir. And build again would fix it.

**Comment by meiry** [comment]
@xpol 
thanks for your time .
can you check on ios , if you have iOS device ? 
im very interested in solve this linking error 
Thanks!

**Comment by weitjong** [comment]
> In Apple world there is not such thing "old compiler" Apple always force you to use the new one.
I think I will decide what is suitable for my need on my own piece of hardware. But I can understand why one would have to play along with them just so that the app is being approved.

@xpol, your finding is still rather interesting for me to read. A few months ago the CI builds were actually configured to build to target the latest Mac OS X being installed on the host (in this case 10.9) and the build were also completed successfully then for both STATIC and SHARED. We later changed the configuration to target 10.8 due to a user demand (see https://github.com/urho3d/Urho3D/issues/447). The point I want to make is, building Urho3D to target 10.9 was a non issue then.

Let me see if I can get hold on an actual Mac hardware with the latest OS X and Xcode installed sometimes this week.

**Comment by cadaver** [comment]
I think it's finally time I update my OSX & Xcode to latest too and see what trouble I run into :)

**Comment by meiry** [comment]
@cadaver
please also iOS device ...

**Comment by weitjong** [comment]
Until then here are the CI test results targeting OSX 10.9 and 10.10, respectively. All green.
https://travis-ci.org/urho3d/Urho3D/builds/46852272
https://travis-ci.org/urho3d/Urho3D/builds/46854474
So far our Travis CI build results have been fairly accurate in this regards.

> The point I want to make is, building Urho3D to target 10.9 was a non issue then.

It **is** still a non-issue now.

**Comment by weitjong** [comment]
I managed to get a Mac Mini and upgraded to OS X 10.10 (Yosemite) and also upgraded to Xcode 6.1.1. So far I have no issue with native build targeting 10.10. Tried STATIC and SHARED on both 64-bit and 32-bit builds. Additionally I am able to do iOS build too with Xcode 6.1.1 targeting 8.0. However, I encounter the orientation issue which is already reported in #553.

I think we should rest our case on this one.

**Comment by meiry** [comment]
that leave me in the dark ... 
god knows what is wrong with my builds ...

**Comment by weitjong** [comment]
I have done nothing special on my build really. The log output that I got are similar to the one I observed from Travis CI build result (including those build warnings).

Here are what I have done, roughly, after upgrading the OSX and Xcode.
- Install homebrew and use brew to install cmake 3.1.
- Check that Ruby and Rake are already installed on the host, so leave them as they are.
- Git clone Urho3D.
- Generate the build tree and build Urho3D using the rake tasks.
```rake cmake macosx URHO3D_LUAJIT=1 URHO3D_LUAJIT_AMALG=1 URHO3D_SAMPLES=1 URHO3D_TOOLS=1 URHO3D_LIB_TYPE=STATIC URHO3D_64BIT=0 && rake make```.
- Try all the four combo STATIC/SHARED/32-bit/64-bit. Verify the binaries are executable and have the right arch using ```file``` and ```otool``` commands.

**Comment by xpol** [comment]
my cmake is 2.x I guess. I'll check tomorrow.

**Comment by meiry** [comment]
@weitjong Thanks!
well for sure i have cmake 2.8 something .. 
and i didn't execute any thing that called "rake"
only the cmake_ios.sh with the -DURHO3D_SAMPLES=1

**Comment by weitjong** [comment]
I thought it is clear that you should always use the latest CMake version to match with latest Xcode. Perhaps we should have stressed that in our documentation.

Those two rake tasks are newly created in the new build system. I just explained what I have done. You don't have to use it to build Urho3D. @meiry your last command is valid and equivalent to what I have done.

**Comment by xpol** [comment]
After upgrade to cmake 3.1 and install xcpretty every thing goes well except a lots of warnings like below: 
~~~~
2015-01-15 09:16:41.386 xcodebuild[10277:97427] warning:  The file reference for "Bin/CoreData" is a member of multiple groups ("Urho3DPlayer" and "Resources"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
2015-01-15 09:16:41.387 xcodebuild[10277:97427] warning:  The file reference for "Bin/Data" is a member of multiple groups ("Urho3DPlayer" and "Resources"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
2015-01-15 09:16:41.387 xcodebuild[10277:97427] warning:  The file reference for "Bin/CoreData" is a member of multiple groups ("01_HelloWorld" and "Resources"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
2015-01-15 09:16:41.387 xcodebuild[10277:97427] warning:  The file reference for "Bin/Data" is a member of multiple groups ("01_HelloWorld" and "Resources"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
2015-01-15 09:16:41.388 xcodebuild[10277:97427] warning:  The file reference for "Bin/CoreData" is a member of multiple groups ("02_HelloGUI" and "Resources"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
...
~~~~

BTW. The xcpretty is required (or preferred?) to build the project as well.

**Comment by xpol** [comment]
For iOS build, is LuaJIT not supported? And does LuaJIT support 32 and 64 bit iOS build?

by running `rake cmake ios URHO3D_LUAJIT=1 && rake make ios target=ALL_BUILD sdk=iphonesimulator` I got:

~~~~
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution CMake\ Rules /Users/xpol/Workspace/ios-Build/Source/ThirdParty/LuaJIT/Urho3D.build/Debug-iphonesimulator/buildvm.build/Script-46DFB69D087A4E55A193B5F6.sh
(1 failure)
~~~~

**Comment by friesencr** [comment]
ios doesn't allow jits or dynamically generated code

**Comment by xpol** [comment]
@friesencr As http://luajit.org/install.html said, LuaJIT on iOS should be used as pure interpreter which is faster that plain Lua.

~~~~
the JIT compiler is disabled for iOS, because regular iOS Apps are not allowed to generate code at runtime. You'll only get the performance of the LuaJIT interpreter on iOS. This is still faster than plain Lua, but much slower than the JIT compiler.
~~~~

**Comment by weitjong** [comment]
@xpol The Xcode 6 warnings has been documented in issue #606. At this point we are not sure yet whether it is an CMake/Xcode generator bug or it is caused that Xcode 6 doing things differently than Xcode 5 (as in CMake has yet to adapt it) or it is something due to our own fault (although we don't get these warnings on Xcode 5).

The xcpretty is a filter to address the verbosity of the 'xcodebuild' tool from its standard output stream. You only need it when you use 'rake make'. If you use the Xcode itself to build the generated project in the build tree then you don't need this filter. In Xcode it knows how to "fold" the build log. But I think we could also make xcpretty becomes optional. So, only perform the filter when it is installed.

Regarding LuaJIT on iOS. At the time we migrated LuaJIT makefile into our CMake build rules, we were told not to bother with iOS platform. So we didn't. But I believe we could make the interpreter part working on iOS platform if we want to. Having said that, there is not much point to do so now because the LuaJIT does not support aarch64 and arm64 ABI yet. See http://comments.gmane.org/gmane.comp.lang.lua.luajit/5663.

**Comment by xpol** [comment]
@weitjong Thank you so much.

**Comment by meiry** [comment]
@weitjong 
Thanks , i will try to build it today , 
is there any log or output that the cmake generate so i can post it here if its still dons't work ?

**Comment by weitjong** [comment]
What you see in the CMake output is its log when you save it to a file. But I am afraid in this case it won't help you much. Xcode is known to change its internal from version to version, letting CMake to play catch up forever. The CMake output won't be able to show anything unusual.

**Comment by meiry** [comment]
Thanks, well im sure will update my findings 
Thanks again!

**Comment by meiry** [comment]
@weitjong 
Good news ! its working ! 
i did the step by step installation after uninstalling the cmake 2.8 
and its working and dyploing into device .
but there is new problem that i know it from gameplay3d :
http://www.gameplay3d.org/forums/viewtopic.php?f=3&t=2196&sid=2daf632d03d20b462be9bf556d64f30b&p=7518#p7518

now it is with Urho3d is there any fix to it ?
look how it looks in iphone 5 
![img_3149](https://cloud.githubusercontent.com/assets/1107316/5774362/8aff723c-9d75-11e4-9b82-6b64242aaeba.PNG)

**Comment by weitjong** [comment]
Glad to hear that. Re orientation issue, it has been reported on our Issues list too.
