### ISSUE TITLE
Install destinations on Linux.

### ISSUE THREAD

**Issue by spongebob** [urho3d/Urho3D#620]
Previous to this morning everything installed in /usr/local/share/Urho3D, except the libs that were put in /usr/local/lib64. Now, it isn't completely correct to put everything under share, but whatever, at least it's contained.

This morning I find that the demo binaries, tool binaries and scripts go under /usr/local/bin, that is correct and good. As is putting headers under /usr/local/include. What is not good is that Data and Core data is also put under /usr/local/bin.

Ideally, it would look something like:
$PREFIX/bin <- binaries, not data
$PREFIX/include <- headers
$PREFIX/lib (or lib64) <- both shared and static libs
$PREFIX/share <- data. put Data and DataCore here along with docs and what not

**Comment by weitjong** [comment]
Thanks for your feedback. We could do that, however, that would mean all the binaries in the /usr/local/bin will not run successfully out of the box. This is because by default our executable expects to find the Data and CoreData in the same directory where the executable is located. But I understand why the objection on putting data dirs in the /usr/local/bin.

**Comment by spongebob** [comment]
That is because you have designed the path handling for engine initialization a bit weird. I will post a suggestion for a fix for that soon, I have something else bugging me right now. In short, you shouldn't add paths automagically, it should be up to the API user. Normally, on Unix anyway, the only path the API knows is a default (or several) set at buildtime by the build system. The user can use that path if he wishes, but is not forced to use it or set any path at all. You also leave little room for people to use the engine without the resources provided with Urho3D. Even though I manually turn the paths off, I get log warnings for resources I dont need. I'll get back on this once I sort a few other things out.

The filesystem structure I referred to is the one and only way to do it right on Unix. There's also the "opt" alternative, which ever works fine tbh. Any upstream package maintainer will have to change all this manually.

**Comment by weitjong** [comment]
Installing the CoreData and Data was an oversight as previously the DEST_RUNTIME_DIR was set to "share/Urho3D/Bin". With the DEST_RUNTIME_DIR now set to "bin", the installation destination for the CoreData and Data has to be readjusted, which I totally agree and it is fixed now.

As for the prefix path handling, you are welcome to send the PR to improve it. I just want to say that under no circumstances that the prefix path is being automagically added. The prefix path is user-defined. It will, however, defaulted to program dir (for backward compatibility) when the prefix path is not defined.

I have adjusted the Editor.sh and NinjaSnowWar.sh shell script to detect the existence of the resource dir in the installation destination and do the necessary so that at least these two scripts are run out of the box. The rest of the samples, however, will not run out of the box anymore. User would need to call, for example: ```01_HelloWorld -pp ../share/Urho3D/Resources``` or ```URHO3D_PREFIX_PATH=../share/Urho3D/Resources 01_HelloWorld```.

**Comment by weitjong** [comment]
Regarding the 'opt' as the install prefix path, the package maintainer will have to patch our CMakeLists.txt. I have peppered in our CMakeLists.txt some notes for them on how to patch. But until now, I am not aware of any distro package maintainers out there that are interested in our project yet. Correct me if I am wrong.

**Comment by spongebob** [comment]
They will be interrested in time. I've sent a suggestion in the forum on how to get rid of the automagic path (and resource) handling that would benefit both the API and future maintainers/distributors of Urho3D.

I realize the changes I have propsed are rather big, but it would be significantly better both user and maintainer and all the examples would work and data could go anywhere the sysadmin/maintainer wants.

**Comment by weitjong** [comment]
> I realize the changes I have propsed are rather big, but it would be significantly better both user and maintainer and all the examples would work and data could go anywhere the sysadmin/maintainer wants.

I think you are confusing about one thing. We don't configure our project just for Linux package. As of now our users are not even forced to install Urho3D SDK in order to run our executables. Our users can run the executables directly from the build free, if they want to. So, we would not want to hard code the path to the resource dirs in our code or anywhere else just so that they run fine when they are installed. As of now our resource dirs can already be put to anywhere the user wants them to be. Either I missunderstand you or you missunderstand the usage of the engine parameter.

When the time truly comes that we have package maintainers want to ship our package in their official repo, they can always download our source from GitHub and patch the code and our build scripts locally to their heart content before submitting the build job to their build farm. I don't think we have to worry about them. I am sure the maintainers know how to patch the source one way or another. I will be surprised if they could package other similar projects like Ogre3D without local patching.

**Comment by spongebob** [comment]
The samples binaries would run fine from ANY location on the system with what I'm proposing.

But the point is: many projects including my own handle paths very easily on ALL platforms. I'm quite used to cross compiling for Linux, Windows and Android and all my path handling is done in a flexible, portable and very usable way, the current Urho3D API for handling this just isn't as good. It could be, with minor modifications. You could still do it the way you like, your wrapper code to get the exact same setup you're using now is a dozen lines. Urho3D could even provide it for backwards compatibility.

Also, Ogre3D does NOT require patching for setting build time paths. Honestly, no project should and I haven't come across any project that does not have an option to set PREFIX.

**Comment by weitjong** [comment]
I think we are talking about different thing here. For sure I am not talking about install PREFIX, as we have CMAKE_INSTALL_PREFIX variable for that. If you have looked at Ogre source packages maintained by RedHat/Fedora distro, you will know what I meant by "patching".

**Comment by spongebob** [comment]
As far as I'm concerned, there's no "patching" involved in setting install dirs. And that PREFIX usually follows into a define or static symbol from which the API can find out where the install path is.

Anyway, I think you just don't get what I'm saying so I'll just stop saying it.

**Comment by weitjong** [comment]
Good then. So I can lock this useless issue.
