### ISSUE TITLE
Last commit in Allocator.h makes LogicComponent.h not able to find Urho3D.h

### ISSUE THREAD

**Issue by setzer22** [urho3d/Urho3D#627]
The title should say it all. Today the line

#include "../Urho3D.h" 

Has been removed brom Allocator.h, commit message was: "Avoid the include dirs hack for finding the Urho3D.h header."

It seems that Urho3D.h is now not reachable through includes from LogicComponent.h and thus the macro URHO3D_API is not defined. 

Adding #include <Urho3D/Urho3D.h> before including LogicComponent.h solves the issue

**Comment by setzer22** [comment]
The git log showed me the full commit message. It appears this is the intended behaviour and now it's the user's responsibility to include Urho3D.h somewhere in its code.

**Comment by MonkeyFirst** [comment]
RefCounted.h also missing the URHO3D_API and my project end compiling with huge counts of errors )

![123](https://cloud.githubusercontent.com/assets/9577466/5825843/31236518-a110-11e4-99e6-7a5bbe43f23c.png)


I'm manualy add #define URHO3D_API in the begining of refCounted.h and it again works and compiled as before.

**Comment by weitjong** [comment]
The idea is now lib users should include the Urho3D.h in their own project's code.

@cadaver, let me know if you think this is bad and I will revert the commit. I.e. Put the include dirs "hack" back.

**Comment by cadaver** [comment]
It seems a bit hazardous that a vital include is only reached via Precompiled.h and not explicitly included by the headers that need it. For me it's not that big deal as I know MSVC will complain instantly if I forget Precompiled.h from a new .cpp implementation file within the engine. I suppose it's not bad for users though as long as they know they have to include the file. The include dirs look very clean now. I don't insist reverting this.

**Comment by OvermindDL1** [comment]
Adding a few forward headers would fix both cases, keep it clean as well as not breaking builds that use those headers.  An example such as "Urho3D_fwd.hpp" to keep with standard naming conventions.

**Comment by weitjong** [comment]
> Adding a few forward headers would fix both cases, keep it clean as well as not breaking builds that use those headers. An example such as "Urho3D_fwd.hpp" to keep with standard naming conventions.

If you think about it then you will realize it won't solve the problem. The root cause of the problem is that "Urho3D.h" header file is a generated file. It only exists in the build tree and not in the source tree. This header file is needed at the time when we **build** Urho3D library and when we **use** Urho3D library. However, the actual physical location of this header file is different between the **building** and **using** time. Previously I tried to solve it with a relative path such as ```include "../Urho3D.h"``` in other header files (but that would require a dirty hack that we now try to avoid). Using ```include "Urho3D.h"``` in other header files only works when **building** because we have added ${CMAKE_CURRENT_BINARY_DIR} in the include search path. But this won't work when **using** the library because when using the library we have intentionally not added the "include/Urho3D" in the include search path. We want to enforce the library user to use ```include <Urho3D/Scene/Scene.h>``` as opposed to just ```include <Scene/Scene.h>```. So, the next best possible solution is simply asking users to include Urho3D.h themselves.

I hope I have made myself clear with this long comment. If not then I am sorry for my bad English.

**Comment by OvermindDL1** [comment]
Makes sense there, but that is why I suggested a forward header, the basics can be kept there that is required to allow others to work without any of the generating content?  The main issue above seemed to be about URHO3D_API, which does not need to be generated as it can be conditionally set from macro defines.

**Comment by Stinkfist0** [comment]
Should we re-open this issue for better visibility? There's some valuable discussion here and I'm pretty sure this issue will confuse more people in the immediate future when they pull latest code.

**Comment by cadaver** [comment]
Btw. is the only reason we're generating the Urho3D.h file because of dynamic support for the __declspec(deprecated)? It occurred to me that we're not using that (URHO3D_DEPRECATED) anywhere, if I'm correct? So if we were to remove that, then we could remove generation of Urho3D.h and include it normally both in engine and client build.

**Comment by weitjong** [comment]
No, not exactly. The below part is more important.

On Linux platform:
```
#ifdef URHO3D_STATIC_DEFINE
#  define URHO3D_API
#  define URHO3D_NO_EXPORT
#else
#  ifndef URHO3D_API
#    ifdef URHO3D_EXPORTS
        /* We are building this library */
#      define URHO3D_API __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define URHO3D_API __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef URHO3D_NO_EXPORT
#    define URHO3D_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif
```

On Windows platform:
```
#ifdef URHO3D_STATIC_DEFINE
#  define URHO3D_API
#  define URHO3D_NO_EXPORT
#else
#  ifndef URHO3D_API
#    ifdef URHO3D_EXPORTS
        /* We are building this library */
#      define URHO3D_API __declspec(dllexport)
#    else
        /* We are using this library */
#      define URHO3D_API __declspec(dllimport)
#    endif
#  endif

#  ifndef URHO3D_NO_EXPORT
#    define URHO3D_NO_EXPORT 
#  endif
#endif
```

On Android platform and Raspberry Pi platform, I think they should look similar to Linux platform as they are Linux variants. The same could even be said for Mac OS X platform (Darwin). However, on iOS it looks different again.

```
#ifdef URHO3D_STATIC_DEFINE
#  define URHO3D_API
#  define URHO3D_NO_EXPORT
#else
#  ifndef URHO3D_API
#    ifdef URHO3D_EXPORTS
        /* We are building this library */
#      define URHO3D_API 
#    else
        /* We are using this library */
#      define URHO3D_API 
#    endif
#  endif

#  ifndef URHO3D_NO_EXPORT
#    define URHO3D_NO_EXPORT 
#  endif
#endif
```

The reason I (we) chose to rely on CMake to auto-generate this platform-specific header file for us so that we don't have to. Of course, we can combine all these manually into one big header file using a lot ```ifdef``` for all the platforms that Urho supports currently. But what if we have more platforms to support in the future?

**Comment by cadaver** [comment]
Ah, forgot the dynamic test for visibility("hidden"). Thanks for the clarification. Probably that could be hacked around by some ugly GCC version testing, but on the whole it wouldn't be an improvement.
