### ISSUE TITLE
Client and Server in the same process

### ISSUE THREAD

**Issue by cornytrace** [urho3d/Urho3D#664]
Hey there!
I've been looking at this engine, and it looks very impressive!
However, I've stumbled upon a use-case for which there does not seem to be any support.
According to the examples and the manual, multiplayer can only be done using two different processes; While in many games, the client and server can be separate threads in the same process.

I've tried to replicate this in urho, by creating two contexts and Client and Server Applications, and running the server first in an std::async, followed by the client being ->Run() normally, as no window would open with the client also in an async. It compiles, and even runs without crashing. But it is extremely slow, and the console is flooded with "Sending events is only supported from the main thread". It is clear that the server is causing interference somehow.
Having it be possible to run the client and the server in one process would certainly be a great addition to the engine, and I am willing to work on that, but first I wanted to ask you guys if you have done any research on this, if you have any tips, or if you can say for certain that this task is simply not suited to the architecture of the engine?

**Comment by cadaver** [comment]
Note that a Context separates everything: resources, input, graphics, sound. You would not want them duplicated, and a Context also always assumes an exclusive main thread.

If you want to go this way then you'd need to hack the Network subsystem to allow it. However I believe you would still be running a separate "client scene" and a "server scene", which can be considered wasted memory and processing at least in a singleplayer game.

**Comment by cadaver** [comment]
It turns out that you don't have to do any hacking; the scenario is already supported by simply calling both the client & server functions in Network, and keeping your client & server scenes separate. Linked is a modified SceneReplication example which allows to test this. First start server, then connect (you don't have to type anything to the address box.)

I had to fix an issue that only "local" components should be created to "local" nodes, otherwise the example will render a blank screen due to component ID overwrite. Pull the very latest master to get this fix.

https://dl.dropboxusercontent.com/u/69662478/17_SceneReplication.as
