### ISSUE TITLE
From Blender to collada to urho scene importing. Light will always point the wrong way.

### ISSUE THREAD

**Issue by Kiraffi** [urho3d/Urho3D#669]
I noticed that when I used the path of going from blender to collada, and then from collada to urho3d, the light seems to point exactly the opposite direction. The Light always has same weird rotation. For me this value would be:
<attribute name="Rotation" value="-4.37114e-008 0 -1 0" />

If I set this value to 1 0 0 0, then the light points in the correct way, since the light is attached to a node.

**Comment by cadaver** [comment]
Are you using AssetImporter for the collada to Urho3D part?

**Comment by Kiraffi** [comment]
Yes, I was using the AssetImporter.exe for the collada -> urho. I also quickly tested out going from fbx-format to urho, and the lights rotation was different in the xml-file.
FBX: attribute name="Rotation" value="0.707107 0 0 0" 
DAE: attribute name="Rotation" value="-4.37114e-008 0 -1 0"

**Comment by cadaver** [comment]
Ok, thanks for the clarification. That doesn't sound too good, because it means we cannot likely make a single fix in Urho AssetImporter code, which doesn't make any distinction between the formats.

Rather the wrong rotation may be a result of Assimp (the library we use for loading models and scenes) treating the formats differently, or even the fbx & collada export in Blender behaving differently.

**Comment by Kiraffi** [comment]
I think overwriting the rotation should work? Like setting the value to 1,0,0,0, because the light seems to have a node as a parent to LightAdjust node, and the parent has the true rotation of the light from the scene. Then again I do not know how it affects importing scenes from other 3d-modeling softwares.

As a matter of fact, I am not even sure what is the purpose of this one extra node that appears in the xml-file. The light itself is attached to it, but couldn't it be attached to the parent node that has all the rotation and position?

**Comment by cadaver** [comment]
The Assimp data structure has a separate transform for the light, while it's also attached to a node. This is actually very inconvenient and AssetImporter tries to avoid creating the extra "adjust" node if possible (if the light has identity rotation + position). We actually cannot move the parent node because there might be something else attached to it, like a mesh.

It could be a bug in the adjust node creation code, or rather that the light direction has to be interpreted as reversed in that case.

**Comment by cadaver** [comment]
Should be fixed by hacking Assimp code. I also fixed spot FOV angle handling, which was a problem in AssetImporter.

Generally it seems that there are large differences / bugs in how Assimp handles scene lights. I tested a very simple scene made with Blender that contained 2 boxes and a spotlight; only Collada produced the correct result.

**Comment by friesencr** [comment]
@cadaver Would you like me to make an issue on the open asset import library?

**Comment by cadaver** [comment]
Sure, if you have time for that, it wouldn't hurt. However preferably the issues with the lights should be verified without using Urho / AssetImporter code at all, to make absolutely sure the fault is with Assimp.
