### ISSUE TITLE
Editor Unresponsive After Setting Window UIElement To Modal

### ISSUE THREAD

**Issue by practicing01** [urho3d/Urho3D#682]
Editor Unresponsive After Setting Window UIElement To Modal
I would also like to point out that it would be nice if the other UIElement's had a modal option.

**Comment by cadaver** [comment]
You should be able to cancel the modal mode with ESC. But otherwise, this pretty much a "Doctor, it hurts when I do this. - Stop doing it." situation, which is hard to fix because we're "misusing" the live UI hierarchy for editing.

I'd recommend building the modal UI layout to completion, saving it without the modal attribute set, and enabling modal mode in code when you instantiate it. Might be good to disable the modal attribute from being shown in the editor at all though.
