### ISSUE TITLE
[Editor] (feature request) Clone material button with auto assign

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#684]
Usually I prefer to create a new material it is fully based on std material like a "stone" and other materials. And in this case I picking the "stone" material to model then going to material inspector save this as copy, then again going to model's setup to pick this new saved material then do some color tweaks or something else.
 
Is it possible to create the "Clone" button for this? 
Maybe with dialog window for enter the new name of cloned material 
![123](https://cloud.githubusercontent.com/assets/9577466/6830838/c164c528-d346-11e4-9329-f781929eaa24.png)

**Comment by cadaver** [comment]
The idea is good, but I'm not in favor of cluttering the material attribute with one more button. Three is almost too much already.

**Comment by MonkeyFirst** [comment]
mb special small ico bnt ? Like these "close" [х] element but with symbol "c" - that's mean "[c]lone"
it may be placed in front of material path like that - [ C ] [Material/Stone.xml]

**Comment by szamq** [comment]
Isn't that related to per drawable shader parameters branch? now we have to clone the entire material to change one entity that shares the material. Then, if we do it programmatically and we save the scene, the cloned material isn't saved/loaded correctly( because it doesn't exist on the hard drive). Of course we can save the newly cloned material as a file with some generic name (Stone_00342.xml) but just imagine how many files would be created when creating foliage with various colors - let say all shades of green color.

**Comment by MonkeyFirst** [comment]
>Isn't that related to per drawable shader parameters branch?
no it's only about manual setup materials in editor and not in code side. 
I know that we have material.clone() method

my point in case that we do not must doing everything in programmatically way, if we could do it manualy in editor, in this case editor becomes more responsible and friendly in usage.

**Comment by cadaver** [comment]
From the point of view of the rendering pipeline, separate materials are actually preferable for mass usage, even when parameters are slightly different. Because let's say you have 100 green trees, 20 slightly yellowish trees, 20 even more yellowish trees, 20 completely yellow trees. the rendering can instance those groups. Whereas individual drawable shader parameters will always force a non-instanced draw call per each object. But yeah, this issue is completely about convenience shortcuts in the editor.

**Comment by hdunderscore** [comment]
What I've been doing is a simple 'Save As' in the material panel.

Just throwing another related idea out there-- material inheritance would be useful in these cases too, so that eg if you like to inherit from Stone.xml and later make changes to Stone.xml (offline), it would be pretty handy to have that change reflected in any material that used Stone.xml as a base. See UE4 materials.

**Comment by weitjong** [comment]
Although it is not properly documented (yet) but we do have some kind of inheritance feature for all resources that use XMLFile. See the implementation in https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Resource/XMLFile.cpp#L102-L127 and an example of the usage in https://github.com/urho3d/Urho3D/blob/master/bin/Data/UI/ScreenJoystick_NinjaSnowWar.xml#L2.

The ```inherit``` attribute can be applied to any top-level element in any XML file describing a resource, be it material or UI-layout or others. Perhaps it is not as powerful as how UE4 does it, but at least we have something.

**Comment by hdunderscore** [comment]
That looks very good, I'll look into it !

**Comment by cadaver** [comment]
Ah, there are potential pitfalls in the XML inheritance if the XMLFile is being background loaded in a thread, in which case GetResource isn't safe. Likely replacing it with GetFile will work.

**Comment by weitjong** [comment]
Yes, I agree. This part of the code was much simpler then, before the background loading feature was added.

**Comment by friesencr** [comment]
At one point I had wanted some sort of resource pointer in the scene format.  So all the bones and such didn't have to reload per node.  It would make the scene files more sparse but complicate code and require putting the control on the developer.
