### ISSUE TITLE
documentation re: Native build process & makefile

### ISSUE THREAD

**Issue by raould** [urho3d/Urho3D#693]
Hi, I'd like the docs to explain if/how we can use make, rather than e.g. Eclipse, on Linux.
http://urho3d.github.io/documentation/HEAD/_building.html
under "Native build process"

**Comment by weitjong** [comment]
In that section we only add specific information pertinent to the specific IDE, like Eclipse and Xcode, but otherwise the texts in that section are valid for all IDEs and build tools including ```make```. For configuring and generating ```Makefile``` project, you should use ```cmake_generic.sh```. It is the same whether you generate the ```Makefile``` project on Linux host or on Mac OS X or even on Windows when using MinGW compiler.

**Comment by raould** [comment]
I'll try to make an edit to show you what I mean. :-)

**Comment by weitjong** [comment]
OK. Feel free to reopen the issue again.

**Comment by raould** [comment]
i'll just try to make a p.r.
