### ISSUE TITLE
Spotlights are broken on Intel HD GPU, Windows, OpenGL 3

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#695]
The 07_Billboards example shows artifacts in the spotlights, both forward and deferred, in GL3 mode. GL2 is fine.

Examine whether this can be circumvented without breaking anything else, and without making the shader code ugly or nonsensical.

**Comment by boberfly** [comment]
Just a hint, it might be due to GL3 not supporting luminance channels as I remember all the spotlights and things were using 1-channel luminance textures. I was using swizzles to convert GL_RED to that in my branch. Unfortunately sRGB doesn't work through this either so the textures should be made linear too.

Maybe you're using swizzles already, haven't looked at the new codebase yet... :)

**Comment by cadaver** [comment]
Yes, GL3 is already using red channel where necessary, and the spot textures were converted to RGB colors so that the shader doesn't have to differentiate between colored and monochrome. It's something fairly weird, possibly related to both stencil masking and the spot texture coord calculation.

**Comment by cadaver** [comment]
Turned out it was using a deprecated enum for the border addressing mode, which Nvidia happily accepted, but Intel reverted to wrap mode.
