### ISSUE TITLE
cmake build is confusing / poorly documented

### ISSUE THREAD

**Issue by raould** [urho3d/Urho3D#697]
(old thread: https://github.com/urho3d/Urho3D/pull/692)

Ok, seeking help. I need to understand how builds are expected to really happen. What I think I have heard / read from people here does not make sense vs. what I have seen happen on my machine in reality.

To wit: It sounds like people are saying that "1) mkdir build 2) cd build 3) ../cmake_generic.sh . 4) make" is expected to Do The Right Thing vs. only doing 3 & 4, in the local git repo root directory.

But it doesn't really work right. Because I end up with localrepo/build/bin that does not contain the stuff in localrepo/bin, so the localrepo/build/bin directory is incomplete & not usable.

**Comment by raould** [comment]
Correction: I guess what is really desired is "1) cd localrepo/ 2) mkdir build 3) ./cmake_generic.sh build 4) cd build 5) make"?

**Comment by weitjong** [comment]
As per existing documentation for [native build process](http://urho3d.github.io/documentation/HEAD/_building.html#Building_Native), there are really only two steps. That section looks confusing because it tries to cover all the use cases on all the supported IDEs and host systems in a few paragraphs. If we just need to support Linux using Unix Makefiles, for example, the two steps could be rewritten to:
1. cmake_generic.sh /path/to/build-tree [build-options]
2. cd /path/to/build-tree && make
Note that the build-tree path will be created by the script.

Another example using VS on Windows:
1. cmake_vs2013.bat /path/to/build-tree [build-options]
2. Open the solution project file in the /path/to/build-tree and build ALL_BUILD built-in target

However, currently we support more than half a dozen of CMake-generators (Unix Makefile is only one of them), more than half a dozen of IDEs, and a few host systems. So we would have combinatorial explosion should we try to write it in the above concise way. And that's only for targeting native platform alone.
