### ISSUE TITLE
Failing to get Urho set up as 'external library' 

### ISSUE THREAD

**Issue by raould** [urho3d/Urho3D#700]
http://urho3d.github.io/documentation/1.32/_using_library.html

(a) if the rake command really works, I think it should be the very first thing on the page! Not the last! :-)

(b) But... it doesn't seem to work for me. (Ubuntu 14.04 lts 32bit intel.) It does make a directory and set up files, symlinks, but then I can't get cmake to work. *I think this is probably because the process of using cmake correctly is still not clear to me: https://github.com/urho3d/Urho3D/issues/697*

$ rake scaffolding dir=MyTestApp

$ cd MyTestApp

$ mkdir build

$ ./cmake_generic.sh build

CMake Error at CMake/Modules/FindUrho3D.cmake:143 (message):
  Could not find Urho3D library in Urho3D build tree or SDK installation.
  Use URHO3D_HOME environment variable or build option to specify the
  location of the build tree or SDK installation.
Call Stack (most recent call first):
  CMakeLists.txt:28 (find_package)

-- Configuring incomplete, errors occurred!
See also "/w/x/y/z/Urho3D/MyTestApp/build/CMakeFiles/CMakeOutput.log".

$ pwd
/w/x/y/z/Urho3D/MyTestApp

$ ls bin
CoreData@  Data@

**Comment by weitjong** [comment]
As per our documentation on the building prerequisite, rake & ruby are not one of them. But those who lucky few that can install and use them, it is a viable option to build Urho3D library and your own project. If you are a CLI user like me, that is.

May I suggest you to first try our support forum on your own build environment setup issue instead of raising it as bug in our GitHub issues. Thanks.

Back to your issue, isn't the CMake error already telling you what is the problem? To me, it has nothing to do with the rake scaffolding task. You will get that error if you have not set URHO3D_HOME variable correctly (or alternatively install Urho3D SDK to the system wide default location). If you search our forums, I believe you can find the solution in no time.

**Comment by GoogleBot42** [comment]
Yes exactly was I thinking... Could you use the forums to report "bugs"?  Most of your bugs aren't actually bugs and the community can answer it.  (Also you are spamming my email because I get an email for every post here...)  If you find a real bug the devs are very active on the forums too.

To solve your problem... call "sudo make install" right after calling "make" when building Urho3D.  This, as weitjong said, will install in a system wide location.  If you don't want to do that edit .bashrc (i am assuming you are using bash I personally use zsh) by typing: "nano ~/.bashrc"

Add "export URHO3D_HOME=/path/to/Urho3D-root-dir/"
Where you should add this depends on the contents of bashrc... adding to the top or bottom might work fine if you are using Ubuntu but IDK... I use arch so my file only contains what I have directly added.
