### ISSUE TITLE
Improve Client and Server in same process

### ISSUE THREAD

**Issue by cornytrace** [urho3d/Urho3D#706]
As nearly almost all multiplayer game engines support a server in the same process as the client (a listen server), I tried doing this in Urho3D. I saw it was not possible to do this elegantly, without some ugly hacks. The most prevalent problems are:
* Unclear seperation between client and server, i solved this partially by making the client and server seperate dlls, loaded by an exe whose only purpose is to set up Urho and execute the client and server dlls. One can then use #defines to make shared code aware in which context (client or server) it is running.

* Engine Subsystems are shared between client and server. This is not wanted for some subsys, as the only exchange of information between the client and the server should be over the network. If, for example, I have a SceneManager storing all scenes of the client or server, I would not want the client to access a server scene. This is not possible in the current Urho3D engine without ugly hacks.

Therefore I propose this:
Add an optional parameter to RegisterSubsystem, RemoveSubsystem, GetSubsystem to specify whether it should be accessible by the client, server, or both/singleplayer (parameter absent). This allows registering a single class twice, so there is no interference and the class does not need to do the  checking itself. It also preserves backwards compatibility.

My question to you is if this is an optimal solution, and whether this would be accepted as a pull request.
If the feedback is positive, I will make the change and make a pull request as soon as I can.

**Comment by weitjong** [comment]
What is the benefit of having both server and client in the same process since you don't want them to share information freely? What wrong with having two separate processes (one for server and one for client) as you can use IPC (using pipe or socket, etc) to communicate to each other?

**Comment by cornytrace** [comment]
You may be right, but then why does UE4/Unity/Source do it otherwise? (Actual question)

Also, it feels much more neat to me to have one process; Server log messages can appear in the client console; The player playing on the client can automatically be marked as trusted or admin; You only need to compile the exe without the client library for a dedicated server; And certain read-only things, such as models (for the collision hulls), would only have to be loaded once.

**Comment by cadaver** [comment]
In Urho, subsystems are a lower level concept than networking (which is just one subsystem itself.) Therefore I don't recommend making this PR: it would need the concept of "being a client or server" to be inserted outside the Network subsystem, which would muddle this principle.

The local client is going to be a bit different than a remote client, since it resides in the same Urho context as the server, unless you go with the two process approach. I would just recommend to be diligent with code and to not access the "wrong" objects. Any hacking protection gained from this would be illusory as long as the client and server are in the same process.
