### ISSUE TITLE
Building Assimp for Urho3D in Mac failing

### ISSUE THREAD

**Issue by syvanpera** [urho3d/Urho3D#709]
Building Urho3D in Mac using Xcode 6.2 fails to following error: "fatal error: 'AssimpPCH.h' file not found".
I understood there was some recent change to the way Assimp is bundled in the build and it seems to not work for Xcode 6.2 anymore. The actual cmake build works just fine, but when you try to build the xcode project you get the error above. This can be fixed by commenting the line "enable_pch (code/AssimPCH.h)" in CMakeLists.txt and rebuilding.

**Comment by Skrylar** [comment]
I seem to recall xcode having some peculiar restrictions with precompiled header use when I still had a mac.  It might be worth manually checking to see if the flags which include the folder for that file are being left out because of this.

**Comment by weitjong** [comment]
The problem is, Assimp uses ```#include "AssimpPCH.h"``` throughout its code. These includes are no longer necessary because we have force include the precompiled version of the header after invoking our ```enable_pch()``` macro. We don't want to change the Assimp's code too much, so we leave those include statement in the code. Interestingly, newer Xcode version catches that, while older Xcode version (and the rest of the compilers) seem to be silence about it.
