### ISSUE TITLE
Error message when reloading a scene with obstacles

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#726]
When reloading a scene containing obstacles (like in sample 39_CrowdNavigation), dynamicNavigationMesh::RemoveObstacle() is triggered and an error is logged, as 'obstacleId_' is not available (not serialized).
I'm not sure how to properly handle this, as everything seems to work fine, but this error should not pop-up.

**Comment by cadaver** [comment]
In "silent" mode, where DynamicNavigationMesh doesn't send events, the obstacleId_ is not cleared even if the obstacle was internally removed. It's sometimes difficult to distinguish "runtime" behavior from "loading" behavior; the setting of Obstacle attributes when loading probably triggers multiple redundant additions / removals.

**Comment by cadaver** [comment]
Btw. I'm unable to reproduce this error.

**Comment by Mike3D** [comment]
I'll try with a previous build, maybe I've messed something today.

**Comment by Mike3D** [comment]
With a previous build, this error happens only in C++, not in AngelScript.

**Comment by cadaver** [comment]
It appears it can be made to happen in AngelScript as well by clearing the mushroom node array before reloading the scene. It's related to clearing the scene of old content before reloading. But in editor I can't get it to happen.

**Comment by cadaver** [comment]
Further observation: this is not strictly related to clearing / reloading the scene, but it will also start to happen in the navigation demo scene when you load it to the editor, and start removing the mushrooms one by one. Once you remove enough, you'll start to get this error.

This is probably for @JSandusky to investigate, who knows the DetourCrowd internals better.

**Comment by cadaver** [comment]
More investigation: the determining factor of whether this error appears seems to be the lack of tileCache update. Basically, when you remove too many obstacles without updating the tile cache inbetween (as would happen when clearing the scene), it starts erroring. You don't get the error in editor either, when you keep scene update running, so that the removals are "flushed" or whatever the tileCache is doing internally.

**Comment by JSandusky** [comment]
The change setting obstacleId_ to zero prevents the double removal, which I'm pretty sure is what the initial issue was. The obstacle was removed, the id was never reset and then an attempt to remove it was made again.

AddObstacle was force updating the cache and RemoveObstacle wasn't when it should. The addition of the request limit checking method, should be sufficient though I'll fiddle around and make sure. But that should have been a problem is with it running out of add/remove request slots so it should be fine with that change.

**Comment by Mike3D** [comment]
Sorry for bad news, but lowering navMesh TileSize (for example to 32 instead of 64) triggers the error at build time.

**Comment by JSandusky** [comment]
The "if" tests Cadavre added in DynamicNavigationMesh.cpp's obstacle addition/removal should be "while" loops. I'll submit a PR for that. I'll submit a PR in a bit once I'm comfortable that it doesn't introduce problems. 

The alternative to looping is modifying the update method, which will be more involved the the other Urho3D specific library edits I've seen - the loop is easily explained with a decent comment.

What's happening is the smaller tile size is resulting in many more tiles being queued for update, so even though update is being called, there's tiles left in the queue and they take precedence over handling obstacle addition/removal requests. It's a problem at higher tile sizes as well, but undetected because the scene isn't large enough for tile requests to overrun.
