### ISSUE TITLE
Error while building with CMake 

### ISSUE THREAD

**Issue by grant0417** [urho3d/Urho3D#740]
When ever I try to use CMake to build my project and use Urho3D as an external library I get this error in my CMake log, I have tried to Google the issue but I cant fix it.

```
The C compiler identification is MSVC 19.0.22816.0
The CXX compiler identification is MSVC 19.0.22816.0
Check for working C compiler using: Visual Studio 14 2015
Check for working C compiler using: Visual Studio 14 2015 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 14 2015
Check for working CXX compiler using: Visual Studio 14 2015 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
DirectX SDK not found. This is not fatal if a recent Windows SDK is installed
Configuring done
CMake Error: CMake can not determine linker language for target: MyExecutableName
Generating done
```

**Comment by weitjong** [comment]
Well, since this happened in your own project configuration and generation, it is difficult for us to help you without seeing your project CMakeLists.txt. Did you follow the steps outlined in http://urho3d.github.io/documentation/1.4/_using_library.html?

Since this is not a general issue, I think it should not be reported in here. Please use our support forum as it has more readers there.
