### ISSUE TITLE
Linking from an external project on Linux seems to be broken

### ISSUE THREAD

**Issue by celeron55** [urho3d/Urho3D#747]
This happens when I try to build using a system quite like is described here: http://urho3d.github.io/documentation/HEAD/_using_library.html

	-- URHO3D_HOME="/home/celeron55/softat/Urho3D"
	CMake Error at /home/celeron55/softat/Urho3D/CMake/Modules/FindUrho3D.cmake:143 (message):
	  Could not find Urho3D library in Urho3D build tree or SDK installation.
	  Use URHO3D_HOME environment variable or build option to specify the
	  location of the build tree or SDK installation.
	Call Stack (most recent call first):
	  CMakeLists.txt:35 (find_package)

	-- Configuring incomplete, errors occurred!
	See also "/home/celeron55/softat/uternadim/Build/CMakeFiles/CMakeOutput.log".

I am using CMake 2.8.12.2 and an out-of-source build for both Urho3D and my own project which links to Urho3D.

It seems to be a simple issue of just not enough path and a wrong file to search being given to CMake. I was able to fix it like this:

	diff --git a/CMake/Modules/FindUrho3D.cmake b/CMake/Modules/FindUrho3D.cmake
	index e84d1f9..63a6ec2 100644
	--- a/CMake/Modules/FindUrho3D.cmake
	+++ b/CMake/Modules/FindUrho3D.cmake
	@@ -77,6 +77,8 @@ else ()
		 # URHO3D_HOME variable should be an absolute path, so use a non-rooted search even when we are cross-compiling
		 if (URHO3D_HOME)
		     list (APPEND CMAKE_PREFIX_PATH ${URHO3D_HOME})
	+        list (APPEND CMAKE_PREFIX_PATH ${URHO3D_HOME}/Source)
	+        list (APPEND CMAKE_PREFIX_PATH ${URHO3D_HOME}/Lib)
		     set (SEARCH_OPT NO_CMAKE_FIND_ROOT_PATH)
		 endif ()
		 # For Android platform, search in path similar to ANDROID_LIBRARY_OUTPUT_PATH variable
	@@ -94,7 +96,7 @@ else ()
		     # For 64-bit, force to search in 'lib64' path even when the Windows platform is not defaulted to use it
		     set_property (GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS TRUE)
		 endif ()
	-    find_path (URHO3D_INCLUDE_DIRS Urho3D.h PATH_SUFFIXES ${PATH_SUFFIX} ${SEARCH_OPT})
	+    find_path (URHO3D_INCLUDE_DIRS Urho3D.h Urho3D.pc.in PATH_SUFFIXES ${PATH_SUFFIX} ${SEARCH_OPT})
		 find_library (URHO3D_LIBRARIES NAMES Urho3D ${URHO3D_LIB_SEARCH_HINT} PATH_SUFFIXES ${PATH_SUFFIX} ${SEARCH_OPT})
		 if (WIN32)
		     # For Windows platform, give a second chance to search for a debug version of the library

**Comment by weitjong** [comment]
I am sorry for the problem you face. I am not sure why it happened on your case. We have tested the project scaffolding (create a new project structure for using Urho3D library, call CMake to configure/generate the project file, and call make to build it) on all our CI builds for Linux platform. In Travis CI VM we are using even older CMake version, namely 2.8.7, and everything is OK. So, we can rule out CMake version to be the problem here.

Based on the description, it is still not clear to me whether you have migrated your project structure and your build system to follow the 'new build system' introduced in the 1.4 release. In the new build system, both the ```include``` and ```lib``` directories are in lower case. Your fix uses ```Lib``` with capital letter 'L' already indicates to me something is not quite right in your setup.

Also note that in the new build system, the ```URHO3D_HOME``` environment variable is supposed to point to the build tree of the Urho3D project. In the old build system, the ```URHO3D_HOME``` was supposed to to point to Urho3D project root itself. Most probably you have mixed these two.

**Comment by celeron55** [comment]
Oh. This makes a lot more sense.

Some kind of a note describing the build system changes would have been useful in http://urho3d.github.io/documentation/HEAD/_using_library.html.

**Comment by weitjong** [comment]
Yes, that's a good point. I will see to it later.
