### ISSUE TITLE
Removing child node from scene does not remove drawables, if node is still alive post removal

### ISSUE THREAD

**Issue by JoshEngebretson** [urho3d/Urho3D#748]
It seems a node's drawables are being left in the scene, if the node survives being removed from a scene (ie. is referenced somewhere else)

In 04_StaticScene, add this after line 114: https://github.com/urho3d/Urho3D/blob/master/Source/Samples/04_StaticScene/StaticScene.cpp#L114

        // keep node alive, after removing node from scene
        mushroomNode->AddRef();

        // Removing components does get rid of drawables in scene, once node is removed
        //mushroomNode->RemoveAllComponents();

        // if node is still alive, drawables are still in scene
        scene_->RemoveChild(mushroomNode);

**Comment by cadaver** [comment]
You're right, the drawable components don't track whether they're currently attached to a scene node chain in the scene, because all the drawable needs for drawing itself is an owner scene node, which it will always have until detached.

If this was fixed one way or another, then the drawables would also need a way to reattach themselves if the node goes back to the scene. But the code would become more complex; at the moment I don't precisely know where this removal/readdition code should be inserted. 

There are also valid situations where you would detach the node from a certain parent, hold on to it, then insert it to another parent in the scene, in which case it would be needless overhead to remove and reinsert the drawable components from the octree.

At least just at the moment I'm tempted to leave this as is to act as a visual indicator of a reference counting problem in the application, but it's good to be aware of this behavior. 

Also note that it's valid to insert drawables outside the scene to the octree, for example the editor gizmo, which further makes this harder to fix.

**Comment by JoshEngebretson** [comment]
Hi Lasse! 

Thanks for the detailed "big picture" rationale! :)

I'll have to chew on this a bit, for one thing scripted nodes may have a reference keeping them alive until garbage collected.  This leads to artifacts, as once removed from the scene, their drawables hang around and then blink out of existence once the node is gc'd.  

I am working around this now by explicitly removing the nodes components as well as removing the node from the scene.

**Comment by cadaver** [comment]
If you want to fix just the rendering, and don't need manually added outside-scene drawables like the gizmo, you should be able to insert a check for a drawable's scene being non-null before accepting it into the culling result (in View class)

However a similar thing will happen with physics etc. which may be more devious.
