### ISSUE TITLE
Fix Shader

### ISSUE THREAD

**Issue by warzes** [urho3d/Urho3D#759]
Sorry for my english

I suggest a couple of fixes for the shaders are used in his Fork Urho3. All are written in HLSL (but can be transferred to GLSL).

1) Scale Normal
It gives a very clear grain.

Samplers.hlsl
#ifdef PACKEDNORMAL
float3 DecodeNormal (float4 normalInput, float bumpScale)
{
     float3 normal;
     normal.xy = (normalInput.ag * 2.0 - 1.0);
normal.xy * = bumpScale;
     normal.z = sqrt (1.0 - saturate (dot (normal.xy, normal.xy)));
     return normal;
}
#endif

Changing bumpScale get different effects.
bumpScale = 1: default
![test 2015-06-30 15-50-35-74](https://cloud.githubusercontent.com/assets/2390773/8424636/57014cce-1f40-11e5-998f-632d025772fa.png)

bumpScale = 50:
![test 2015-06-30 15-50-18-18](https://cloud.githubusercontent.com/assets/2390773/8424641/5fcac010-1f40-11e5-8f35-292188c96fd0.png)

2) LitSolid.hlsl
Instead
#ifdef ALPHAMASK
if (diffInput.a <0.5)
discard;
#endif

write:

#ifdef ALPHAMASK
clip (diffInput.a - cCutoff);
#endif

cCutoff - constant

removed superfluous condition. plus the ability to adjust the alfamask
sCutoff 0.0 (nothing is discarded) to 1.1 (drop all)
sCutoff = 0.5 - discarded alpha <0.5

**Comment by cadaver** [comment]
Thanks for the suggestions. However, the LitSolid shader is already complex (it should be split into smaller shaders like DiffuseNormal etc.) and adding these snippets would mean that new material default parameters would also need to be added, which has the potential to slightly reduce rendering performance for everyone.

I don't think I'll be incorporating these now; I recommend rather posting them to the Urho user wiki ( http://urho3d.wikia.com ) or the forums.

Note that the LitSolid shader does not have any "special" meaning to the engine except being referred to by the default techniques that come with it so using a custom shader, which has these features added, instead of modifying LitSolid, is just as valid.
