### ISSUE TITLE
Update to lua 5.3.1

### ISSUE THREAD

**Issue by amerkoleci** [urho3d/Urho3D#766]
Lua 5.3.1 is out, any plans to upgrate the lua version?

**Comment by weitjong** [comment]
I am not the main maintainer for the Urho3D/Lua bindings, so take my comment with a grain of salt.

At the moment we cannot upgrade the Lua version to anything higher than 5.1 because the Lua binding library that we currently use (tolua++) only works with that version. It does not work with Lua 5.2, let alone this newly released version. It seems that tolua++ is not being maintained anymore. Its homepage is even already defunct. So, unless we have someone come up to rewrite how we bind the exposed Urho3D API to Lua, we are pretty much stuck with 5.1.

**Comment by friesencr** [comment]
There is a another version of tolua++ that get you to 5.2 http://webserver2.tecgraf.puc-rio.br/~celes/tolua/.  

It hasn't reciprocated to the usual mirrors which doesn't give me warm fuzzy feelings.

**Comment by weitjong** [comment]
@friesencr The link you provided is for ```tolua```. We are using ```tolua++``` which is a different library. IMHO, the tolua++ binding generator must go if we want to catch up with Lua. Having said that, do not forget that the same generated bindings are being used for Lua and LuaJIT. And as I understand, current LuaJIT version is only compatible with 5.1 although it has 5.2 compatibility switch. So, if we have someone come up to replace the binding and upgrade Lua version in the process, that person must keep an eye on the LuaJIT as well. i.e. it would probably be wise just to use features available in 5.2 and not the new feature in 5.3 which is not supported by LuaJIT yet.

**Comment by weitjong** [comment]
As supporting LuaJIT is important, there is no such plan in the near future.
