### ISSUE TITLE
[Editor] Phantom Sprite bug ?  

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#770]
see this
https://youtu.be/QJSyc95hOLw

**Comment by cadaver** [comment]
Please always try to provide steps as text to reproduce a bug instead of relying just on a video.

AnimatedSprite will create hidden child nodes to actually display the sprites. Probably it goes wrong when the AnimatedSprite component is created directly into the Scene root, which you really aren't supposed to do.

Can you reproduce the bug when you create a node for the AnimatedSprite first? (ie. don't create it directly to scene root) If not, I'll be tempted to close this as wontfix.

**Comment by cadaver** [comment]
Note that you can see the internal nodes that AnimatedSprite creates when you tick "Show temporary objects" in the editor preferences window.

**Comment by MonkeyFirst** [comment]
no, it no reproduced if I create AnimSprite at node first. but i'm still think that this is a some kind of editor bug, because user may create anything anywhere ) 
but ok, you may close this as wontfix

**Comment by cadaver** [comment]
Some components issue warnings when created to the scene root, I'll add one to AnimatedSprite as well.
