### ISSUE TITLE
Invisible mouse cursor can escape window in MM_ABSOLUTE mode

### ISSUE THREAD

**Issue by newbthenewbd** [urho3d/Urho3D#788]
Hi,

While further testing out the engine I noticed another issue with it - invisible system mouse cursor in MM_ABSOLUTE mode doesn't actually prevent the mouse from escaping the window.

**Test machine:**
AMD Athlon 64 X2 Dual Core Processor 3800+, NVIDIA GeForce 7600 GT (OpenGL 2.1.2) running on 64-bit Fedora 22 with propertiary NVIDIA 304.125 driver, Urho3D 1.4.
**Steps to reproduce:**
Set mouse mode to MM_ABSOLUTE, set mouse visibility to false, move the mouse aggressively until it escapes. (using tiny window makes it easier)
**Workaround:**
Use MM_RELATIVE mouse mode.
**Proposed fix:**
Deprecate SetMouseVisible() recommending the use of MM_RELATIVE instead, or use some under-the-hood magic not letting invisible cursor leave the window in MM_ABSOLUTE mode.

Once again, thanks for making and providing support for the engine! Keep up the good work!

**Comment by cadaver** [comment]
Yes, this is pretty much as expected. Would be nicest to have @hdunderscore's input for this. Using MM_RELATIVE however presently breaks opening the console, which expects to be able to switch the OS mouse cursor on.

**Comment by newbthenewbd** [comment]
In that case I suppose changing SetMouseVisible(false) logic to "jail" the mouse just like MM_RELATIVE does could work. Least harmful and simplest solution would be simply to place a warning somewhere and having the coder handle it himself, as the issue is clearly unwanted and doesn't expose itself easily, especially on higher resolutions, while being pretty easy to fix when one "knows what's going on". This is also one of the main reasons I posted it here - just to warn people and propose a workaround. :-)
Thank You for Your reply!

**Comment by hdunderscore** [comment]
I will look at cleaning up issues with the mouse modes in the next few days.

I think it's best to promote MM_RELATIVE for these purposes, however the Console and examples will need to be updated for this.

**Comment by juj** [comment]
It looks like on Windows in native builds that have the cursor hidden, the mouse cursor lock is done by repositioning the cursor each frame to stay in the center of the screen. As a result, if the application is in windowed mode, it is possible to escape the mouse cursor lock if one moves the mouse cursor very fast. The Win32 API function `ClipCursor` (https://msdn.microsoft.com/en-us/library/windows/desktop/ms648383(v=vs.85).aspx) could be used here to make sure that the mouse cursor is not allowed to escape the window rectangle, however one has to be very careful to release the clip if e.g. one alt-tabs away from the window or when the window loses focus otherwise.

**Comment by friesencr** [comment]
In my voxel renderer, if there is a hitch and the mouse is moving moderately fast you will break out of the window.  Same issue except it is easy to produce.

**Comment by hdunderscore** [comment]
This issue should be solved. We now use SDL_SetMouseGrab to prevent escape in MM_ABSOLUTE mode.
