### ISSUE TITLE
StaticModelGroup don't work when used Techniques/DiffAlphaMask.xml

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#791]

**Comment by 1vanK** [comment]
My wrong

**Comment by 1vanK** [comment]
This is a very strange bug https://drive.google.com/open?id=0B_XuF2wRVpw4ckJUMWdsRzV1QXM

StaticModelGroup is not rendered.

But:
1) If change lastGroup->SetModel(cache->GetResource<Model>("Models/Plane.mdl"));
to lastGroup->SetModel(cache->GetResource<Model>("ModelsBox.mdl"));
it works
2) If delete boxNode->SetScale(0.25);
it works
3) If change material it works

**Comment by cadaver** [comment]
Can you clarify what is the exact bug here? When I run the provided exe, I can see the group of leaves just fine, however the shadows are extremely angle-dependant and easily blurred due to cascaded shadows not being used, and because the StaticModelGroup causes the objects to have one huge bounding box, which makes the shadows harder to focus. You should be able to remedy this by splitting into more groups so that the group bounding boxes are smaller, or by using cascades.

**Comment by 1vanK** [comment]
It's strange, when I run, only ground rendered

http://s020.radikal.ru/i701/1507/af/817ff62c1039.jpg

**Comment by cadaver** [comment]
Can be a GPU related bug, what is your graphics card? I'm running on a Nvidia GPU and I only have the shadow blurriness problem.

Things to try:
- Make a D3D build
- Try to run in GL2 mode (-gl2 switch)

**Comment by 1vanK** [comment]
I have NVidia too. -gl2 does not help. I have not installed Directx SDK currently, i am to try it

**Comment by 1vanK** [comment]
I have warning in log, but I do not know what it means
WARNING: Shader LitSolid(DIRLIGHT NOUV PERPIXEL SHADOW) does not use the define NOUV

**Comment by cadaver** [comment]
This should be a benign warning. The NOUV define is only used by HLSL shaders to avoid reading noexistent UV channel, which causes failed rendering on D3D11.

**Comment by 1vanK** [comment]
With d3d same problem, I will try update a video driver

**Comment by 1vanK** [comment]
Resolved xD
