### ISSUE TITLE
[Feature] OS Exception Message Dialogs

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#795]
Hi,

So I was wondering if a feature already exist with the latest build in handling OS specific exception messages. Take for example a Checksum Error Scene where in Android it just automatically exits without any clue on what just happened. It would be nice to have a way to handle these type of messages so that users are aware of some fatal or exit errors.

Thanks.

**Comment by cadaver** [comment]
This issue is a bit unclear. Do you want to be able to show a message dialog using the OS (e.g. outside normal Urho rendering), or be handling/trapping platform-specific exceptions raised by the OS?

For the first, there is SDL_ShowMessageBox, which could be exposed into the engine API. Not sure if it works on Android though.

If by "Checksum Error Scene" you mean Urho's internal error raised by a checksum error mismatch in networking, Urho itself will not exit, it just sends an event and returns error return value, so that is something that can be perfectly handled with Urho's UI dialogs. Example applications don't necessarily demonstrate best practice and may e.g. just log something which isn't visible to the user.

**Comment by rasteron** [comment]
Hey Lasse,

> Do you want to be able to show a message dialog using the OS (e.g. outside normal Urho rendering), or be handling/trapping platform-specific exceptions raised by the OS?
> For the first, there is SDL_ShowMessageBox, which could be exposed into the engine API. Not sure if it works on Android though.

Yes this is what I have in mind and I did suggest the SDL_ShowMessageBox at the forums later on.

Perhaps something like this for mobile devices or just as an option to have OS exception message handling for all platforms?

![Dialog](http://www.essentialpim.com/help/free/android_conn_error.gif)

I just recently replicated a checksum error and it does exit on my android phone when I try to run it. I'm not sure if I am missing something.

Thanks.

**Comment by cadaver** [comment]
In that case there can be an engine bug which causes a crash and exit.

**Comment by cadaver** [comment]
Briefly tested the SDL message dialog, worked on desktop but not on Android. Though may be that I was not using it correctly, as I called it already after the rendering window was closed, and when the app was exiting anyway.

**Comment by rasteron** [comment]
Thanks Lasse. Yes it looks like message dialog does work with Android..

https://github.com/ennorehling/android-sdl/blob/master/jni/SDL2/include/SDL_messagebox.h

**Comment by rasteron** [comment]
Just found out recently URHO3D_LOGERROR is related to what I'm looking for. :+1: 

Closing this issue, thanks!

![error](https://cloud.githubusercontent.com/assets/3676827/16570770/eff5f774-427e-11e6-9060-2aa3c644ee4e.jpg)
