### ISSUE TITLE
Configure Resource Path on specific builds

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#809]
It looks like with Android build you can't specify your CoreData and Data folders like sort of renaming them. The paths are hardcoded to CMake or Rakefiles somehow. Is there some way to do this as MKLINK is missing on them and still creating broken links with the new name changes.

Thanks.

**Comment by weitjong** [comment]
Yes, you are right. Although the Urho3D::Engine class has ```ResourcePaths``` parameter which suggests that you can use any pathnames, but our build system currently just assumes the default resource paths will be used. You can try to fix this by first checking whether the default pathnames exist on a project structure and skip performing some actions when they do not. Better still, perhaps you can introduce a new build option to specify the alternative paths as a list when you really want to make it a generic solution. Keep in mind that external projects are in fact just reusing build system which was originally designed just for Urho3D project, so if your project is not structured similarly to Urho3D project then you can expect things to break. I think I have stressed this enough in this documentation [page](http://urho3d.github.io/documentation/HEAD/_using_library.html). I agree this is not nice.

**Comment by rasteron** [comment]
Thanks Weit Jong :) I'll see what I can come up with. It's not a priority at the moment but it would be a nice addition to have.

Any pointers though on what specific source files to look for to save time?

**Comment by weitjong** [comment]
I actually also don't remember where are those places but I usually just use 'git grep' command to find anything that I want from the repository. Just look for "CoreData" and the command should list all its occurrences.

**Comment by weitjong** [comment]
I am currently working on a new macro called define_resource_dirs() which, hopefully, will address this issue.

**Comment by weitjong** [comment]
It is done but still only in the ```refactor-buildsystem``` branch. It will be great if you can test to see if it works as you have wanted. In the downstream project, if you don't call ```define_resource_dirs()``` explictly then the build system will call it for you taking the default options (which would setup things as currently we have today for backward compatibility). However, your project CMakeLists.txt now can call the ```define_resource_dirs()``` explicitly and passing option for specifying your project/targetspecific resource directories.

**Comment by rasteron** [comment]
Ok great but have no idea where to start and test with these changes, but I did see the PBR sample setup with it. https://github.com/urho3d/Urho3D/blob/refactor-buildsystem/Source/Samples/42_PBRMaterials/CMakeLists.txt#L33

Can you post an example on how it would test for Android Data/CoreData, something like:

```
/assets/Resources (for Data)
/assets/Core (for CoreData)
```

On a side note and going with the post above, I remember it works with desktop only versions without these new changes, so perhaps it would be much easier for the user if this can be managed through API instead of CMake?

I'm also still having Android build problems (r13) with the latest engine commit/version. I guess I have to submit a separate issue when I get a chance.

**Comment by weitjong** [comment]
To my understanding, we already have an "API" for the application to define the resource directories and resource prefix path. I purposely put quotes there because it is not ```URHO3D_API``` or AS/Lua scripting API as you know it. I have pointed out in my previous comment above that Urho3D::Engine class takes engine parameters (see ```EP_RESOURCE_PATHS``` and ```EP_RESOURCE_PREFIX_PATHS```). You can set those engine parameters in your application's startup code (compile time), or you can initialize those engine parameters using command line options or environment variables (runtime). The ```Urho3DPlayer``` uses the latter approach. Thus, user can already manage that long time ago.

Also, I have commented before, although the engine supports flexible resource directories and resource prefix path setup, our build system was not, well until now. Our build system was originally made just for building Urho3D project and it is only at later time we retrofit itself to be also reusable by downstream projects. So, the build system was not as flexible and only assume that the downstream project should structure like Urho3D porject, including the way where the resource directories are located and named. With this enhancement, the downstream project now have a "hook" to tell the build system otherwise.

Note that if you decide to setup things differently then you have to tell *BOTH* the build system as well as the engine, separately. I have actually thought about making this even more intuitive, however, I didn't pursue it due to limited free time. IMHO, it is more plausible to have a mechanism for build system to setup some external files that could influence how the engine starts during runtime than to have a mechanism that works the other way around.

And as for your question, you can try this (assuming the subdirs in /assets are real directories and not symlinks and they are the actual location where the subdir can be found and that ```assets/``` is located in your project source tree, otherwise adjust the code accordingly).
```
define_resource_dirs (GLOB_PATTERNS ${CMAKE_SOURCE_DIR}/assets)
```
I also assume in there are no other directories in the ```assets/``` directory. But just for demo purpose, in case you do have, say ```/assets/acme``` then you can exclude it by specifying an extra option as so.
```
define_resource_dirs (GLOB_PATTERNS ${CMAKE_SOURCE_DIR}/assets EXCLUDE_PATTERNS .*/acme)
```
Note that, the include pattern uses CMake's glob pattern, while the exclude patterns use CMake's regex pattern. They are not exactly the same :). Check CMake documentation for more detail.

**Comment by weitjong** [comment]
I have added a few paragraphs on the "Using Urho3D libarry" page to explain the new macro usage. I hope it answers all your questions.

**Comment by rasteron** [comment]
Hey, so got Android build working again and tried this with UrhoPlayer, here's the updated [UrhoPlayer CMakeLists.txt](https://pastebin.com/PyvqjEtZ) with your suggestion. (Line 29) 

I have renamed `CoreData` to `Core` and `Data` to `Resource` just like my post above for testing and now getting this error..

![bluestacks](https://cloud.githubusercontent.com/assets/3676827/24745117/fe5d3700-1ae6-11e7-8c7f-07c3c4f5078d.jpg)

![apk](https://cloud.githubusercontent.com/assets/3676827/24745124/04a73dea-1ae7-11e7-8b77-52f82c804c77.png)


Let me know what I have missed here, thanks.

**Comment by weitjong** [comment]
You need to change the engine parameter as well.

**Comment by rasteron** [comment]
Ah yes, works great now :) and also changing the line in Urho3DPlayer.cpp which has `Data` encoded.. https://github.com/urho3d/Urho3D/blob/master/Source/Tools/Urho3DPlayer/Urho3DPlayer.cpp#L59

Issue solved.
