### ISSUE TITLE
Collect all libs into a single folder

### ISSUE THREAD

**Issue by guijun** [urho3d/Urho3D#857]
I noticed all libs will be collected in a single folder if we build with xcode.
I'm wondering if we can do the same thing for visual studio,codeblocks etc.

**Comment by weitjong** [comment]
You don't say what is your reason or the benefit of having them in a single folder. The thing is, we don't even tell our CMake build script to do one way or the other. We fully rely on CMake provided generators to generate the corresponding project/solution for the respective IDE. We don't actually control how the internal of the generated project/solution would look like, aside from its output directories (the bin and the lib folders).

**Comment by guijun** [comment]
thanks for quick feedback.
the reason:
I'm using urho3d custom build as external lib. we are working on mac and windows.
I need to add library search path for all libs. it's sample if we are working with xcode. but it's very hard if we are working with visual studio.

**Comment by guijun** [comment]
I'm not familiar with CMAKE,so I have to post a issue here,:-)
I noticed that the collection is done here:

    # Workaround CMake/Xcode generator bug where it always appends '/build' path element to SYMROOT attribute and as such the items in Products are always rendered as red as if they are not yet built
    if (XCODE AND NOT CMAKE_PROJECT_NAME MATCHES ^ExternalProject-)
        file (MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/build)
        get_target_property (LOCATION ${TARGET_NAME} LOCATION)
        string (REGEX REPLACE "^.*\\$\\(CONFIGURATION\\)" $(CONFIGURATION) SYMLINK ${LOCATION})
        get_filename_component (DIRECTORY ${SYMLINK} PATH)
        add_custom_command (TARGET ${TARGET_NAME} POST_BUILD
            COMMAND mkdir -p ${DIRECTORY} && ln -sf $<TARGET_FILE:${TARGET_NAME}> ${DIRECTORY}/$<TARGET_FILE_NAME:${TARGET_NAME}>
            WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/build)
    endif ()

**Comment by weitjong** [comment]
That custom command is added for other purpose instead of collecting the libs. It is there just so that in the "items" listed under the "Product" in the Xcode Project view will turn from red to black after a successful build. Now you mention it, it actually shows that CMake/generators are actually consistent in this case, i.e. its generated project file will scatter the build artifacts in a few places, including the CMake Xcode generator. This does not cause any build problem within xcodebuild, only that Xcode IDE/GUI still expects the build artifacts to be in a certain place for a given build configuration. The custom command above simply create symbolic links in the GUI expected place to fool the GUI as if they are there. For VS and C::B, I don't think their IDE/GUI have this kind of expectation. In short, the xcodebuild will work with or without the above workaround.

I still don't quite understand why you need all the *.a to be in one place though. You do aware that all the symbols available in all those *.a will eventually end up in the final Urho3D library, either it is a shared or static library type. In other words, external project just need to link against Urho3D library in its lib folder. You don't actually need to know where are those sub-libraries are.

**Comment by guijun** [comment]
there will be lots of libs in lots folders.
I'm using urho3d as external lib,so I have to add paths for all libs and add them all into link list in my CMakeLists.txt using abs_XXXXXX_lib.

**Comment by weitjong** [comment]
Perhaps I did not explain myself well in my last comment.

> there will be lots of libs in lots folders.

Yes, that's true but external project should not depend on or link against them directly. They are only need when building Urho3D library and not needed when using Urho3D library.

> I'm using urho3d as external lib,so I have to add paths for all libs and add them all into link list in my CMakeLists.txt using abs_XXXXXX_lib.

Could you explain why you have to do that? What symbols do you need that you have to get it from the intermediate sub library *.a instead of getting it from Urho3D library directly?

I repeat myself again. All the symbols are found in Urho3D library. Your app only needs to link against Urho3D library. Your app only need library search path to the lib folder where the Urho3D library resided. If this is not how you setup your project then my question is why?

**Comment by guijun** [comment]
I added following lines to my CMakeLists.txt, and it works but ugly ...
foreach (MYLIBNAME sqlite Lua${JIT} luaexpat SQLiteCpp jsoncpp zlib)
    	list( APPEND LIBS ${MYLIBNAME})
		LINK_DIRECTORIES("${URHO3D_HOME}/Source/ThirdParty/${MYLIBNAME}/Debug")
	endforeach ()

**Comment by weitjong** [comment]
Thirdparty libs that are officially used by Urho3D project when building its library will all be "merged" into the final Urho3D library. That may or may not be the case for those that you have added yourself, this is largely depends on how you customize Urho3D build system to suit your need. But judging from your explanation that you need multiple search paths then I guess they are not merged into the final Urho3D library. And if so, it answered my "why" question above. But I am sorry to say that you are on your own in this case. IMHO, we should not collect all our 3rd party libs into one place, say, in the "lib" output directory or somewhere else simply because we don't want our library users to think their app need to link against them. For your own custom 3rd party libs, you can do whatever you want. You can merge them into final Urho3D library (see the Urho3D's CMakeLists.txt to see how this merging is being done); or you can modify the build system to always output all the libraries (intermediate and final) into a single directory as you wanted (see the usage of ```set_output_directories()``` macro).
