### ISSUE TITLE
Configurable texture binding

### ISSUE THREAD

**Issue by JSandusky** [urho3d/Urho3D#859]
Add some method of configuration to specify which textures for a shader technique's pass should be bound, defaulting to "all" and with an easy out of "none."

---

I made a quick and dirty pass at adding a "textures" attribute to Technique passes to filter what textures should be bound for which passes.

The reasons for this were to avoid texture binding during shadow passes (or just bind the diffuse for alphamask techniques), specifically to compensate for integrated GPUs which have limited dedicated vram so unnecessary binds hurt more as the textures will realistically never be in vram.

From the built in DX11 profiling in VS2013:
Gains for shadow rendering were 15% on Intel HD4000 & HD4400 (smidge higher results), going down to around 8-10% for just binding diffuse for alphamask. For 3 4096x4096 textures, results were lesser on smaller sizes.

I'm not sure my implementation is great enough to warrant a PR however, it's basically just passing a PODVector<TextureUnit> from the pass by pointer to batch drawing, if null then bind everything (a magic "all" was checked for first), if not null check size for whether to bind anything and if size is > 0 check the contents for what to bind.

**Comment by cadaver** [comment]
Thanks, this is a good idea to consider.

However, there is already this piece of code in Batch, which should check whether the current shader uses the texture unit in question:

            if (graphics->HasTextureUnit(i->first_))
                graphics->SetTexture(i->first_, i->second_.Get());

Did this not work as expected?

**Comment by JSandusky** [comment]
That test is always passing on my tablets/laptops. It only failed on a tower I just happened to fire up to check.

The intel hd's were on Surface Pro 1 and 2 models. Which are pretty locked down, it's pulling teeth to update drivers on them.

**Comment by cadaver** [comment]
Will have to check this on all APIs. On D3D11 it should be in the hands of the shader compiler & D3D runtime, not the GPU driver.

**Comment by cadaver** [comment]
Verified that on my machine (Win7, Nvidia GPU) each render API produced shaders that identified their used texture units properly.

The debugging code I added to Graphics::SetShaders() was:

```
        static HashSet<ShaderVariation*> maskPrinted;
        if (!maskPrinted.Contains(ps))
        {
            maskPrinted.Insert(ps);
            unsigned unitMask = 0;
            for (unsigned i = 0; i < MAX_TEXTURE_UNITS; ++i)
                if (shaderProgram_->HasTextureUnit((TextureUnit)i))
                    unitMask |= 1 << i;
            LOGINFO("Shader " + shaderProgram_->GetPixelShader()->GetFullName() + " tu bitmask " + String(unitMask));
        }
```

Therefore I'd rather go in the direction of trying to fix that (where necessary) rather than adding a parameter to Technique / Pass. Can you double-check by adding similar code and seeing if you indeed get different results with D3D11 on different machines? The only thing that should make a difference is if there's a different shader compiler DLL, which isn't able to strip away the unused samplers when compiling.

However, a wholly another question / feature would be the ability to bind different textures altogether in different passes, but that would need to be defined through the Material class, as Technique / Pass usually are shared between multiple materials.

**Comment by JSandusky** [comment]
Sorry about that, a case of quadrupled stupidity. Everything is fine in a clean checkout.

First, I mauled the setting of useTextureUnit_ when implementing geometry/compute shaders such that the test always passed and I never noticed. Second, used the wrong branch when I updated and checked desktop which is why it differed.
