### ISSUE TITLE
Allow styling on other element type/styles like ListRow

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#865]
I wonder if this has been implemented yet, or maybe I have missed this somewhere, but I can't find it on the latest docs. I noticed that ListRow style or type does not have any default styling applied or does not show if you added say hover color or selection color:

```
    <element type="ListRow">
        <attribute name="Min Size" value="0 17" />
        <attribute name="Max Size" value="2147483647 17" />
        <attribute name="Layout Mode" value="Horizontal" />
        <attribute name="Hover Color" value="0.0 0.0 0.0 0" />
        <attribute name="Selection Color" value="0.0 0.0 0.0 0" />
    </element>
```

I would also assume that ListRow can also be selected?

**Comment by cadaver** [comment]
You may be misunderstanding the ListRow style, or it's badly named. It's not related to dropdownlists at all, it's used by static layouts like the editor settings dialogs to set a fixed row size and horizontally layout the elements, when there's a vertical list of settings rows.

In DropDownList et al. the list items themselves are responsible for behaving appropriately, for example having hover color and being selectable, but there's no mechanism to assure that, or to automatically have a hoverable "parent" element underneath them. See for example the style FileSelectorFilterText (again, may be badly named since it's also used for other purposes) for an example of a text that is suitable as a list item.

**Comment by rasteron** [comment]
Ok thanks for the info Lasse.
