### ISSUE TITLE
Consider searching EMSCRIPTEN_ROOT_PATH from EMSCRIPTEN env. var?

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#871]
Hi,

when using the Emscripten SDK, sourcing the `emsdk_env` script will get one into an Emscripten build environment. In this environment, there's a standard `EMSCRIPTEN` environment variable that points to the directory where `emcc` resides in. I notice when building that `cmake_emscripten.bat` was not able to find Emscripten directly via that. Perhaps if user doesn't set `-DEMSCRIPTEN_ROOT_PATH=x` in CMake command line, then the canonical `EMSCRIPTEN` environment variable could be searched?

**Comment by weitjong** [comment]
What a nice surprise!

The short reason for that is because ```EMSCRIPTEN``` environment variable is already used by our own build system for other purposes. Besides ```EMSCRIPTEN```, we also have ```ANDROID```, ```RPI```, etc. They are boolean option to tell our build system which CMake cross-compiling toolchains to use. But perhaps, we can rename it to avoid the name clash.
