### ISSUE TITLE
Windows build error on Emscripten

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#872]
Tried building Emscripten version on Windows, and I'm getting this kind of peculiar error:

    C:\code\Urho3D\build_emcc>mingw32-make
    [  9%] Built target FreeType
    [  9%] Built target JO
    [ 10%] Built target LZ4
    [ 11%] Built target PugiXml
    [ 11%] Built target rapidjson
    [ 11%] Built target SDL
    [ 11%] Built target StanHull
    [ 12%] Built target STB
    [ 13%] Built target Detour
    [ 15%] Built target DetourCrowd
    [ 15%] Built target DetourTileCache
    [ 17%] Built target Recast
    [ 26%] Built target Box2D
    [ 55%] Built target Bullet
    Scanning dependencies of target Urho3D
    [ 56%] Building CXX object Source/Urho3D/CMakeFiles/Urho3D.dir/Resource/JSONFile.cpp.o
    [ 57%] Linking CXX static library ..\..\lib\libUrho3D.a
    Merging all archives into a single static library using emar
    [ 99%] Built target Urho3D
    [ 99%] Performing build step for 'PackageTool'
    [ 71%] Built target SDL
    [ 73%] Built target LZ4
    [ 77%] Built target LibCpuId
    [ 78%] Building CXX object CMakeFiles/PackageTool.dir/PackageTool.cpp.obj
    In file included from C:/code/Urho3D/build_emcc/include/Urho3D/Core/../Core/../Core/../Math/../Math/../Math/../Math/../Math/MathDefs.h:27:0,
                     from C:/code/Urho3D/build_emcc/include/Urho3D/Core/../Core/../Core/../Math/../Math/../Math/../Math/Vector2.h:26,
                     from C:/code/Urho3D/build_emcc/include/Urho3D/Core/../Core/../Core/../Math/../Math/../Math/Vector3.h:25,
                     from C:/code/Urho3D/build_emcc/include/Urho3D/Core/../Core/../Core/../Math/../Math/Vector4.h:25,
                     from C:/code/Urho3D/build_emcc/include/Urho3D/Core/../Core/../Core/../Math/Color.h:25,
                     from C:/code/Urho3D/build_emcc/include/Urho3D/Core/../Core/../Core/Variant.h:27,
                     from C:/code/Urho3D/build_emcc/include/Urho3D/Core/../Core/Attribute.h:26,
                     from C:/code/Urho3D/build_emcc/include/Urho3D/Core/Context.h:25,
                     from C:\code\Urho3D\Source\Tools\PackageTool\PackageTool.cpp:23:
    c:\mingw64\include\c++\4.8.3\cstdlib:178:10: error: expected unqualified-id before '__int128'
       inline __int128
              ^
    CMakeFiles\PackageTool.dir\build.make:62: recipe for target 'CMakeFiles/PackageTool.dir/PackageTool.cpp.obj' failed
    mingw32-make[5]: *** [CMakeFiles/PackageTool.dir/PackageTool.cpp.obj] Error 1
    CMakeFiles\Makefile2:68: recipe for target 'CMakeFiles/PackageTool.dir/all' failed
    mingw32-make[4]: *** [CMakeFiles/PackageTool.dir/all] Error 2
    Makefile:126: recipe for target 'all' failed
    mingw32-make[3]: *** [all] Error 2
    Source\Tools\CMakeFiles\PackageTool.dir\build.make:109: recipe for target 'Source/Tools/PackageTool-prefix/src/PackageTool-stamp/PackageTool-build' failed
    mingw32-make[2]: *** [Source/Tools/PackageTool-prefix/src/PackageTool-stamp/PackageTool-build] Error 2
    CMakeFiles\Makefile2:985: recipe for target 'Source/Tools/CMakeFiles/PackageTool.dir/all' failed
    mingw32-make[1]: *** [Source/Tools/CMakeFiles/PackageTool.dir/all] Error 2
    Makefile:148: recipe for target 'all' failed
    mingw32-make: *** [all] Error 2

**Comment by weitjong** [comment]
```PackageTool``` is a host tool to package our game assets into a single *.pak file. As all the other host tools, they have to be built using compiler toolchain native to the host system (as opposed to target system). Regardless of which target system and target compiler toolchain is being used in the build, our build system is capable of configuring CMake to use another native compiler toolchain to build the host tool within a single build process. In your case, the target system is being built using Emscripten compiler toolchain and the PackageTool is expected to be built using MinGW compiler toolchain (since you are on Windows).

**Comment by Stinkfist0** [comment]
MinGW-w64 seemed to be the path of least resistance for me. I gathered up Urho Emscripten Windows build instructions here earlier this year: http://urho3d.prophpbb.com/topic831-100.html

**Comment by juj** [comment]
I am using MinGW64 currently. Building with `VERBOSE=1`, the command line for the build looks like 

    c:\mingw64\bin\g++.exe   -DGLEW_NO_GLU -DGLEW_STATIC -DURHO3D_ANGELSCRIPT -DURHO3D_LOGGING -DURHO3D_NAVIGATION -DURHO3D_NETWORK -DURHO3D_OPENGL -DURHO3D_PHYSICS -DURHO3D_PROFILING -DURHO3D_STATIC_DEFINE -DURHO3D_URHO2D -Wno-invalid-offsetof -ffast-math -m32 -static -static-libstdc++ -static-libgcc -fno-keep-inline-dllexport -O2 -DNDEBUG @CMakeFiles/PackageTool.dir/includes_CXX.rsp   -o CMakeFiles\PackageTool.dir\PackageTool.cpp.obj -c C:\code\Urho3D\Source\Tools\PackageTool\PackageTool.cpp

but googling, here, http://sourceforge.net/p/mingw-w64/bugs/401/ , it is said of MinGW64: "Toolchain is not multilib capable, -m32 not expected to work.", which looks like the issue here. I'll try the 32-bit MinGW  instead.

**Comment by cadaver** [comment]
This probably comes from the default CMake setting of URHO3D_64BIT=0, which would try to build the executables as 32bit. However the bitness shouldn't strictly matter when the tools are only being built as a byproduct of a cross-compilation, so would it be possible to just disable the bitness switch in that case?

**Comment by weitjong** [comment]
I actually haven't done any Emscripten build on Windows host, but I don't expect it to be of much difference than on Linux host. On my Linux system, the PackageTool on the Emscripten build has ```-m64``` set correctly. The fact that it has this flag set meant the Urho3D-CMake-common module has detected that the native/host compiler toolchain is capable of building 64-bit target. The detection logic is here: https://github.com/urho3d/Urho3D/blob/master/CMake/Modules/Urho3D-CMake-common.cmake#L48-L51
There is nothing being hardcoded. The compiler is either 64-bit capable or not, and got the ```-m64``` or ```-m32``` flag set, respectively.

I do have 64-bit MinGW-W64 compiler toolchain on my Windows7 VM though. After ensuring my PATH environment variable is pointing to this toolchain, the command ```echo |gcc -E -dM -``` produces a list of predefined macros and I can confirm the ```#define __x86_64__ 1``` is there in my output as expected. So, if I could setup an Emscripten build on my VM, I bet the host tool building would get the ```-m64``` flag. I could not setup Emscripten build now because my VM is low on disk space at the moment.

**Comment by weitjong** [comment]
> This probably comes from the default CMake setting of URHO3D_64BIT=0, which would try to build the executables as 32bit. However the bitness shouldn't strictly matter when the tools are only being built as a byproduct of a cross-compilation, so would it be possible to just omit the bitness switch (in the Urho3D-CMake-common file) in that case?

Your wish is my command :smile:

**Comment by cadaver** [comment]
Thanks! Now let's see if this fixes juj's problem. Emscripten builds have tended to be fragile on Windows for me as well but it has been hard to pinpoint the exact cause; mostly I've gotten the CMake error that the "compiler cannot build a simple test program"

**Comment by juj** [comment]
Thanks for the change! I tested this now and see that the Emscripten build does complete ok on MinGW64 as well. I hit another error on build with latest emsdk incoming on missing `posix_spawn` symbols, but that actually looks like an issue in our end, since I don't think Urho3D would ever invoke `posix_spawn` by itself?
