### ISSUE TITLE
Compile Urho3D for Sailfish OS

### ISSUE THREAD

**Issue by osanwe** [urho3d/Urho3D#876]
Hello!

I want to try to use Urho3D on Jolla Sailfish OS which is arm linux factually. How could I change cmake files for building Urho3D for armv7h platform?

Thanks in advance!

**Comment by weitjong** [comment]
It should be possible but not that easy to port to as compared to Raspberry Pi, simply because the latter has larger community and documentation on how to access the GPU.

It is not the CMake files that you need to worry about but you can start by searching all the places where the RPI keywords appear and study them. I think the biggest issue is to port the C/C++ code to support the Jolla's hardware. Take SDL sub-library, for example. SDL supports Android and RPI out of the box, so there is not much of a problem to port Urho3D to these two platforms. So I suggest you first check whether SDL supports Jolla or not.

**Comment by osanwe** [comment]
Yes, jolla supports SDL. There are a [brief tutorial](https://together.jolla.com/question/22379/porting-sdl-20-game-to-sailfish/?answer=22493#post-id-22493) and small examples ([1](https://github.com/sailfish-sdk/sdk-sdl-project-example) and [2](https://github.com/lanurmi/sailfish-minimal-sdl)).

Is I understand right that I should build Urho3D with MerSDK environment, not just on my own computer?

**Comment by weitjong** [comment]
In that case it looks very promising, I have no exposure to this MerSDK before, but from the link you provided it appears the SDK has a sysroot for development, so it does not look so much different compared to Android and Raspberry Pi. Having said that, I am afraid you are on your own because none of the core team members I am aware of have the actual device or incentive to perform this port.

**Comment by osanwe** [comment]
Okay, I started to trying build Urho3D for Sailfish, but this OS uses wayland instead of X11. Therefore how can I change `libX11-devel` and `libXrandr-devel`?

**Comment by weitjong** [comment]
Our X11 dependency is coming from SDL itself. Urho3D does not depend on it directly. So, rather asking us how to switch this dependency, you should ask SDL team how to enable the Wayland (and disable X11). We have not even attempted to enable Wayland on our Linux desktop platform.

**Comment by cadaver** [comment]
This may be just a question of adapting back SDL's original CMakeLists. We have a hacked-together version that only supports X11, because originally SDL's CMakeLists was broken.

**Comment by weitjong** [comment]
@osanwe You may want to know that we have integrated original SDL's CMakeLists.txt in our current master branch. Building using Wayland video driver is now a valid build option to choose from provided you have the right devel packages installed.

**Comment by weitjong** [comment]
Closing as there is no response to this issue.
