### ISSUE TITLE
doc generation pollutes source tree

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#879]
Urho3D/docs/CMakeLists.txt dumps the following files into Urho3D/docs
  AngelScriptAPI.h
  ScriptAPI.dox
  LuaScriptAPI.dox
This is done deliberately with a CMAKE_SOURCE_DIR directory.  The comments talk about "desired" side effects from doing this.  However it's creating at least 2 undesired side effects.  1) CMake builds are generally intended to allow so-called "out of source" builds where the source tree is left pristine.  This allows the CMake build master to delete the build directory and start over clean.  2) the dump messes up "git pull".  It complains about new local files that need to be resolved.  Both of these side effects are annoying.  Please find a clean way to implement the desired build dependencies.

**Comment by weitjong** [comment]
It is desired from the core team member's point of view, at least it was. Before the time we have automated the online documentation update via Travis CI, we were the one running the doc build command locally before each push. So, to have those doc artifacts in the right directory in the source tree is therefore desirable. A single ```git add``` command would stage all the changes including doc update for us. Now we have trained a robot to do all this for us. But the steps are almost identical with the manual one. So, again having the artifacts in the source tree makes our automation scripts simpler. 

Although there should be a way to keep both devs and users happy, I would not put it as high priority item. Contribution from other who would like to try is welcome.

**Comment by weitjong** [comment]
I think we might later introduce another new build option (mark as advanced) only to be used by dev who has "push privilege" to our Urho3D repository. After that all the build artifacts i.e. newly generated source files or newly generated dox files will always be located somewhere in the build tree (for normal users). When the option is turned on by the dev then extra custom steps will be added to copy back some of the required build artifacts to the desired location in the source tree to facilitate dev to push them to master branch.

You may ask why we would want to push a few of our build artifacts to master branch. That's because we want to lower the barrier to build Urho3D project as much as possible. As strange as it might sound, not all users could figure out how to setup their build environment properly as Urho3D library devs do, although our library users are developers themselves. So having those artifacts in the repo would allow those users to use them directly in their build instead of going through all the loop to generate them again locally.

**Comment by bvanevery** [comment]
To be honest I'd try to educate users on what to do, by copious informative messages galore in the CMake build itself.  "You need this dependency, you need that dependency."  Part of what I've been talking about regarding dot / Graphviz.  I'm not sure if "dumbing things down for users" is what you're proposing, but I do not believe in that, in any event.  It is important to train users.  That's what I learned having a network support job a long time ago back in college, with an office full of mainly tech ignorant people.  If you train them, their skill grows and they become self-sufficient.  If you don't, then you are forever doing repeated work holding their hands.

**Comment by weitjong** [comment]
Nobody is suggesting that. With the new option being introduced, it will be, well, just another option for our user to explore when he or she thinks is ready. But we would like to make our build tree as easy to configure as possible for new comer. If you have a better idea on how to fix this problem, you are welcome to share it with us.

**Comment by bvanevery** [comment]
My CMake is too rusty to get into it right now, but back in the day, I implemented things like three stage self-bootstrapping compiler builds.  I may have done it by having CMake invoke CMake.  I would start on such things by insisting that the source tree is never polluted under any circumstances.  I consider it a baseline for solving such problems incrementally.  I will look at this when / if I get some dynamic lighting going.
