### ISSUE TITLE
AngelScript Update ?

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#892]
This is a feature request.

Maybe it will be the right time to update AngelScript in Urho3D there has been a lot of bugfixing and new usefull features added lately :) 

Thank You !

**Comment by JSandusky** [comment]
I'll submit a PR in a few days once I've fiddled with 2.30.2 (unless Nitelordz beats me to it - I know he's using at least 2.30.1). I never went through and checked all the samples for 2.30.1, have to do that first.

Might need a PSA as there were some changes in 2.30.1 that changed how type-casting is registered (APITemplates methods should cover most common cases) and the addition of "protected" class members makes private members truly private instead of being the equivalent of protected. I don't believe the private/protected changes affect any of the samples/editor.

**Comment by OldSnake22** [comment]
Nice, looking forward to it.
