### ISSUE TITLE
Navigation crash

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#895]
1) Load Ground.mdl https://drive.google.com/open?id=0B_XuF2wRVpw4bmsxNGZSc0VlNXM
2) In sample CrowdNavigation.cpp replace
```
planeObject->SetModel(cache->GetResource<Model>("Models/Plane.mdl"));
```
to
```
planeObject->SetModel(cache->GetResource<Model>("Models/Ground.mdl"));
```

**Comment by cadaver** [comment]
This is the Detour navmesh failing to allocate due to large mesh size, and crashing because its destructor doesn't take the possibility into account. I can fix that, however it'd be good to have input from the people who worked on DynamicNavigationMesh: it seems to allocate 128x more tiles than the ordinary NavigationMesh (#define TILECACHE_MAXLAYERS 128, used in the maxTiles parameter). Is this as intended, 128x sounds quite large.

**Comment by 1vanK** [comment]
How many the limit on the number of polygons?

**Comment by cadaver** [comment]
It's not a polygon limit as such, because you can control how Recast/Detour rasterizes the navmesh, and how many tiles it creates. Look at the "cell size" parameter, which is quite small by default, 0.3.

When your mesh errored, it was something like 1700 x 1700 tiles, which simply failed the memory allocation request; the actual memory area requested would be 1700 x 1700 x 128 x sizeof(dtTile). It's the 128 there which seems questionable.

**Comment by 1vanK** [comment]
I saw a tool for manual creation of navmeshes https://github.com/memononen/recastnavigation  (recast) Is it possible to using it?

**Comment by cadaver** [comment]
Can you elaborate, what is the tool? At present the navigation component always feeds the mesh data to Recast/Detour, and doesn't allow circumventing that path. If you want to be able to bypass that and feed your own data to Detour directly, the best path is to work on that and contribute a PR.

**Comment by JSandusky** [comment]
The maximum should definitely be exposed for configuration.

While entirely possible to just build all the compressed tiles first, then construct the navmesh and tilecache with the right number of layers, there'd still have to be a configurable "grace layers padding" for when a partial rebuild introduces more layers than encountered at the initial build (and it's probably going to produce twice as many layers as you think it should).

Docs will probably need a picture and explanation as to how Recast determines what a "layer" is. What a person casually expects and what they're going to get aren't likely to match.
