### ISSUE TITLE
Add Alpha Cutoff Threshold for Materials

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#903]
Most alpha texture cutouts looks bare so it would be better if there is an alpha threshold (0.0 - 1.0 value) control in default shaders, material xml and editor to make this adjustment.

Blender
![Blender Threshold](https://cloud.githubusercontent.com/assets/3676827/9983370/00ec859c-602c-11e5-8033-a5f2492dc573.png)

Unity
![Unity Cutoff](http://docs.unity3d.com/500/Documentation/uploads/Main/StandardShaderCutoutGrassExample.png)

**Comment by cadaver** [comment]
Consider adjusting the image or writing a customized shader, which uses an additional material shader parameter. Adding alpha cutoff as a default material parameter (similar to MatDiffColor and the UV offsets) would slightly increase rendering overhead for all materials, even for those that don't actually use it.

Also, note that if we must compare, Urho is closer to libraries like Ogre which provide the mechanisms for you to author shaders / materials, rather than something which comes with a well-rounded default set for everything (Unity)

**Comment by rasteron** [comment]
noted, thanks.
