### ISSUE TITLE
Incremental Emscripten mingw32-make build rebuilds libUrho3D.a even though user did not change it.

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#913]
This is not really a critical issue in any way, but marking down in case it's useful. When building Urho3D sample projects with Emscripten, I'm observing that libUrho3D is rebuilding itself even though I did not do any changes to it.

STR:

    git clone https://github.com/urho3d/Urho3D.git
    cd Urho3D
    mkdir build_incoming
    cmake_emscripten.bat build_incoming -DURHO3D_SAMPLES=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
    cd build_incoming
    mingw32-make
    # wait for the full build to finish
    # edit Source/Samples/06_SkeletalAnimation/SkeletalAnimation.cpp and change the number of models to draw, e.g. set "const unsigned NUM_MODELS = 2000;" and save the file.
    # ask for an incremental rebuild of that sample:
    mingw32-make

Observed: The build system builds libUrho3D.a as well, with the following print:

	C:\code\Urho3D\build_incoming>mingw32-make
	[  7%] Built target FreeType
	[  8%] Built target JO
	[  8%] Built target LZ4
	[  8%] Built target PugiXml
	[  8%] Built target rapidjson
	[  8%] Built target SDL
	[  8%] Built target StanHull
	[  9%] Built target STB
	[ 10%] Built target Detour
	[ 12%] Built target DetourCrowd
	[ 12%] Built target DetourTileCache
	[ 14%] Built target Recast
	[ 23%] Built target Box2D
	[ 47%] Built target Bullet
	Scanning dependencies of target Urho3D
	[ 47%] Building CXX object Source/Urho3D/CMakeFiles/Urho3D.dir/Resource/JSONFile
	.cpp.o
	[ 48%] Linking CXX static library ..\..\lib\libUrho3D.a

after which it starts to link all samples again (and unfortunately since Emscripten linker is very slow, taking ages :/).

Expected: Changing code in a sample application should not trigger the recompilation of JSONFile.cpp(?), and the build system should only incrementally recompile and relink the 06_SkeletalAnimation project?

**Comment by weitjong** [comment]
This is a unique problem only happens on Windows host system without MKLINK setup because our build system is forced to fallback to do a directory/file copy instead of creating symbolic links to the actual header files being used. In our build tree configuration we setup a so-called SDK-like include directory structure. This is done so that so all our 3rdparty libs headers can be included using angle bracket format and without ```-I``` to all over the places. We use symlinks in order to avoid stale headers in this directory structure. The setup works nicely on *nix naturally and on Windows when MKLINK is available. When it is not then the fallback copying will be done each time the dependency libs are being rebuilt. This would also work well too but unfortunately CMake only has copy_if_different (for file) and copy_directory (for directory). The latter copies the directory regardless of whether the dir has differed since the last copied or not. This is the root cause of what you have observed above. The ```rapidjson``` include dirs is copied in each rebuilt to keep its headers in the include dir structure fresh but in doing so it inadvertently trigger a recompilation of JSONFile.cpp and the rest follows.

**Comment by weitjong** [comment]
@cadaver I am not sure how we should fix this. I could easily change the ```create_symlink``` macro so that when it is in fallback mode on Windows host system then it only does the fallback once only at the time the build tree is being configured/generated instead of in the post-build step of the 3rd-party library. However, the build tree would then have a risk of having stalled headers should they change after the build tree has been generated. A proper fix would require something like ```copy_directory_if_different``` but I am not going to go there myself as it will make the macro even complicated than it is now, besides the fallback is only for Windows host system which I may not be able to test fully. So, I will leave it as it is unless someone from Windows makes the required changes.

**Comment by cadaver** [comment]
One thing would be to just raise awareness of the issues one will encounter when symlinks aren't available, and perhaps to instruct how to enable them on non-administrator accounts.

The idea of more complicated fallback logic doesn't sound good to me.

**Comment by weitjong** [comment]
> One thing would be to just raise awareness of the issues one will encounter when symlinks aren't available, and perhaps to instruct how to enable them on non-administrator accounts.

Yes, that's a good idea.

There might a way to workaround the above issue without going all the way to fix it proper. There are a number of 3rd-party libraries that uses ```copy_directory``` in fallback mode and yet they do not cause negative effect in overall build time because those libs are only built as necessary. That is, their post-build steps are also triggered as necessary. This is not the case for ```rapidjson``` library. This library target is a "dummy" target because ```rapidjson``` is implemented using headers only. The dummy target is added exactly because we want the post-build step to refresh those headers. The problem is, that "dummy" custom target is always being rebuilt. I see something could be done locally in the rapidjson's CMakeLists.txt to workaround this reported issue.

**Comment by weitjong** [comment]
Users on Linux and Mac OS X may need to regenerate their existing build tree from scratch. CMake does not like the existing rapidjson directory symlink to change type half way. Either manually delete this symlink first before doing a git pull or just regenerate everything from scratch again.
