### ISSUE TITLE
one frame animation is not fully applied

### ISSUE THREAD

**Issue by 299299** [urho3d/Urho3D#920]
same as the title, if you have a animation just has one frame, the animation playing looks odd.

**Comment by cadaver** [comment]
Is this 3D mesh or 2D sprite animation?

**Comment by 299299** [comment]
3D mesh

**Comment by 299299** [comment]
here is the FBX link https://www.dropbox.com/s/482mue1456lw207/1.FBX?dl=0

**Comment by cadaver** [comment]
Thanks. I'm able to see the pose in e.g. open3mod viewer, where it appears to show correctly (a fighting "ready" stance, right?)

**Comment by 299299** [comment]
yes, but just one frame.

**Comment by cadaver** [comment]
The cause was twofold: the fbx (or at least how Assimp sees it) initially has the bones already in the animation's pose instead of bind pose. Also, there is detection in AssetImporter to throw out animation tracks which contain only one keyframe and it's same as the bone's initial transform.

Added new AssetImporter switch -bp, which forces bones to bind pose before saving. This is not something Assimp can give directly, but it can be calculated from the offset matrices. I didn't make this happen by default, as it has potential to go wrong.

Another solution would be to make even your "pose" animations have at least 2 keyframes for all important bones.
