### ISSUE TITLE
Blank audio is continuously outputted even if application does not have any audio playback.

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#924]
Browsers have gone in a direction where they have an audio speaker icon in each tab indicating whether the tab is generating audio or not. See e.g. http://dottech.org/wp-content/uploads/2015/07/mute-tab-Firefox.png .

It looks like Urho3D opens the SDL audio device always at startup, which causes the audio playback icon to show up, as the engine is generating and mixing null audio data to the browser. For small Urho3D demos that don't have any audio, this can be a bit confusing if a user is visiting a Urho3D page, and assumes there should some audio since the icon is showing up, but nothing is heard. I wonder if it would make sense to open up the audio device only on demand, e.g. when the playback of first audio clip is started, or some other appropriate spot?

**Comment by weitjong** [comment]
As I understand Urho3D engine has a parameter to turn on/off the audio device during its initialization. The engine defaults it to on which I guess is a sound choice for a game engine. I think it is the simple sample apps that we have that are not "normal" in that sense. Only a few of them actually output any sound. Fortunately though it is just as easy to switch it off.

**Comment by cadaver** [comment]
Yes, on-demand initialization may be a bad fit for actual game usage because it can induce a stutter, and it's better to fail on start than later.

The C++ samples could be made to default to audio off when compiled for Emscripten in the Sample::Setup() phase (and the few that require it, re-enable it explicitly). Script examples don't have similar access to the engine startup parameters, so it will need re-examining if/when scripting is supported on the web platform.

**Comment by weitjong** [comment]
I switch if off by default without checking if it is targeting HTML5 platform first. Reason being on Linux platform when ALSA buffer is under run then the samples also spam the log because of it.

**Comment by cadaver** [comment]
Ok, that's fine.
