### ISSUE TITLE
debug draw physic world will still draw constraint which is not enabled

### ISSUE THREAD

**Issue by 299299** [urho3d/Urho3D#964]
How to reproduce:

 1. test with 13_Ragdolls.as
 2. set constraint.enable = false
 3. test with physics world debug draw on.
 4. you will see the debug draw of constraint is still visible even constraint is not enabled

**Comment by cadaver** [comment]
This seems to be the expected behavior of Bullet. When the constraint is disabled, it still exists in the physics world, it just doesn't affect the connected bodies. The Bullet world class doesn't render a disabled constraint with a different color either. I suggest raising this issue on the Bullet project's issue tracker, if you're interested. For now, I'll make Constraint::DrawDebugGeometry() to behave the same.
