### ISSUE TITLE
Fonts rendering issue ? 

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#968]
Please look on the image below how the "e" letter is close to the "T" capital letter. I don't know anything about how fonts rendering is working but is there aby way to tweak how letters "bounding box" is working ? Also can you update the freetype library cadaver ? There is numerous issues fixed in the latest revision of freetype library.

![font](https://cloud.githubusercontent.com/assets/8931643/10576534/3390bbaa-7664-11e5-9ccd-241b53b9ebac.png)

Thanks !

**Comment by cadaver** [comment]
For font spacing / advance, we are relying on the kerning values as given by FreeType. Because there is more space on the right side, it looks like the "e" is rendered more to the left than it should be, but it's hard to say if anything can be done to this apart from updating FreeType, or tweaking the font file itself.

Note that I am certainly not the sole person that can update libraries in the Urho project (or do anything else, for that matter) so there's no need to refer explicitly to me.

**Comment by cadaver** [comment]
Btw. can you tell what font it is, if it's publicly available, and what size you are using, so that the possible effect of FreeType update can be tested?

**Comment by OldSnake22** [comment]
I have uploaded the font for you here: https://mega.nz/#!b1pH2SxQ

I use 10 as font size.

**Comment by cadaver** [comment]
Thanks.

**Comment by cadaver** [comment]
It turns out that proper rounding of the fixed point font sizes / offsets is enough to fix this. Freetype update is also sitting in a branch, but it broke at least the default fixed-width font (made it not fixed width) so I'm reluctant to merge that. Anyone is welcome to work on that branch, though; I will probably not touch it for now.
