### ISSUE TITLE
WriteDrawablesToOBJ doing export with geometry mirroring for scene's objects

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#975]
I trying to use this ability of editor and find that my scene(and all objects) are mirrored.
also I found that models before exporting apply theirs node's transform
Drawable.cpp 
468         Matrix3x4 transMat = drawable->GetNode()->GetWorldTransform();
510                     vertexPosition = transMat * vertexPosition;  

but why they are mirrored?

**Comment by JSandusky** [comment]
Because of handedness. The coordinates are in Urho's left handed system.

Will have to add flip and swap axes in a dialog before exporting as some tools like Blender and Substance Designer that I tested have absolutely horrid OBJ import.

> also I found that models before exporting apply theirs node's transform

That's intended. Drawables are exported as they are present in the scene. Debatable whether the transform should be applied when a "single" drawable is selected.

**Comment by JSandusky** [comment]
Pull request #977 adds options for right handed export (the mirroring you describe) and Z up axes (relevant to Max and other Z up tools).

**Comment by MonkeyFirst** [comment]
Thanks, I will check this after merge.

**Comment by MonkeyFirst** [comment]
Well, I check this, and now orientation in exported files is fine.
