### ISSUE TITLE
.exe samples do not have resource paths

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#994]
I am pretty sure that I have run .exe samples just fine in the past, either from within Visual Studio, or clicking on them in \bin when they're in the build directory.  Now none of them work, they all give the same message: "ERROR: Failed to add resource path 'Data', check the documentation on how to set the 'resource path prefix' "  I deleted the build directory and rebuilt clean, to be sure of the behavior.  This observed on both Windows 7 and Windows 10 machines.  I do get a big MKLINK error on both systems when first configuring CMake, but not subsequently. 

.bat samples run fine because they explicitly pass a Data directory option to the Urho3DPlayer.

Note that hardwiring a single path for the build directory is not desirable, as the samples will be installed and need to be runnable from their final installation directory.  Yet it is still desirable to have them be runnable from the build directory, so that people can trace the code with a debugger.  This furthermore implies that using a global environment variable to specify resource paths is not desirable.

Although the Docs do specify some ways to cause the samples to work, I submit that all of the methods given in the docs are wrong / this is a bug by design.  Samples should just work.  The build knows where the resources are, and where they should go.  This should be automated and not require user intervention nor reading the docs.

**Comment by weitjong** [comment]
I believe you were referring to the "past" time when we used to output all our binaries directly into the "Bin" directory in the source tree. Some of you frown on build system that touches the source tree in the build. This topic has been discussed in the forums and also in our issue tracker before, so I will not try to explain the rationale behind it again here. Please search for them. The changes were done prior to 1.4 in the build system refactoring branch.

In a nutshell the problem arises because the binaries are now only available in the build tree, while the Data and CoreData are only available in the source tree. When the source and build tree is the same, the binaries are runnable out of the box, however, we recommend our users to use out-of-source build tree. The documentation describes ways to bring the two together. I don't think it is too much to ask our users to read our documentation before building and using Urho3D. If the documentation is still deficient, you may help to make it better.

Of course, we can do as per your suggestion to automate to implement one of the documented way to make those sample binaries in the build tree to work out of box. However, doing so would only delay the inevitable. Sooner or later, user need to understand this "resource prefix path" concept because they are on their own once the binaries are installed elsewhere or when user start to build their own binary with customized asset directories.

What do others think? Should we automate it? Now that we have a macro to create symlink with fallback to copying, we could create the Data and CoreData symlinks in the build tree pointing to source tree, if we really want to.

**Comment by bvanevery** [comment]
It is not a sin to copy static assets to a build tree, if it works.  My Visual Studio based build tree is 1.2 GB as is.  What's another 0.25 GB of assets?  And really, the issue of copying only arises out of a desire to do things the same on all platforms, due to Unix vs. Windows directory conventions.  Windows users certainly don't need anything in a \share directory, they'd be happy with stuff in something like \bin\data just fine.

Another things apps typically do is have some place where they look for the pointer to the info, something other than an environment variable.  If that doesn't exist, apps typically make guesses based on directory structure.  The risk with that is aliasing an inappropriate project.  Especially, in an environment with multiple builds, searching up a couple of relative directories and coming back down again can lead to the wrong place.  I would think these cases wouldn't be that tough to solve though, as one only needs to account for the (CMake source, CMake bulid) and (installed) cases.  Everything else can fail; it's weird and up to whatever the user decided to do themselves.

GNU Automake had an exotic post-configuration step for just this circumstance, for the reality that the build and final installation directories are different, and things need to work in both places.  I have forgotten how they did it, nor is it strictly relevant to CMake.  I just don't recall CMake having a similar staging notion.  Probably anything can be achieved with enough file configurations and "cmake calling cmake" tricks though.

It is definitely too much to ask that people build docs before doing anything else, as the docs may not even build.  Many of the bugs I've filed over the past 6 months, trivial though they may seem, have arisen in this kind of "chicken and egg just trying to get things going" circumstance.  Asking for manual intervention when automation should just work, puts off new users.  I'm a person who has the discipline to try to do something about it, at least to file bugs and research why something doesn't work.  How many people simply don't, just give up and walk away?  I don't think Urho3D is at a point where you can afford "friction" getting things working.  If you were as popular as Unity or some such maybe you could say eh, who cares about the small things, make 'em learn.

Delaying "the inevitable" as you call it *should* happen.  That's how you actually get people to go up learning curves, by hiding the cognitive load until it is really really needed.  Shouldn't need to know any of this, just to see if Urho3D works.  Should just work.  A way to IMPRESS potential users with a build, is to have it build out of the box, no problems, no special steps, just suddenly you're looking at samples / demos of stuff that do something worth paying attention to.  That's a resume for a project, a way of demonstrating, oh, these guys are pretty hard core about builds, they don't fool around, this is a tight ship.  People don't sit down and read a big beefy pile of docs for issues X, Y, Z, P, D, Q when they're evaluating something.  Sure this is *one* issue, but when issues like this are not held in check, they become a creek and then a river.  And then potential new users say no, they don't want to swim in a river of small nagging details.

I don't think I could make my own buildmaster sensibilities any more clear, so I'll await anyone else's opinions if they have them.

**Comment by bvanevery** [comment]
Brilliant upon brilliant thought, just had to get a head of steam up to clear my mind.  ;-)  Samples directory should have a .txt file that all .exe's refer to for the magic location of the assets.  Build system should substitute appropriate DIFFERENT values for build directory and install directory, at build and install time respectively.  Problem solved.

**Comment by yushli** [comment]
First let me say that Urho3D's build system is excellent! It just worked when I first time ran it and I was impressed. It is getting better and better with out-of-source build tree etc. 
And I agree to automate the smylink/copy the data folder to the build tree just to let the first time user run the demos smoothly. Actually I would suggest set URHO3D_SAMPLES to ON by default just to let the first time user see what Urho3D's capable of without needing to learn anything at first.

**Comment by weitjong** [comment]
I think I hear you clearly. It actually does not take much work to automate the script to call the macro for creation of the symlink, however, it is the fallback to copying part that I am little worry about. On *nix the symlink works nicely, however, on Windows it relies on MKLINK which by default normal Windows user account does not have the privilege to use and so I am afraid the majority of Windows users would get fallback to file copying instead. The problem is, this file copying is only done initially when the build tree is being generated. So, it potentially get stale pretty quickly when the source tree get updated. I personally would find it confusing when there are multiple copies of same thing exists in my file system, but of course I don't have such problem because I am a Linux user so I could use symlinks to my heart's content. The next best thing we could do is to do the file copying again and again on each build which slow down the build on Windows platform unnecessarily.

We have online documentation exactly so that our users don't have to build the doc manually just so that he/she can read it to find out how to build the software. I think we can safely assume all our new users would come to http://urho3d.github.io first to find out more about Urho3D before doing anything else. We could put the *.txt file like you proposed in the sample directory but I doubt its usefulness. If user fails to read the online documentation before trying, I doubt that user would read the *.txt file even if it is being called README_FIRST.

**Comment by cadaver** [comment]
I don't have a strong opinion as such, but have nothing against linking/copying the asset directories. I wouldn't be too worried of the stale assets caused by copying, because I'd assume a novice user would be happy to edit the copy of the assets in the build directory to try some things out, and a more advanced user would either fix the MKLINK privileges, or customize where the assets are being read from altogether.

We could well enable URHO3D_SAMPLES by default (since that happens in the packaged binary builds anyway), and also URHO3D_LUA.

**Comment by yushli** [comment]
It is good to enable URHO3D_SAMPLES by default and have the linking/copying as well. Also another suggestion: when running cmake_xxx without the build parameter, now it says :
./cmake_generic.sh 
Usage: cmake_generic.sh /path/to/build-tree [build-options]
At first run I don't know what /path/to/build-tree is referring to.
 Can we change it into if no build tree parameter provided, it defaults to ..\Urho3D_1.5_build? then prompt to say that since no build tree parameter is provided, the build tree will be generated in ..\Urho3D_1.5_build, is it good to go?

**Comment by weitjong** [comment]
Ok, it seems there are no objection to have automation for symlinking/copying the asset directories. Agree to enable URHO3D_SAMPLES and URHO3D_LUA by default.  Personally I always have these turned on in all of my build trees.

As for the prompt, I do not in favor of it. Typical CLI commands would just terminal gracefully when there are missing mandatory arguments. See ```cmake``` or ```ccmake``` for example.

**Comment by yushli** [comment]
That sounds good enough for me. Look forward to the new release!

**Comment by bvanevery** [comment]
Darn it, why did my "brilliance" have to come in the wee hours of the morning so I can't explain clearly?  By a *.txt file, I didn't mean a README.  I meant that the *.txt file contains the absolute path of where the assets are.  Call it something brilliant like resources.ini.  The sample apps read the .ini to determine the location of the resources.  Problem solved.  Different .ini contents for build and installation trees.  That can be achieved several different ways in CMake.

**Comment by weitjong** [comment]
> Darn it, why did my "brilliance" have to come in the wee hours of the morning so I can't explain clearly? By a *.txt file, I didn't mean a README. I meant that the *.txt file contains the absolute path of where the assets are. Call it something brilliant like resources.ini. The sample apps read the .ini to determine the location of the resources. Problem solved. Different .ini contents for build and installation trees. That can be achieved several different ways in CMake.

I actually understand it correctly the first time. But I was saying it won't work because CMake cannot alter the content that text file in the manner you described so in the end it needs to be maintained manually should we have implement the binary to read the text file this way.

**Comment by bvanevery** [comment]
Can't alter a text file??  Impossible.  It's going into a build directory, and configuration time is not the only time when CMake can generate the contents of a file.  "Maintained manually" makes no sense:  it is the user who decides what their installation target is, and things have to work there too.  Incidentally, right now they do not.  Your patch makes samples work in the build directory just fine now, but not when installed.  Suggest you re-open this.

You can take advantage of a likely circumstance when a Windows user installs Urho3D.  They will have had to acquire Administrative permissions to do it!  mklink will probably work.  For instance, I have to start Visual Studio with "Run As Administrator" if I want to do an install, so I think anything executed by CMake from within VS will have administrative rights.  This presumes that the user is installing to directories that require administrative permissions to access, such as C:\Program FIles.  That's the default, so worth assuming IMO.  Some user someday will suffer the weird corner case of things breaking if they install somewhere else, don't need any special permissions to do it, and mklink fails, but heck they wanted to be weird so who cares.  It will rarely occur if ever.

If you pursue this strategy, a comment in the build files that "permissions are only available at install time" would be advisable.

**Comment by weitjong** [comment]
> Can't alter a text file?? Impossible.

You have misunderstood me. I didn't say CMake cannot alter a text file. I said CMake cannot alter the content of the text file in the manner you described. I have mentioned in my earlier comment that CMake only knows where are the source tree and the build tree, but it does not know where the install directory will be at the time the build tree (and this text file) is being generated. We could naively use CMAKE_INSTALL_PREFIX for this purpose, however, it is not bullet proof especially on *nix platforms (they can use DESTDIR environment variable at the installation time for doing a staged installs). Besides, I don't think everyone would want to have their binary to read an external file that only contains the resource prefix path.

> Your patch makes samples work in the build directory just fine now, but not when installed.

This is exactly the point I made earlier. Sooner or later user (or more precisely developer) need to know about this thing in order to use Urho3D on their own. Let's just assume we could make certain assumption on where the asset directories are relative to the binaries in the installed location, we could then preset that in all of the binaries that we shipped by default. So, all our installed sample binaries work out of the box. Great! But user learns nothing yet until he/she tries to build his/her own app and encountered the resource prefix path error for the very first time.

You could of course say, this is a crap design. Why doesn't Urho3D engine just assume the asset directory always located in the same directory where the binary is? This was how it used to be, anyway. Well, we actually move away from that assumption for a good reason, a few in fact. One of them is, it allows us to bundle the assets into Mac OS X bundled app.

**Comment by bvanevery** [comment]
There is still the possibility on Windows of just doing a mklink at installation time.  Before I consider additional technical remedies, it is best to address a pretty basic design consideration.  Otherwise this and other things are just a waste of our time.

I'm trying to get this so that samples work out of the box, during build and install.  Is that *your* goal?

Or, do you place a high priority on forcing the user's education?  Even if that means some things about the build are broken?
